### ISSUE TITLE
One page template with angular?

### ISSUE THREAD

**Issue by urosjarc** [mkdocs/mkdocs#1054]
Is it possible to make one page template, base on angular? The problem is is that mkdocs template engine uses `{{ conent }}` the same templating system that angular uses...

**Comment by waylan** [comment]
It seems to me that if you want a "one page app" then MkDocs is not a good fit. However, it you have some valid edge case, I suppose it could work. If you need to combine both Jinja templates and Angular templates, then whichever is proceseds second will need to be escaped (wrapped in raw) so that the first template engine skips over it. See Jinja's [documentation][1] for details.

[1]: http://jinja.pocoo.org/docs/dev/templates/#escaping

**Comment by waylan** [comment]
I'm closing this as there does not appear to be any actionable item here.
