### ISSUE TITLE
Filenames with digits at the beginning return 404

### ISSUE THREAD

**Issue by agonzalezro** [mkdocs/mkdocs#1060]
Steps to reproduce:

```
mkdocs new test
```

Edit the `mkdocs.yml` to add this:

```
site_name: My Docs
pages:
    - 'Index': 'index.md'
```

Everything works fine.

Now, edit it again:

```
site_name: My Docs
pages:
    - 'Index': '00_index.md'
```

And, of course, move the file:

```
mv docs/{,00}_index.md
```

It starts returning 404 even when I restart the server.

**Comment by agonzalezro** [comment]
Ok, I've investigated a little further and it seems that the problem is that `mkdocs` is always expecting a `index.md` even when we use `pages` key on the yaml?

If I do this:

```
site_name: My Docs
pages:
    - 'Index': 'index.md'
    - 'Something': '00_index.md'
```

Being `index.md` and `00_index.md` the same file (`ln -s`) it just works.

Please, let me know if you prefer to close this issue and open a new one, or if this is a "feature". 

Thanks for your hard work on this!

**Comment by waylan** [comment]
This is a feature. All (major) web servers work this way (with their default config). The file which is served when just the directory is requested is the file named `index.html`. All other files need to be explicitly requested. We replicate that behavior in our dev server so that you get the same behavior as you will get with any hosting provider out there.
