### ISSUE TITLE
Creation of PDFs from mkdocs

### ISSUE THREAD

**Issue by mr-gosh** [mkdocs/mkdocs#1064]
is the creation of PDFs from the created docs a planned feature?

**Comment by waylan** [comment]
Closing this as a duplicate of (at least) #58, #374, & #480.

**Comment by henryiii** [comment]
Shouldn't at least one of these remain open so that people can more easily find it and not keep opening new issues? It's the one thing I keep checking on; it's something I don't want to lose moving off of GitBook. (Any reasonable method would be fine, like a way to "print" the HTML pages to a nice PDF).

**Comment by martinbira** [comment]
There is a plugin, https://comwes.github.io/mkpdfs-mkdocs-plugin/index.html But it seems to be behind on its dependencies
