### ISSUE TITLE
extra_css entry confusion

### ISSUE THREAD

**Issue by sander76** [mkdocs/mkdocs#1096]
In the documentation I read I could add an `extra_css` entry in my yaml file to define extra css files to be included in my page. So I did. But I ran into problems as I found out all css files are loaded regardless of my `extra_css` entry. I checked the log and found a warning message confirming the above.

Only when version 1.0 is released the `extra_css` entry will have any effect. So I could be reading this wrong, but the documentation is ahead of the actual mkdocs release ?

I am currently on release 0.16. Installed through pip. For customization I am heavily relying on the `extra_css` option. Does the current git branch already support this ? Or when is version 1.0 to be expected?

Thanks !
Sander.

**Comment by waylan** [comment]
Yes, you are understanding correctly. This is a transition period. Version 0.16 was just released earlier this month with the updated documentation and the warning issued. We need to give existing users an opportunity to adjust their projects without breaking things. The documentation was updated because that is the behavior you should expect.

We have not yet started working on version 1.0 (we are letting the dust settle on the just released version 0.16)and we don't have any hard timeline. It will be released when it is ready. Note that anything before 1.0 is in beta and not guaranteed to be stable between releases (although we try to provide ample warning and a transition period). But once 1.0 is released, we are committed to supporting that behavior for some time. So we want to make sure we get it right, which may take more time.

**Comment by sander76** [comment]
All clear. Great project!
