### ISSUE TITLE
Add support for renames and redirects?

### ISSUE THREAD

**Issue by migurski** [mkdocs/mkdocs#1102]
In order to handle change over time without showing users a 404, we implemented custom redirect and rename behavior for Mapzen’s documentation. Both are exposed as namespaced `mz:` configuration entries, which works reasonably thought mkdocs displays warnings. 

Would it be possible to integrate this behavior into mkdocs proper? Also, would the [in-progress work on plug-ins](https://github.com/mkdocs/mkdocs/issues/206) be an appropriate pre-requisite for this functionality?

- Renames happen before documentation is generated, and move documents and directories around. With a distributed set of upstream docs, we needed to be able to tweak folder structure prior to running mkdocs. Here is the Python [`setup-renames.py` implementation](https://github.com/mapzen/mapzen-docs-generator/blob/d87f88cc47c465116464d161a0f3f43656174ef2/setup-renames.py) and a [sample rename configuration](https://github.com/mapzen/mapzen-docs-generator/blob/d87f88cc47c465116464d161a0f3f43656174ef2/config/mobility.yml#L5-L18).
- Redirects happen after generation, and are needed to keep users’ old links working. Here is the Python [`setup-redirects.py` implementation](https://github.com/mapzen/mapzen-docs-generator/blob/d87f88cc47c465116464d161a0f3f43656174ef2/setup-redirects.py) and a [sample redirect configuration](https://github.com/mapzen/mapzen-docs-generator/blob/d87f88cc47c465116464d161a0f3f43656174ef2/config/mobility.yml#L37-L40).
- Both are called [from within a Makefile](https://github.com/mapzen/mapzen-docs-generator/blob/d87f88cc47c465116464d161a0f3f43656174ef2/Makefile#L103-L111).

**Comment by waylan** [comment]
Personally, I find the entire redirect-with-a-meta-tag thing to be a distasteful hack. I would only ever do redirects through server configuration (the server returns a 301, 302, 307, or 308 status code as appropriate). Of course, server configuration is out of scope for MkDocs as we only generate static files which should be server agnostic.

On top of that, I realize that many users are hosting their statically generated sites on hosts which do not provide configuration options for those sorts of things. The only real option for such users is to use meta tags. Even so, I'm inclined to put this in the plug-in category rather than something we would include in the core.

**Comment by migurski** [comment]
I agree, though we are limited in our header options because we are hosting docs on S3. A plug-in system would be great, but the discussion issue is very long and very old. Any idea what the outlook is for supported plug-ins?

**Comment by waylan** [comment]
[This comment][1] points to the current state of the Plugin API. Its earmarked for the 1.0 release. We just released 0.17 and anticipate the next point release to be 1.0. However, there are a lot of items tagged with that [milestone][2] (many of them big items), so no timetable on when that will happen.

[1]: https://github.com/mkdocs/mkdocs/issues/206#issuecomment-236259667
[2]: https://github.com/mkdocs/mkdocs/milestone/4

**Comment by migurski** [comment]
Thank you Waylan, that list is very helpful!

**Comment by abitrolly** [comment]
So how does `mkdocs` support renames and redirects?
