### ISSUE TITLE
Unable to completely customize sidebar background colour of ReadTheDocs theme

### ISSUE THREAD

**Issue by chetcuti** [mkdocs/mkdocs#1115]
I'm trying to change the entire sidebar background color, and by customizing the below sections via theme_extra.css I've been able to **almost** do it, however there's one small section of the sidebar that no matter what I do, won't change colours. I feel like I've tweaked every possible item in the CSS but nothing seems to work, so as a last ditch effort I figured I would post here and hope that someone may know how to do this.

Here is a screenshot of what I'm trying to accomplish. I want the brown line above Github and Next to match the rest of the dark colour in the sidebar.

http://content.screencast.com/users/assets/folders/Snagit/media/db1c5db5-795f-4e8b-8e86-cfbdb99b708b/12.23.2016-12.24.png

This is the CSS that I've customized via theme_extra.css to change the rest of the sidebar, but I can't for the life of me figure out how to change the one last section, and it's driving me a bit insane.

`.wy-side-nav-search {`
`    background: #222c32;`
`}`
`.wy-nav-side {`
`    background: #222c32;`
`}`
`.rst-versions .rst-current-version {`
`    background: #222c32;`
`}`

Does anyone have any idea as to what I need to change?

**Comment by waylan** [comment]
The `readthedocs` theme is a clone of a [Sphinx theme][1] of the same name, which is built on top of the [Wyrm][2] framework. The Wym framework is a [SASS][3] framework. The SASS files for the Sphinx theme include a [file full of variables][4]. Conceivably you could copy those SASS files, alter the variable values (using different colors) and regenerate the theme's CSS and the new colors should be applied globally to the theme.

After all, the MkDocs theme is just the Sphinx theme's unaltered CSS files (and images, JavaScript etc) and a custom MkDocs template which mimics the HTML output of the Sphinx theme. So there isn't any reason why you shouldn't be able to [swap out the CSS][5] for a slightly different version. Especially if all you need to change are colors.

By the way, those general purpose frameworks tend to be much more complex than what any single project ever needs. So sorting through a generated project can be difficult. I find it easier to start with the pieces of the framework which are used to generate the output. Also, those frameworks generally have good documentation of the various hooks they use so that theme authors can take advantage of the styles defined in the framework. You may find the Wym framework's documentation will be more helpful in identifying which styles you need to redefine, even if it is a few levels removed form MkDocs. The CSS generated by SASS is not generally human readable, whereas the SASS files are.


[3]: http://sass-lang.com/guide
[4]: https://github.com/snide/sphinx_rtd_theme/blob/master/sass/_theme_variables.sass
[5]; http://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme_dir
[1]: https://github.com/snide/sphinx_rtd_theme
[2]: http://wyrmsass.org/

**Comment by chetcuti** [comment]
Thanks for the reply, but luckily I was able to get it figured out just by going through the CSS. It was a bit tricky to find because it's a border, not a background colour.

For anyone else with the same issue, I just added this to my theme_extra.css.

`.rst-versions{`
`    border-top:solid 10px #222c32;`
`}`

**Comment by brendan8229** [comment]
I've used the tips above to change the colors to my mkdocs page. However, I haven't managed to change it for the header on mobile. Here's the page [http://giraffegeo.com/data]( http://giraffegeo.com/data).  I'd like to change the header color from the standard blue to black. What is the name for that region to use in theme_extra.css?
