### ISSUE TITLE
Override `base_url`

### ISSUE THREAD

**Issue by pgergov** [mkdocs/mkdocs#1123]
Hello,

If this question has already been asked, please excuse me :panda_face: 
Is there a way to override `base_url`, used here - https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/base.html#L19-L23?
The only solution I figured out is to override the blocks where it's used (custom theme-ish like) with my base url specified in the `extra` variable of the config file.

Best,
pgergov :beer:

**Comment by waylan** [comment]
The `base_url` variable is updated for each page to ensure a proper relative path. The assumption is that you would not want to override it. So, yes, the only way would be through theme customization, although I can't imagine why you would want to do that. Seems to me the you should be building your own theme then.

**Comment by pgergov** [comment]
@waylan In my case I wanted to serve the documentation within large Django project & use specific permissions. I collected docs build's statics and i needed to point the `base_url` to the static folder. 

I overrided all imports from the `base.html`, but this is not really clean solution. If you can toss an idea I'd appreciate it :beer: 

I'm going to paste some of the stuff I did just in case someone else comes here:  
* In `mkdocs.yaml`:
```
theme: mkdocs
theme_dir: docs-custom-theme
extra:
  base_url: "/static"
```
**Note:** `/` is where `mkdocs.yml` is located.

In `main.html` inside my custom theme folder:
```
{%- block styles %}
  <link href="{{ config.extra.base_url }}/css/bootstrap-custom.min.css" rel="stylesheet">
  ...
{%- endblock %}
```

**Comment by waylan** [comment]
We always use relative paths and do not support using absolute paths. The assumption is that the entire build will be a self-contained unit. Even if it is served as a subdir of some other system, it still works as-is (which is why we use relative links). I'm summing you are using the same media files (CSS, JS, images, etc) for both the MkDocs site and the Django site. This is not something we support out-of-the-box (that breaks the self-contained unit). So, yeah, you would need to hack/customize the theme to get that to work.

**Comment by pgergov** [comment]
Okay, I understand. Also, what you're assuming is right.

Thanks for the fast answer & keep up the good work!

Cheers :beer:
