### ISSUE TITLE
Make mkdocs a SPA?

### ISSUE THREAD

**Issue by hifall** [mkdocs/mkdocs#1137]
Single Page Applications (SPA) are becoming popular these days. They basically load the whole app upon first access, and issue no more request after that. The result is UX with no page refresh and no delay, which is unparalleled by traditional web pages.

An example of such a SPA document project is: [Slate](https://github.com/lord/slate)

Check Slate's live demo here: [Slate Live Demo](https://lord.github.io/slate/)

Any plan to implement SPA for mkdocs?

Thanks!

**Comment by d0ugal** [comment]
There are no plans to do this in MkDocs itself.

This would be something that a custom theme would do - so we should make sure that it is possible and easy for a custom theme to do this. This would be also useful for people that want a one page theme (that they can easily convert to a pdf).

I think at the moment is is tricky and maybe not possible.

**Comment by waylan** [comment]
I recently stumbled upon a competing static page generator that worked exclusively as a SPA. Unfortunately, I don't recall its name and I apparently didn't save the link. In any event, the single page included a JavaScript Markdown lib and the code to fetch the raw Markdown files from the server and render them to HTML in the browser. It was interesting, but not at all something that MkDocs would become. Personally, if I was looking for a SPA, then I would use that rather than MkDocs.

I would imagine that if MkDocs were do support any type of SPA, then we would render the Markdown pages as HTML fragments (rather than whole documents) and the home page would be the single page which would fetch the fragments and update the body of the page. The trick to doing that would be to define a different template for the home page than the rest of the pages, which is already possible via the (undocumented) `template` meta-data variable (see [build.py#L197][1]). You might be able to get this to work today with a custom theme. If not, I'm sure we can make the necessary adjustments to make this possible. We're just not going to built the theme for it ourselves. If you run into any roadblocks, feel free to file a new issue or, even better, submit a pull request.

Regardless, the concern I have is how do you offer a fallback for those who do not have JavaScript? Do you render both complete HTML pages as well as fragments? That seems unnecessarily redundant. This is not a dynamic site with pages generated on-the-fly by the server. We serve up flat files only, which is already the fastest possible way to serve anything. Yes, with a SPA, you get slightly smaller file size and there is no need for the browser to go through the CSS/JS/etc on each page load. But with browser caching, is is really that much of a gain? 

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/build.py#L197

**Comment by hifall** [comment]
@waylan thanks for your thoughts.

Regarding your concern for those who do not have Javascript enabled, here are my thoughts:
1 various sources state that the percentage of people who browse with JS disabled are anywhere from 0 to 2+, see http://stackoverflow.com/questions/9478737/browser-statistics-on-javascript-disabled for example. Therefore, I would not worry about 1-2% percent of that population;
2 since mkdocs seems to be made for websites and (especially) web apps supposed more complex than a simple web page with a noscript tag, I'd say the percentage of people browsing mkdocs-generated docs are even smaller than 1-2%, since in the real world almost all production websites and web apps require Javascript enabled to function properly. That is to say, if one disables Javascript, he won't be able to use the main website/web app, therefore I don't see it a big problem if he can't use the mkdocs-generated docs.

In addition to the small gain you mentioned, there is actually another one: get rid of page flickering caused by page refresh. Since there is no page refresh with a SPA, navigating through the links feels really slick, and I'd personally prefer it quite much. It sounds like small, but the overall UX is much smoother and more integrate.

**Comment by facelessuser** [comment]
> In addition to the small gain you mentioned, there is actually another one: get rid of page flickering caused by page refresh.

I have to be honest, I don' t think I've ever been on a documentation site and been like: "man, I sure wish I didn't have to see the minimal flicker of a new page render".  I think the perceived advantage here is so minimal, I just can't see the real selling point here.  I can understand in certain applications dynamic page loading *would* be a great benefit, but I just can't really understand the need in a static documentation site.

I feel this the only real advantage here solves a problem that only 1% percent of people would even perceive.  And I feel like that population only perceives it because someone introduced them to SPA and told them that flicker is a negative (which I don't think it really is).  I don't think it is something people are naturally wringing their hands over.

Is this really something people complain about?

**Comment by waylan** [comment]
This discussion is already getting long, but I'll just add one point: There are two situations which are mostly likely to encounter either no or disabled JavaScript. (1) Advanced users who disabled it and (2)scrappers/robots/etc. As MkDocs primary use case is documentation, our target audience are those advanced user, which could (no stats to back it up) mean a higher percentage than the Internet in general. But even if that was not the case, I want Google (and others) to index my site and provide good search results. I'm certain that works with traditional pages but I'm unclear about SPAs. No doubt there are a set of conditions that can make it work, but I don't want to have to figure out what those are and always keep them in mind as I update by site.

**Comment by hifall** [comment]
@facelessuser "I feel the only real advantage here solves a problem that only 1% percent of people would even perceive." I feel relaxed to see that you use "feel", because "only 1% percent of people would even perceive" is a bold statement without any fact support. So that is indeed a "feel".

Same for "And I feel like that population only perceives it because someone introduced them to SPA and told them that flicker is a negative (which I don't think it really is)."

And I don't think either of your feels is right. Your second feel even feels a bit condescending.

The thing is: one can never feel anything imagined into a fact.

One can argue that the downsides of turning this project into a SPA outweigh the advantages, which is what @waylan did. I think you made your points.

**Comment by facelessuser** [comment]
> And I don't think either of your feels is right. Your second feel even feels a bit condescending.

@hifall,  I apologize as I can see I've struck a nerve.  My intentions were not to come off condescending, but I see now how the phrasing was insulting.

My intentions was to express an everyday user view.  As an every day user who is invested in MkDocs, I don't see the problem that is to be solved, nor does it sound like something I'm personally looking to solve.  I've simply never thought the flickering was a problem.  I was addressing the flickering advantage as @waylan made points about caching already.  If flickering turns out to be the only noticeable advantage (and I'm not saying it isn't an advantage) then it seems like a lot of work for very little payoff.  

I guess if there was some other overwhelming advantage, then I'd feel very differently. I can understand how more complex sites might have a problem reloading the entire page every time you load more content in a particular container. SPA would be great for that.  I just think in this case it might be a little bit of over engineering.  Clearly some people feel differently as @waylan  pointed out that SPA document tools exist.  If MkDocs wants to go in this direction, then so be it. As one of the unwashed, average masses, I'm meh on this.  That is all I was trying to communicate, albeit poorly.

**Comment by d0ugal** [comment]
One of the advantages of MkDocs is the simplicity of it's use and the end result. I don't think we are likely to change to a single page application anytime soon in any of the themes we include in MkDocs. Maybe down the road that is what all web sites will look like and we can revisit that.

We **should** let custom theme writers create a single page application if they wish. So this issue should look at the following questions:

1. Is it possible to make a SPA application theme for MkDocs now?
2. if it isn't possible, what needs to change and how easily can we support it?

So, for now, if anyone is interested this probably needs some investigation.

**Comment by hifall** [comment]
@facelessuser thanks for the communication!

**Comment by squidfunk** [comment]
Well, I was planning to do a solution somewhere in the middle with [Material](squidfunk.github.io/mkdocs-material) - loading only the HTML via XHR and injecting it into the body. This should be nearly as good and instant as the desired solution and will require absolute minimal JavaScript and no big SPA framework footprint. Furthermore, it gracefully degrades to full page loads if JavaScript is somehow not available, and we're not talking about general availability which is indeed below 2%. We're talking about bad connections, failed fetches, long waiting times, especially on mobile. In my profession as a web developer I try to get this point across: (let us) make your site work without JavaScript.

**Comment by waylan** [comment]
@squidfunk I'd love to see how this works in a third party theme. As @d0ugal said, if there is anything that gets in the way, we should fix it. Please let us know of any problems you encounter.

**Comment by squidfunk** [comment]
I just prototyped it: https://github.com/squidfunk/mkdocs-material/tree/feature/instant-loading-via-xhr

Loads instantly, I mean really fast. Needs some refactoring, but will make it into `master` and next release.

**Comment by facelessuser** [comment]
@squidfunk Gave it a little spin just out of curiosity. The difference is nice, subtle, but very nice.

I realize this is a prototype and still has much work to be done.  So this is just a question on how the full implementation will work.  I noticed due to the specialized way that content is loaded, that scripts that rely on the page finishing loading in order to trigger `onready` type events no longer work. For instance MathJax code doesn't get converted and I imagine other things would break on pages where people are loading JavaScript to be executed on `onready` events.  How would those things be workable in this environment?

**Comment by hifall** [comment]
@squidfunk I tried your demo, and it looks nice so far! 

We used Slate before and found it quite impressive. Unfortunately, we are unable to put together its recent build possibly due to some Python issues. That's why we are seeking a new solution for our documentation.

Good luck with your nice-looking work!

**Comment by squidfunk** [comment]
> I realize this is a prototype and still has much work to be done. So this is just a question on how the full implementation will work. I noticed due to the specialized way that content is loaded, that scripts that rely on the page finishing loading in order to trigger onready type events no longer work. For instance MathJax code doesn't get converted and I imagine other things would break on pages where people are loading JavaScript to be executed on onready events. How would those things be workable in this environment?

That is indeed a good point I haven't thought of. From the top of my head: I would require to wrap everything in DOMContentLoaded event listeners (= onready), which makes sense anyway and fire this specific event upon page loading. This way it would be executed every time.

But yes, there has some work to be done. Hmm, thinking about it maybe I will include it as a feature (was thinking of feature flags anyway, e.g. for the tabs navigation), leave it off by default for now and declare it as beta. Then, in a few releases maybe I could switch it on by default. I think that's the best way of getting this kind of new features out in themes, because everybody can try it out whether it breaks the documentation and give valuable feedback.

**Comment by waylan** [comment]
As @squidfunk has demonstrated that SPAs are already possible without any modifications to MkDocs and we not are interested in maintaining any such themes ourselves, I'm closing this. If a theme author encounters any specific issues when developing a SPA theme, please open a new issue specific to the encountered problem.
