### ISSUE TITLE
Page variable causes errors when overriding templates

### ISSUE THREAD

**Issue by DominikaK** [mkdocs/mkdocs#1182]
When using MkDocs with a modified readthedocs theme (hosted on readthedocs.io) there is a problem with the `page` variable.

I copied and slightly modified the built-in theme templates, and when building on RTD I get a `jinja2.exceptions.UndefinedError: 'page' is undefined` error on the `page` variable, for example on `{% if page and page.next_page or page.previous_page %}`. 

As suggested here: https://github.com/mkdocs/mkdocs/issues/875#issuecomment-216117876, wrapping the `page` in a separate `{% if page %} {% endif %}` tag removes the error message, **but** the content wrapped this way does not display on readthedocs.io (it's present locally using `mkdocs serve`, however).

(MkDocs version 0.16.2)

**Comment by waylan** [comment]
Which template is that error being raised in? And what modifications have you made?

Also this seems odd. The `if` statement specifically starts with `if page and ...`  for this reason. The rest of the the statement should never get evaluated if `page` evaluates to false. In fact, this is used extensively throughout the templates and no errors are generated. Presumably, your modifications broke something, but without more information I have no way of knowing as I'm not able to replicate the problem myself.

**Comment by DominikaK** [comment]
Here's an example to show the problem:

I've modified the footer template [here](https://github.com/DominikaK/mkdocs-playground/blob/master/templates/footer.html#L19), just adding a paragraph and changing some classes. But the problem occurred above, [in line 3](https://github.com/DominikaK/mkdocs-playground/blob/master/templates/footer.html#L3). After extracting the `if page` tag no error occurs, but the whole section wrapped in the if clause does not generate, as you can see here: http://mkdocs-playground.readthedocs.io/en/latest/, where the Edit on Github button is missing.

**Comment by waylan** [comment]
Which version of Jinja (the template engine) do you have installed? The command `pip freeze` should give you a list of everything installed.

**Comment by waylan** [comment]
> the content wrapped this way does not display on readthedocs.io (it's present locally using `mkdocs serve`, however).

Sorry I missed that part. When you use the readthedocs service, they override your theme and force their own. Additionally, unless they have updated their system since I checked last, they don't support version 0.16 of MkDocs. We made a lot of changes to the template context in version 0.16. If they are using an earlier version still (as I expect they are) then things will probably work differently for you.

Of course, because they force their own templates, any template modifications you make will be ignored. IIRC, there is a way to force them to use your templates, but I don't recall the exact set of config settings to get that to work. Perhaps setting the `theme_dir` setting or something. However, if you succeed with that, then you need to be developing against the version of MkDocs that they use (I'm assuming 0.15 but it could actually be older).

As an aside, I figured the above all out by reading through their [source code][1] myself (it has been a while so my memory is fuzzy on the details now). Unfortunately they don't actually document any of this. AFAICT, they don't really want anyone modifying the template. However, they will allow it if you really know what you are doing and get it just right. But you will be on your own. We can't offer support for their service as they are not using standard (current) MkDocs but a custom hybrid of their own.

[1]: https://github.com/rtfd/readthedocs.org

**Comment by waylan** [comment]
I just checked and in fact readthedocs [uses][1] MkDocs version 0.14.0 exclusively. If you are using that service, you need to develop against that version with its bugs and all. For a summary of changes between 0.14 and the current release, see the [release notes][2]. As there is no actionable item for us here, I'm closing this.

[1]: https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L9
[2]: http://www.mkdocs.org/about/release-notes/
