### ISSUE TITLE
Add custom_theme at mkdocs/themes as EXAMPLE

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1207]
to add `custom_theme` at https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes a **simple** exemple of custom theme (with eg.  new background and new footer) , modifing the default mkdocs theme. 

So, to test and **see "how to"**, user must copy the `custom_theme` to its project's as [overriding-template-blocks](http://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks) say. 

An example is so important to understand the user-guide, and to reduce support or alerts here at issues.

-----

PS: see also typical "bugs" (new user difficulties)  in overriding-template-blocks  at #1206.

**Comment by waylan** [comment]
This seems like a reasonable request. However, there will be some significant changes in 1.0 (see #1201) so we should probably wait till that lands.

**Comment by pawamoy** [comment]
Since 2017, the documentation has been improved a lot. To me the issue looks resolved, as the docs show how to kickstart a new theme using the mkdocs-basic-theme folder, or how to create a custom theme in the project directory, see https://www.mkdocs.org/dev-guide/themes/#creating-a-custom-theme. If the documentation lacks important elements, please let us know!
