### ISSUE TITLE
Using inline links pointing to a bulleted header in the same document

### ISSUE THREAD

**Issue by happicamper** [mkdocs/mkdocs#1225]
I want to have a link that will point to a header that has a numbered list in the same document. I know a format for mapping headers which is:  
```
[reference](#this-is-my-header)
```
but when I try to reference a bulleted header like this:
```
[reference](#4.-this-is-my-header)
```
It seems that it doesn't work.
Thanks for the future responses!

**Comment by waylan** [comment]
Just check what id is being assigned to the header and use that. You could use the browsers "developer tools" to "inspect" the element, or you could just use "view source" to look at the HTML. Both should be available via a right-click. I prefer using "inspect" because it opens directly to the element I right-clicked on, but you usually need to have "developer tools" enabled in your browser before its available. With "view source", you will be presented with the entire file of HTML and need to scroll down and find it yourself.

In any event, you are looking for this:

    <h1 id="this-is-my-header">This is My Header<h1>

In the above example you would use the "id" with a hash pretended to it:  `#this-is-my-header`.

**Comment by happicamper** [comment]
Awesome! I just replaced my code to `[reference](#4-this-is-my-header)`  and now can map the desired header.
