### ISSUE TITLE
Set image size

### ISSUE THREAD

**Issue by sesispla** [mkdocs/mkdocs#1226]
I am using pandoc to migrate some docx files to a static site using Markdown and MKDocs. However, the images are translated like this:

`![](images/media/image1.png){width="3.15in" height="4.668055555555555in"}`

We have two issues:
1. Width and Height attributes are not supported > Ok, I can remove it.
2. If I remove the width and height attributes, there are display issues if the image is larger than expected. 

I would like know if there is a way to add image width and height, in a similar way pandoc is doing right now.

**Comment by waylan** [comment]
Attribute lists (the format Pandoc uses for width and height) are non-standard Markdown and not available by default. You need to [enable][0] the [attr-list][1] Markdown Extension.

[0]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
[1]: https://pythonhosted.org/Markdown/extensions/attr_list.html

**Comment by sesispla** [comment]
Great, thank you @waylan !

**Comment by ashnur** [comment]
I can turn that extension on, but `width="123in"` is not valid html. how to create `style="width: 123in"` or `width="11808"` instead?

**Comment by martinbira** [comment]
I'm pretty sure you need to use px or em as a unit of measurement. Inches is not valid.

**Comment by ashnur** [comment]
> I'm pretty sure you need to use px or em as a unit of measurement. Inches is not valid.

isn't this just a repetition of what I said?
the inches are given already, because that's what I get with pandoc. thing is, it should be possible to change it to something valid, otherwise why would this option even exist?

**Comment by waylan** [comment]
The attribute list extension does not do any conversion. You need to provide a valid value. Whatever key and value you set gets used as-is. It is your responsibility as the document author to ensure the key/value pair is valid.

As you point out, inches are not valid for the `width` attribute, but they are valid for the `width` CSS property. So, then define your attribute list accordingly:

![](images/media/image1.png){ style="width: 123in" }

**Comment by ashnur** [comment]
Thanks, I just realized that this has nothing to do with mkdocs. Sadly, it seems that pandoc can not do this out of the box. Although right now I have attr_list enabled and the attributes are still not parsed, even though yesterday this still worked, and put the attrs into the html. Now it just ignores it and I have no idea why :(

**Comment by waylan** [comment]
The fact, is, most Markdown problems are related to bad input. Therefore, the correct way to address most Markdown problems is to correct the Markdown document. Whether that means the document author makes their own changes, or someone else comes along and makes edits later is inmaterial and generally ignored in Markdown related questions everywhere. 

To add to that, one of Markdown's "features" is that an error is never generated when parsing the source text. Any errors are communicated to the document author by outputting something that was unexpected, which sometimes includes invalid HTML. Yes, that means document authors need to know about HTML, but back when Markdown was first created, that was more common that it might be today. Note what the rules [state]:

> Markdown is not a replacement for HTML, or even close to it. Its syntax is very small, corresponding only to a very small subset of HTML tags. The idea is not to create a syntax that makes it easier to insert HTML tags. In my opinion, HTML tags are already easy to insert. The idea for Markdown is to make it easy to read, write, and edit prose. HTML is a *publishing* format; Markdown is a *writing* format. Thus, Markdown’s formatting syntax only addresses issues that can be conveyed in plain text.

By that measure, attribute lists don't belong in Markdown. Document authors should be using raw HTML directly in their documents to define things that are related to publishing such as image width. But some of us see the convenience and simplicity of attribute lists and s we've included them as a non-standard addon. But, as they are non-standard, with no clear authority on how they should behave, each implementation is slightly different.

While Pandoc is a great tool, it is dangerous to use it as a reference when setting expectations for other Markdown implementations. In fact, Pandoc is often the outlier where most other Markdown implementations agree. That's because Pandoc is not, strictly speaking,  a "Markdown Parser", but rather a document converter which happens to include Markdown as one of its supported formats. Because it needs to convert between any number of possible formats, all of which use very different ways of specifying various things (for example, a width could be specified in pixels, inches, or some other unit), Pandoc needs to convert things that any pure "Markdown Parser" would not need to be concerned with.

Python-Markdown (which MkDocs uses under the hood) is a pure "Markdown Parser" as it only converts from Markdown to HTML. Therefore, it, like the original rules, makes a lot of assumptions based upon the HTML output that Pandoc does not necessarily make. But those assumptions are common across most Markdown implementations including the original reference implementation. So, yeah, the answer is often, "you need to edit your Markdown source" when you get unexpected/invalid HTML output.

[state]: https://daringfireball.net/projects/markdown/syntax#html

**Comment by ashnur** [comment]
Thank you for the very elaborate and exhaustive explanation :). Sadly, even though I understand and agree with what you say, I still have the task to take a `.docx`, convert it into `.md` and run the results through mkdocs. Whatever I do I have to do it with scripts or configuration, because I can not change the content of the `.docx` or the `.md`. It's not in my control.  

further clarifications: 
- I don't parse markdown with pandoc, I generate it with it. I parse `.docx` with pandoc. 
- I don't know if I can set `.docx` unit to pixels from inches :) In fact, I know that pandoc is the one creating those width/height attributes from the `.docx`, and afaik, there is no configuration to change inches to pixels for it either.

**Comment by waylan** [comment]
> I don't parse markdown with pandoc, I generate it with it. I parse `.docx` with pandoc.

I feel your pain. Unfortunately, I know of no good solution for that except manually editing documents. I've had to do it myself before and its less than pleasant. Pandoc helps, but it only gets you so far. Unless you are also using Pandoc to parse the Markdown, manual editing of Pandoc's Markdown output is inevitable in that type of situation.

But this discussion has gone way off topic so let's end it here.
