### ISSUE TITLE
Add option to allow building to 'site_dir' instead of tempdir even when using livereload

### ISSUE THREAD

**Issue by ianmackinnon** [mkdocs/mkdocs#1227]
In our organisation we would like to be able to use livereload's folder watching and automatic rebuilding while using Apache to serve the generated files. As I understand from reading the code, a temporary directory is always created for the build when using livereload, and `site_dir` is ignored.

Would it be desirable to add an option to build to `site_dir` instead of the temporary directory even when using livereload? I would be happy to submit a pull request if so.

**Comment by waylan** [comment]
That sort of feature does not make sense to me. Livereload actually uses two servers: (1) a flat file server which serves the built files and (2) a web socket server which the [livereload][1] JavaScript lib uses to "reload" the browser page. As the dev server is not intended for use as a public server (it is not tested for or guaranteed to be thread safe), you would need to re-implement the web socket server. Also, the livereload flat file server injects the JavaScript lib into each page on each request (it is not included in the build files by MkDocs), so that would need to be re-implemented as well.

If you don't actually want the web socket part, then it would make more sense to write your own simple script which "watches" the `docs_dir` and runs `mkdocs build` on changes. After all, at its simplest, that is what our server does internally, but you get to avoid the extra overhead of the web socket. I would consider using either [githooks][3] or something like [watchdog][2] to trigger builds, depending on the specific needs and workflows of the project.

[1]: https://github.com/livereload/livereload-js#livereloadjs
[2]: http://pythonhosted.org/watchdog/
[3]: https://git-scm.com/docs/githooks
