### ISSUE TITLE
Connecting Github to the my Hosted mkdocs

### ISSUE THREAD

**Issue by Carbowix** [mkdocs/mkdocs#1264]
Hello Guys,

I was wondering if its possible to connect my github repo to the hosted mkdocs i have in my host. I wanted to make it connected so that people can commit their own work in the repo and it updates the hosted mkdocs with the things Commited. For example there is a new page created in the github with some information. How to make the hosted mkdocs sync this new page from the github and updates itself.

**Comment by waylan** [comment]
I suppose it could be possible, but you would need to write an automation script which responded to one of GitHub's [webhooks][1] to update the build on commit/push to the repo. And that script would need to be hosted somewhere publicly so that the webhook could reach it. Depending on your needs, that script may also need some sort of authentication to restrict access to authorized users. Such a solution is highly specialized and outside the scope of our ability to support directly. Of course, if you encounter problems when your script called MkDocs `build` or `deploy`, we can help with that. But everything leading up to that point in the script falls on the user to implement according to their specific needs.

[1]: https://developer.github.com/webhooks/
