### ISSUE TITLE
option to list content files distributed in the repo

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#1279]
It is commom to use many README's distributed in the repository, [like this](https://github.com/UnB-CIDACS/observatorio-jats):

* root README.md is a relevant content  and can't duplicate in a /docs

* the sub-project's README's as [in these folders](https://github.com/UnB-CIDACS/observatorio-jats/tree/master/campanhas)

* other `*.md` that are not README, but are content, as this other [`report-*.md`](https://github.com/UnB-CIDACS/observatorio-jats/blob/master/campanhas/c05-openCoherence-zika/report-01.md).

So, we need a simple *non-/docs* paths at `mkdocs.yml`... Will be a good issue for *mkdocs*.

**Comment by waylan** [comment]
I'm not clear what you are requesting here. Do you mean that you want to include Markdown files which are not within the `docs_dir` or to treat README files specially. The former has been discussed in #1134 and the later in #608. In either case, this would be a duplicate. I'll leave this open for now in the event I misunderstood you.

**Comment by ppKrauss** [comment]
Thanks @waylan , seems #608 , but I express all as a kind of  "parsing `mkdocs.yml` bug"... If it make sense there, we can close here.

**Comment by waylan** [comment]
As I explained in a comment on #608, that issue is about using `README.md` in place of `index.md`.  There is no changing location going on there.

However, if you want to include files not within the `docs_dir`, then you should create a symbolic link to that file from the `docs_dir`. In that case #608 is not necessary. At the location in the `docs_dir` where you want the file, create your symbolic link named `index.md` (or whatever you want) and point it to `../README.md`. There is no need to do anything special in the config file. Just include the symbolic link directly.

As these are two separate issues addressed elsewhere, I'm closing this as a duplicate.

**Comment by waylan** [comment]
> "parsing mkdocs.yml bug"

There is no parsing bug. It is completely intentional that no files are allowed to be listed in the `pages` setting that are not within the `docs_dir`. That will never change. If you want that behavior, you need to find another means to accomplish it. Right now, using a symbolic link seems the most likely. Perhaps a plugin could accomplish something similar. The plugin API is currently available in the 1.0.dev branch if you would like to experiment.

**Comment by ppKrauss** [comment]
Hi @waylan , the plugin must accept this kind of `mkdocs.yml`,

```yml
pages:
    - Home: ../README.md
    - Topic1: topic1.md
    - Topic2: ../repoTopic/README.md
```
it can?  Let's use it (!), how to plug this plugin?

**Comment by SloCompTech** [comment]
@waylan  solution is working, if you want to include `README.md` from root of your repo:
> As I explained in a comment on #608, that issue is about using `README.md` in place of `index.md`. There is no changing location going on there.
> 
> However, if you want to include files not within the `docs_dir`, then you should create a symbolic link to that file from the `docs_dir`. In that case #608 is not necessary. At the location in the `docs_dir` where you want the file, create your symbolic link named `index.md` (or whatever you want) and point it to `../README.md`. There is no need to do anything special in the config file. Just include the symbolic link directly.
> 
> As these are two separate issues addressed elsewhere, I'm closing this as a duplicate.

Just make sure you make **relative symbolic link** (See [why](https://www.mokacoding.com/blog/symliks-in-git/)).

And make sure to restart `mkdocs serve`.
