### ISSUE TITLE
mkdocs doesn't find any third-party plugin or theme

### ISSUE THREAD

**Issue by Maxiride** [mkdocs/mkdocs#1281]
I've installed mkdocs on my ubuntu machine with `apt install mkdocs` which insalled the 0.16.3 version. I've tried to add a new theme (squidfunk/mkdocs-material/issues/454) carefully following the steps indicated.

I've also tried to installa a third party plugin, also here I followed every step and dependencies request facelessuser/pymdown-extensions/issues/110 but when running mkdocs serve the module can't be found.

I am beginning to believe that there is something wrong with my MkDocs setup :\

**Comment by Maxiride** [comment]
I've found out **why**, my suspect was right! I've installed mkdocs via apt and then the plugins and theme via pip [check here](https://github.com/squidfunk/mkdocs-material/issues/454#issuecomment-328894193).

So I worked around the theme issue by cloning it in my documentation root and pointing mkdocs with theme_dir.

What about the plugin however?

**Comment by facelessuser** [comment]
I don't think this is really a mkdocs issue per se.  I'll never understand why things like `apt install mkdocs` is even offered.  The best choice in my experience is to always `pip install mkdocs`.  Is there a reason you chose to use `apt` instead of `pip`?

**Comment by Maxiride** [comment]
I used apt because I've never used python and didn't even had pip installed on my machine so I went in "autopilot" with apt which I'm more familiar with.

**Comment by waylan** [comment]
>  I'll never understand why things like `apt install mkdocs` is even offered. 

I understand the frustration. And for the record, the MkDocs project maintainers do not maintain the apt package. However, the open-source licence allows anyone to package a Python module up as an apt package, which is what has happened with MkDocs.

As for why people use non-Python specific package managers, there are various reasons cited. At least Debian puts their packages through extensive testing for an extended period of time before moving packages to the "release" stage. Some organizations policies require that only packages which have undergone this testing be installed on their systems. Any package which is not available on apt might as well not exist from their perspective. Of course, the down side is that they are multiple versions behind. Ubuntu (and friends) don't have those built-in delays, but many policies still require all packages to go through the system package manager.

AFAICT, the primary issue is that decent package management came too late in Python's growth. The various OS package managers have had decent solutions for Python long before Python had its own. And, well, old habits are hard to crack.  It turns out that Python's problem is political and/or social, not technical (now that decent Python specific solutions exist).

I've considered refusing to licence a personal project (not MkDocs) for distribution through other package managers, but in addition to enforcement being a pain, a significant number of potential users are immediately cut off. Instead, I've found the best approach to be to simply always document installation via pip and when users report bugs related to other methods if installation, suggest they use pip instead. Although, you do need to be careful; if you don't provide updates which address bugs in the apt package, the apt package maintainers will fork the package on their own and then you really have a mess.

**Comment by facelessuser** [comment]
@waylan Thanks for the explanation.  I guess one of these days I should at least look to understand the fundamental differences and implications of a Python module installed via apt vs pip.

Unfortunately I probably don't have the time and resources to actively spend ensuring my projects work with apt or packages installed via apt, but if people have fixes, I'll gladly accept them via pull requests.

**Comment by ventolinmono** [comment]
@Maxiride I couldn't point a bootswatch cloned theme on the configuration file.
https://github.com/mkdocs/mkdocs-bootswatch

I don't know if some files are missing from that repo in order to do that or something is wrong on my configuration file. What theme did you used?

**Comment by ventolinmono** [comment]
Maybe it was because iI installed Mkdocs with apt-get and it is a previous version. Uninstalled and then did it with pip and it works now.

**Comment by Maxiride** [comment]
@ventolinmono I'm sorry but as of now I don't recall which theme I was using.
