### ISSUE TITLE
Question: Casing Options?

### ISSUE THREAD

**Issue by joshrhoades** [mkdocs/mkdocs#1289]
This seems like a basic question or configuration, but I can't find it anywhere in the docs or other postings.

Is there a way to prevent pages/nav structure from using initial case?

Such as I create `something.md` and it renders in the nav as `Something`. I would like to be able to preserve the casing if possible.

I could do this in the yaml by setting an override title, but this would be egregious for the amount of documentation we're about to write.

I could also do this via CSS and force it to LC, but this is not ideal either as I would rather _preserve_ the case as it was originally entered.

Hopefully I've just missed something?

**Comment by trel** [comment]
Agreed.  I'd like the casing to be preserved by default.  But since there is already a standing precedent of upcasing, I'd be happy with an option to preserve.

**Comment by joshrhoades** [comment]
Actually, this seems a bit more convoluted. It appears as if single entities are converted to initialcase, as is anything with a dot-naming convention, whereas camelcase is not.

The URI, however, seems to maintain the original casing.

filename | Nav Output
------------ | -------------
`namespace.fn.method.md`|`Namespace.fn.method`
`hide.md`|`Hide`
`getActualSize.md`|`getActualSize`
`test this`|`Test this`

**Comment by trel** [comment]
Yes, our current workaround is to specify anything that isn't vanilla initial upcase.

Every other scenario behaved surprisingly.

**Comment by joshrhoades** [comment]
kebab-case and snake_case also get the Initial case treatment too:

File|Nav Output|URI
------------ | ------------- | -------------
`test-this`|`Test this`|`test-this`
`test_this`|`Test this`|`test_this`

A configurable option to preserve casing as entered would be ideal to my mind, without impacting already existing usages/behaviors.

**Comment by joshrhoades** [comment]
Weird, it isn't consistent either:
`namespace.fn.method.md` gets initial-cased, but another file with the same naming convention `namespace.fn.otherMethod.md` does not.

Or perhaps it _is_ consistent. The difference _seems_ to be that one is entirely lc, while the other is camelCase.

**Comment by waylan** [comment]
This is not a configurable option, but is [hard-coded][1]. And we are very resistant to adding new configuration options. In fact, we've removed more than we've added in the last few releases. 

The behavior is rather simple. If a filename is all lower case, then Python's [string.capitalize][2] method is run on it (capitalize first character of string). If the filename is not all lowercase, then no capitalization is done. The current behavior was put in place over 4 years ago (see ed59436), with a slightly simpler variation (which didn't check existing case) being added one day earlier (see c38db6198). Prior to that titles were not derived from filenames and there have been no other changes to title generation since (except for the code being moved without any changes in behavior in 984029ab52). I find it curious that this is the first we have had any complaints about it.

In any event, we are intending to rework the way titles are determined in the next major release (see #316). And if that doesn't meet your needs, the new Plugin API (see #1223) might be a way for users to define their own method for defining page titles. The work on these things can be found in the 1.0.dev branch.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/__init__.py#L423-L425
[2]: https://docs.python.org/2.7/library/string.html#string.capitalize

**Comment by joshrhoades** [comment]
@waylan Thanks for the info.

Don’t get me wrong, not trying to dog you guys for it, just found it curious as it seemed somewhat unexpected especially when I couldn’t find any info on it. I expected to find at least one random topic on it somewhere.

Though I agree it’s also strange if no one ever mentioned this before, we’re not doing anything crazy with our naming conventions (standard JS namespace dot notation), so I’d be shocked if I’m the first person who ran into it. Of course, running into it and then digging into it are two separate things, or perhaps people found other workarounds or just decided it wasn’t that crucial for their needs.

It’s not a dealbreaker for me (kinda sorta), liking what I can do so far with the tool otherwise, and I’m going to need to customize some things anyway so perhaps I’ll work around it.

Thanks for the info, guys.

**Comment by ganatrat** [comment]
I know this thread is too old - but I had to ask, are you guys planning any update on this?

**Comment by waylan** [comment]
@ganatrat the last activity was to give this the [needs design decision] tag. Until a decision is made, there are no plans.

**Comment by pawamoy** [comment]
This is one of the feature/change request where everybody wants something different, and it is almost impossible to satisfy everyone with the default behavior. The current default behavior is good in probably 90% of cases (maybe more, maybe less).

Instead of adding a configuration option with multiple predefined values and the according behaviors, maybe this option could accept a Python function (using YAML Python tags) that accepts input objects from MkDocs and returns a titlefor the navigation. This way users could implement their own behavior.

A current, possible solution would be to hook into [`on_nav`](https://www.mkdocs.org/dev-guide/plugins/#on_nav) to iterate on the navigation items and update them as you see fit. A very basic example:

```python
# hooks.py
from pathlib import Path

def on_nav(env, config, files):
    for file in files:
        if file.page:
            # Restore origin file name (without extension) as title.
            file.page.title = Path(file.src_uri).stem
```

```yaml
# mkdocs.yml
hooks:
- hooks.py
```

Since it seems to be achievable through hooks and plugins, I'll close this as out of scope for MkDocs core. If the plugin API can be improved though, please let us know!
