### ISSUE TITLE
Can't gh-deploy to master branch

### ISSUE THREAD

**Issue by jeffreymeng** [mkdocs/mkdocs#1291]
I'm trying to gh-deploy to the master branch of a github user page repository, but after I enter my password and press enter, nothing happens. I have to press `^c` to abort.
![2017-09-22_20-52-39](https://user-images.githubusercontent.com/15185258/30769923-0dd5e9e0-9fd8-11e7-95c2-c39975ce2874.png)

I'm also using the mkdocs [material theme](http://squidfunk.github.io/mkdocs-material/), if that's significant.

**Comment by epogrebnyak** [comment]
Are you able to git push anything outside mkdocs? Seems like general repo access problem. did you create the repo with git clone?

**Comment by jodumont** [comment]
Hi jeffrey;

I'm not an expert of github and mkdocs but I think you're issue is related to the fact you use
https instead of ssh

![image](https://user-images.githubusercontent.com/5204724/34646183-c9aac9f6-f361-11e7-92bc-b263177de7ca.png)


if you already have the file **.git/config** inside you mkdocs project you could simply open it and safely replace **https** by **ssh** which will give something like :

`url = git@github.com:jeffreymeng/brushjs-docs.git`

**Comment by waylan** [comment]
If you're trying to push to master, then are you using GitHub's user/organization pages? If so, the gh-deploy command won't work for you. See davisp/ghp-import#65 for details.

**Comment by jeffreymeng** [comment]
yes, I was using the organization pages.

**Comment by waylan** [comment]
I'm going to leave this open as we need to address this. At the very least we should document the problem.

**Comment by waylan** [comment]
By the way, this should start working once we fix #543. In that case, you would need to cd into the local working copy of the pages repo (master branch), and call `mkdocs gh-deploy --config ../path/to/mkdocs.yml`. Unfortunately, until then, you will need to use the ghp-import script directly for user/org pages.

**Comment by jeffreymeng** [comment]
ok thanks!
