### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by AndreWin** [mkdocs/mkdocs#1310]
Hello!

I use the latest mkdocs and Python 3.6 on my local server Ubuntu Server 17.04 (virtual machine in vmware).
When I start `mkdocs serve`, all works fine.
After some time `mkdocs serve` works too, but its process eats (7...12)% of CPU on virtual machine. On Windows 8.1 it will be approximatelly (12...25)% of CPU and my notebook begin hot. I need to stop `mkdocs serve` and start it again after a few minutes.

How can I fix it? Please help me.

Best regards, Andrey.

**Comment by waylan** [comment]
Interesting. I haven't seen any report of this before (or experienced it myself). I wonder if being on a VM is a factor, or if that just makes the issue more evident.

In any event, the `mkdocs serve` command is mostly a light wrapper around [lepture/python-livereload][1], which is a wrapper around tornado. It would seem most likely that any problems would be an upstream problem. To determine if the problem is specific to MkDocs or not, I would suggest running python-livereload directly and seeing of the problems persists. As you already have MkDoc installed, you also have python_livereload installed. Therefore, just run the following commands:

```sh
mkdocs build
cd site
livereload -p 8000 ../docs
```

If the problem persists, then the problem should be reported upstream. Either way, please report back here.

If you don't need the auto-reload functionality, you can also try the `--no-livereload` option of `mkdocs serve`:

```sh
mkdocs serve --no-liverelaod
```

That will run a simpler server which will use less system resources. You will need to stop the server, restart it, and manually click the "refresh' button in your browser to see any saved changes to your pages. If you are running on a resource constrained vm, that may be the only viable option.

[1]: https://github.com/lepture/python-livereload

**Comment by AndreWin** [comment]
@waylan, thanks a lot for your answer!
I tested livereload and got high CPU on host machine again.
I was cofused that it was only (1..2)% of CPU on Linux (guest machine).
I decided that it was Vmware issue. After searching I decided to change it's settings:
* I used all processors but only 1 cores for processors,
* I enabled "virtual Intel VT-x/EPT or AMD-V/RVI

I have no idea why but this solved my problems.
Thank you very much for your help!

Best regards,
Andrey.

**Comment by AndreWin** [comment]
Hello!

It seems to me, I definitelly found the source of high CPU in vmware. My folder project was linked (`ln -s`) with shared folder. Shared folders were made via settings for virtual machine in vmware. It turned out that there was high CPU on Linux because of some processess that have been working with shared folder. I decided don't use shared folder tool from vmware, and used [this instructions](https://www.howtogeek.com/176471/how-to-share-files-between-windows-and-linux/) unstead. Now when I save changed file on Windows I see high CPU from Chrome and Vmware. After site was livereloaded, CPU on Windows is small again. So it seems for me I really find solution for my problem.
