### ISSUE TITLE
Failing `mkdocs gh-deploy` appears to return 0 even with errors

### ISSUE THREAD

**Issue by brianhlin** [mkdocs/mkdocs#1334]
We push to our github-pages using `mkdocs gh-deploy` (https://github.com/opensciencegrid/operations) and it looks like even though there are errors and the deployment aborts, mkdocs returns 0. Travis-CI run here: https://travis-ci.org/opensciencegrid/operations/builds/295015594

Relevant error:

```
ERROR   -  Config value: 'theme'. Error: Invalid type "<type 'list'>". Expected a string or key/value pairs. 
...
Aborted with 1 Configuration Errors!
...
The command "if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token; git push gh-token gh-pages; fi;" exited with 0.

Done. Your build exited with 0.
```

**Comment by brianhlin** [comment]
Another, different error: https://travis-ci.org/opensciencegrid/operations/builds/295021003

**Comment by waylan** [comment]
Neither of those errors are in the deploy code. The first is raised in config validation and the second during the build. therefore, either of those errors would have presented themselves with a `mkdocs build`. Does the `mkdocs build` command also return `0` or is this unique to `gh-deploy`?

As an aside, I always run a local build before doing a deploy just to check for any unforseen errors. That said, we should be returning the proper code.

**Comment by brianhlin** [comment]
I tried `mkdocs build` locally with one of the broken commits and it failed with return code `1` as expected so this appears to be only affecting `gh-deploy`. I hear ya on checking with mkdocs build first. --w e do that on all PRs in our other repos but this one didn't seem to get that treatment.

**Comment by waylan** [comment]
Just tested this and I don't see any problem here:

```sh
$ master ± mkdocs build
ERROR   -  Config value: 'extra_css'. Error: Expected a list, got <type 'unicode'>

Aborted with 1 Configuration Errors!
$ echo $?
1
$ mkdocs gh-deploy
ERROR   -  Config value: 'extra_css'. Error: Expected a list, got <type 'unicode'>

Aborted with 1 Configuration Errors!
$ echo $?
1
```

**Comment by waylan** [comment]
So I looked at your `.travis.yml` file and I realized that your call to `gh-deploy` looks like this:

```sh
if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token; git push gh-token gh-pages; fi;
```

First of all, that line will exit with the exit code of the last command, which is not the `gh-deploy` command, but the `git push`.  Let's demonstrate that:

```sh
$ echo hello
hello
$ echo $?
0
$ unknowncommand
-bash: unknowncommand: command not found
$ echo $?
127
$ unknowncommand; echo hello;
-bash: unknowncommand: command not found
hello
$ echo $?
0
```

Note the last example there. While the first command erred, the second command still executed and and return code is the return code of the last command, which in this case did not error.

Just to be thorough, wrapping commands in an `if` make no difference (so that's not the problem):

```sh
$ if [ 1 = 1 ]; then unknowncommand; fi;
-bash: unknowncommand: command not found
$ echo $?
127
$ if [ 1 = 1 ]; then unknowncommand; echo hello; fi;
-bash: unknowncommand: command not found
hello
$ echo $?
0
```

If you want to string commands together and have all commands stop upon the first error, then use `&&`:

```sh
$ unknowncommand && echo hello
-bash: unknowncommand: command not found
$ echo $?
127
```

Note that in that case the second command never executed ("hello" was not echoed) and the exit code was the exit code of the command that erred.

Nevertheless, why are you pushing to the gh-pages branch? `gh-deploy` already does a push for you.

In any event, as this is an error in a wrapping script and/or travis config problem, I'm closing this. There is no MkDocs issue here.

**Comment by brianhlin** [comment]
Oh shoot, I realized the issue after your last comment. Sorry for wasting your time.

And thanks for the tip about `gh-deploy` and pushing!
