### ISSUE TITLE
Using YAML/MultiMarkdown metadata to control MkDocs flow?

### ISSUE THREAD

**Issue by twardoch** [mkdocs/mkdocs#1356]
Is it currently possible to somehow control the MkDocs flow via the YAML/MultiMarkdown metadata embedded in some source documents? 

Specifically, I would want to be able for some pages to provide "exceptions" to some settings that are provided in `mkdocs.yml`. For example, it would be useful if a theme accepts an `extra_css` or such config setting, and then I could use a different `extra_css` config setting on some specific pages (for example to use different accent colors on some chapters, or give different treatment to HTML formatting of the same elements, like H1, on specific pages. 

Also, of course, it might be useful to be able to pass the metadata values into the Jinja engine as values. 

My [md_mako extension](https://twardoch.github.io/markdown-steroids/md_mako/) does this during preprocessing — I use the Mako templating engine (which allows direct explicit embedding of Python code) as a Markdown preprocessor, so I can execute some programmatic elements in my source Markdown to build a "static" Markdown, which then gets passed into Python Markdown. And there, I have a way to define some `meta` global settings for my extension, and then use the YAML/MultiMarkdown metadata of the document to override those values locally. The contents of those is then accessible in the Mako engine so I can actually have some variables rendered right at the Markdown stage (which is often useful). 

I feel that the YAML/MultiMarkdown metadata concept is very useful and could be leveraged well for MkDocs. So — is something like this already possible, or planned?

**Comment by facelessuser** [comment]
Metadata is currently available, see documentation: http://www.mkdocs.org/user-guide/custom-themes/#pagemeta.

**Comment by waylan** [comment]
In addition to the metadata being available to the template (to be utilized by a theme), you may also be able to use a [plugin][1] to achieve some more advanced stuff. 

Finally, it's currently undocumented, but we have built-in support for defining the template to use for a page via the [template][2] meta key. It defaults to `main.html`. Just set it to a different template path/filename and, as long as a template exists in the theme env at that location, it will be used instead of the default.

[1]: http://www.mkdocs.org/user-guide/plugins/
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/build.py#L146

**Comment by waylan** [comment]
As the requested feature already exists, I'm closing this.
