### ISSUE TITLE
Incorrect markdown parsing

### ISSUE THREAD

**Issue by joshuaavalon** [mkdocs/mkdocs#1366]
## Description

```markdown
1. Text
2. Text
3. Text
4. Text

* Text
* Text
* Text
```

### Expected behavior

```markdown
1. Text
2. Text
3. Text
4. Text

• Text
• Text
• Text
```

### Actual behavior

```
1. Text
2. Text
3. Text
4. Text
5. Text
6. Text
7. Text
```

### Steps to reproduce the bug

1. Create a markdown.
2. `mkdocs serve`

### Package versions

* Python: 3.6.2
* MkDocs: 2.26

**Comment by waylan** [comment]
First of all, Markdown parsing is the responsibility of [Python-Markdown/markdown][0]. Any issues should be reported upstream. Second, this actually is the expected behavior, as [documented][1]. However, with the [Sane Lists extension][2] you can get the behavior you desire. In fact, MkDocs [makes it easy to use Markdown extensions][3].

[0]: https://github.com/Python-Markdown/markdown
[1]: https://python-markdown.github.io/#differences
[2]: https://python-markdown.github.io/extensions/sane_lists/
[3]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
