### ISSUE TITLE
Support build --dry-run

### ISSUE THREAD

**Issue by hellt** [mkdocs/mkdocs#1386]
In my CI chain I want to add a step that verifies that docs will be ready to properly build. I see that if someone misconfigures mkdocs.yml or misses some .md file referenced elsewhere a `filenotfound` error got emitted, for instance.

Question is how can I run mkdocs in a dry-run fashion so only checks will be done, but none of html pages built?

Is the `mkdocs build -s` the only option?

**Comment by waylan** [comment]
If you are concerned about polluting the `site_dir` with a partial build, then I would suggest using the `mkdocs serve` command. It builds to a temp dir which is destroyed when the server is stopped. Therefore, it never touches the `site_dir`.

That said, I can see the value of a "dry run" feature which would do everything except write files to the `site_dir`. However, at this time no such feature exists. I'll consider this a feature request, although it will probably be a post 1.0 feature.

**Comment by MikeyMJCO** [comment]
Any news/update on this? It would very useful in CI/CD/Test scenarios!

**Comment by chrimaho** [comment]
Why not just build, then delete?

Like this:

```sh
mkdocs build --site-dir="temp"
if [ -d "temp"]; then rm --recursive temp; fi
```

**Comment by homotechsual** [comment]
> Why not just build, then delete?
> 
> Like this:
> 
> ```shell
> mkdocs build --site-dir="temp"
> if [ -d "temp"]; then rm --recursive temp; fi
> ```

Because it's a significant waste of compute and storage resources, even temporary, when it's being run in a CI/CD scenario to test whether a build is viable hundreds or thousands of times in response to PRs/Commits

**Comment by pawamoy** [comment]
@squidfunk and I thought about this, and there are several cases where actually writing files is required for the build to succeed: some plugins like the [exclude-search plugin](https://github.com/chrieke/mkdocs-exclude-search) or the [offline plugin](https://squidfunk.github.io/mkdocs-material/plugins/offline/) rely on files being written to the `site_dir` in order to operate correctly.

So a pure dry-run mode is not possible I think.

However there are a few possible solutions that come to mind:

1. use an [`on_config`](https://www.mkdocs.org/dev-guide/plugins/#on_config) hook to change the destination directory so that MkDocs writes in a temporary directory
2. use something like pyfilesystem to manage a [memory filesystem](https://docs.pyfilesystem.org/en/latest/reference/memoryfs.html) and have MkDocs use it when reading and/or writing files
3. use other technologies like Docker volumes or whatever, who provide some kind of in-memory, temporary directories? not an expert here

If there are obvious improvements to be made to the plugin API so that plugins do not have to rely on files actually being written on disk, we're happy to hear about them!

In the meantime I'll close this as out of scope. Feel free to comment further of course :slightly_smiling_face: We can also re-open if someone wants to work on this!
