### ISSUE TITLE
suggest: use HTTPS on mkdocs.org

### ISSUE THREAD

**Issue by sinkcup** [mkdocs/mkdocs#1409]
mkdocs.org still uses HTTP at 2018...it's not safe.
suggest use free HTTPS, such as cloudflare HTTPS CDN in front of gh-pages

demo: https://github.com/openwrtio/openwrtio.github.io

**Comment by waylan** [comment]
While I understand the premise, mkdocs.org is a static site (MkDocs is a *static site generator* after all). The potential for harm is extremely low.

Regardless, the GitHub [docs][1] state:

> HTTPS is not supported for GitHub Pages using custom domains.

As it turns out, you can go to `https://mkdocs.com`, but you will get a browser warning as there is no certificate. If you tell the browser to ignore the warning, things work fine, but the warning is less that ideal (to say the least).

In any event, @d0ugal or @tomchristie would need to set that up if they are so inclined.

[1]: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by d0ugal** [comment]
I don't think I have access to this either. I assume the main requirement is control of the domain - @tomchristie has that access.

**Comment by sinkcup** [comment]
@waylan HTTP doesn't mean site owner attack visitors, but means site will be hijacked by router owner, they can insert js script such as ICO Cryptojacking / AD.

in China, almost every HTTP site has been insert AD. screenshot:

![image](https://user-images.githubusercontent.com/4971414/36575383-b43d68e6-1885-11e8-822c-d6a97e5ccec6.png)

Docs: man-in-the-middle attack (MITM)
https://en.wikipedia.org/wiki/Man-in-the-middle_attack

**Comment by waylan** [comment]
Yes, I understand there are vulnerabilities, but being a static site, there is no private info being sent/received and users are not "interacting" with the site. Yes, injected ads are undesirable, but my point is that the potential for harm is low relative to other types of sites.

Regardless, this is in @tomchristie's control alone.

**Comment by tomchristie** [comment]
Okay. It's not a massive priority for me, but I will put looking at putting cloudflare in front of mkdocs.org and django-rest-framework.org.

**Comment by d0ugal** [comment]
@tomchristie FWIW, I see you already have HTTPS for DRF. Maybe these is an approach we can copy? https://www.django-rest-framework.org/

**Comment by sinkcup** [comment]
@d0ugal it's very easy. log in https://www.cloudflare.com/ , add your domain, turn on Crypto->SSL, it's free.

@tomchristie it's better to turn on "Always use HTTPS", it will redirect http://www.mkdocs.org/ to https://www.mkdocs.org/

![image](https://user-images.githubusercontent.com/4971414/36624452-75407f00-194a-11e8-8ffe-7c4afb0f5591.png)
![image](https://user-images.githubusercontent.com/4971414/36624470-ad3edb18-194a-11e8-84fd-ea1a37cba75d.png)

**Comment by waylan** [comment]
For a good explanation of why this isn’t as big a deal as some make it out to be read http://scripting.com/2018/02/23/174914.html

**Comment by tomchristie** [comment]
@d0ugal I think that’s new. GH are trialling https support on GH pages, I’ve not confirmed but the rest framework site might already be getting that.

**Comment by sinkcup** [comment]
@tomchristie "HTTPS and HTTP coexist" is not a good idea. If user input "www.mkdocs.org", they will be still injected.
suggest: turn on "Always use HTTPS", it will redirect http://www.mkdocs.org/ to https://www.mkdocs.org/

**Comment by coliff** [comment]
Agree with everything thta @sinkcup has said. There are many benefits to being HTTPS only... Google now rank HTTPS sites slightly higher so it can help with SEO, and having that nice green padlock in the URL bar makes the site and the project look more trustworthy. I like this site: https://doesmysiteneedhttps.com/
I use Cloudflare on GitHub pages for free SSL - it's awesome - plus it really speeds up your site too!

**Comment by charlesreid1** [comment]
https://http://www.mkdocs.org is currently working without any certificate errors. http:// addresses do not redirect to https://. I guess that means this issue is resolved. Glad to see this is being addressed. Having SSL certs on a project site is a sign that at least one person involved with the project gives a hoot about privacy/security/adware protection. This issue _is_ important to a lot of users.

**Comment by sinkcup** [comment]
From May 01, 2018, Custom domains on GitHub Pages gain support for HTTPS, we can turn on "Enforce HTTPS" in project settings. @waylan 
Docs: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

![](https://blog.github.com/assets/img/2018-05-01-github-pages-custom-domains-enforce-https.png)

**Comment by waylan** [comment]
Sorry @sinkcup, but I don't have administrative rights so either @tomchristie or @d0ugal would need to enable that setting.

**Comment by tomchristie** [comment]
It's enabled now.

**Comment by tomchristie** [comment]
Thanks all!
