### ISSUE TITLE
dev_addr overwrites site_url

### ISSUE THREAD

**Issue by borekb** [mkdocs/mkdocs#1414]
From the docs:

> **site_url**
> Set the canonical URL of the site. This will add a link tag with the canonical URL to the generated HTML header.

and

> **dev_addr**
> Determines the address used when running `mkdocs serve`.

From these two pieces of info, it is not clear that the `dev_addr` will actually overwrite `site_url`, which seems to be happening for me. Would be nice if it was mentioned in the docs.

I'm happy to submit a pull request if you agree that the docs could be updated.

**Comment by waylan** [comment]
This is intentional. When using the local `serve`, the `site_url` is the address used by the server. When you `build`, then the `site_url` is used as configured. If it helps, the dev server is **not** intended to be used in production. You should be 'building' the docs and them serving them with a static file server. 

The dev server is only intended for testing locally before deploying your build docs to a production server. Therefore, any altered behavior does not effect the production build and only ensures the dev server works as expected. See 54a24ea8 where the current behavior was implemented.

**Comment by borekb** [comment]
I agree that it makes sense but it was not very intuitive to me. This issue is mostly a suggestion to update the docs, I'll try to put together a PR.

**Comment by borekb** [comment]
Hmm, now when I read the docs really carefully, it mentions that "This will add a link tag with the canonical URL to the **generated HTML header**." This probably means really just the generated header, not the dynamic preview version by `mkdocs serve`. So it's probably there, I just didn't realize that.
