### ISSUE TITLE
compatibility with 'Markdown Preview Enhanced'

### ISSUE THREAD

**Issue by devmiyax** [mkdocs/mkdocs#1417]
I think it would be better to support compatibility with 'Markdown Preview Enhanced'.
For example

mkdocs 
input:
<pre>
```plantuml
```
</pre>

output:
```
 <pre><code="pluntuml">
 </pre>
```

But 'Markdown Preview Enhanced' outputs rendered plantuml image.

On mkdocs to use plantuml, we need to install the extension and write like this.

<pre>
```plantuml format="png" classes="uml myDiagram" alt="My super diagram placeholder" title="My super diagram
</pre>

**Comment by waylan** [comment]
The [Markdown rules][0] provide for very limited functionality. Everything outside of those basic rules are non-standard and inconsistent across implementations. You have your preferences and I have mine. You don't like my preferences and I don't like yours. And that is only two of many opinions. In the end it is impossible to support every possible Markdown variant. Therefore, we include support for Markdown extensions. Each user can install a set of extensions which gives them a Markdown variant that they prefer and no one is forced to use a variant they don't like. And if an extension doesn't exist that fits your needs and/or wants, you are free to [create your own][3].

That's why we only include a few limited extensions by default. It's also why we have no intentions of adding to that list. If anything, I would be inclined to remove the "default" extensions and require users who want them to explicitly list them in their config. But that would "break" a lot of existing user's sites so we'll leave them for backward comparability reasons. However, I do not see any reason to add to the list of default extensions.

Whether an extension is included by default or not, if you would like to address the functionality of a specific extension, that would be a downstream issue that should be addressed with the developers of that extension. Even the [Markdown library][1] itself is a separate project and any issues with it should be addressed downstream.

[0]: https://daringfireball.net/projects/markdown/syntax
[1]: https://github.com/Python-Markdown/markdown
[3]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
