### ISSUE TITLE
PlauntUml is not render when it does not have arguments

### ISSUE THREAD

**Issue by devmiyax** [mkdocs/mkdocs#1421]
## Input

<pre>
```plantuml
Bob->Alice : hello
```</pre>

<pre>
markdown_extensions:
    - plantuml:
</pre>

## Expected Output
![image](https://user-images.githubusercontent.com/1174152/36875470-75926a2e-1df3-11e8-979b-178b97afd1d6.png)

## Current Output

```
<pre><plantuml>
Bob->Alice : hello
</pre>
```

---
It seems that Internal 'Fenced code blocks' has higher priority than the markdown_extensions define.
As evidence when a palntuml part has arguments rendered correctly as below.

<pre>
```plantuml format="png" classes="uml myDiagram" alt="My super diagram placeholder" title="My super diagram" 
Bob->Alice : hello
```
</pre>

Do you think markdown_extensions should have higher priority than internal functions?

**Comment by waylan** [comment]
This appears to be an issue in the plantuml extension to Python-Markdown. As the issue appears to be unrelated to any MkDocs code, please report this matter upstream with the developer of that extension.

**Comment by facelessuser** [comment]
In general, I'm curious why `tables` and `fenced_code` are forced as defaults.  As someone that uses a different solution than `fenced_code`, I'm curious why MkDocs forces `fenced_code`. `toc` I understand, but I can't see reason why `tables` and `fenced_code` are forced as builtin.  I could understand as default which a user can override.

I guess me using `superfences` must have just been inserted before `fenced_code`, so I didn't even realize this was being forced.

If `tables` and `fenced_code` were defaults, a user could override the defaults when defining their own extensions and could control the order or use something else entirely.

**Comment by waylan** [comment]
Oh, is the problem that another extension is conflicting with the fenced code blocks extension? Then my knee-jerk reaction is that the extension author should have chosen a different syntax, or developed the extension so that it can work with the existing extension. That said, I have no idea what plantuml is (at least I have no recollection of it), so maybe that's a naive reaction.

Regardless, I'm not crazy about the "default" extensions either (of course except for `toc` which MkDocs heavily relies on). The problem is that they have been there from the beginning (way before I got involved) and many users have documents which include syntax that relies on them. If we removed them as defaults, we would break a tremendous number of user's documents and require many many users to modify their config files to list extensions for the first time. As a reminder, being able to define extensions in the config is a relatively new addition. For most of MKDocs' life, that wasn't even an option. 

Another factor is that GitHub Flavored Markdown (and others) include tables and fenced code blocks by default and more and more users are expecting those features to be included in the base set of features. If you follow the [markdown] tag on Stackoverflow you'll see people constantly confused by that. It has never occurred to them that a Markdown implementation might not support those features by default (or at all) and they don't even check documentation to see if there is a way to enable them. I think that from that perspective (which is not necessarily my personal viewpoint), it makes sense to have them included in the default. That also reinforces the thought that any third party extension which builds on the syntax needs to work even when the basic extensions are enabled. 

Despite all of that, it would be interesting to see a proposal for an elegant way to "exclude" default extensions in MkDocs. I didn't like any of the ideas that I had, but I would be interested in the right kind of solution, whatever that might be.

**Comment by facelessuser** [comment]
I haven't specifically looked at where the plantuml extensions injects itself in relation to other extensions, it might be possible that it is an ordering issue (where if first in the list it naturally precedes `fenced_code`).  Regardless, they seem to offer an alternative syntax as well.

I was more interested in this issue because I didn't realize `fenced_code` was always being included.  SuperFences just happens to inject itself in such a way that when it follows `fenced_code` it gets injected before `fenced_code`, so I was getting lucky.

I'm definitely interested in a way to "exclude" defaults.  I'd even be willing to create a pull, but I would kind of want to get an idea of what would be viewed acceptable before attempting.

**Comment by facelessuser** [comment]
FYI, `plantuml` is implemented as block processor, so its fenced syntax will never play nice with `fenced_code` which is a preprocessor extension, so this is definitely an upstream issue, though if I were the user, I'd just use the alternative syntax which would side step this issue.

**Comment by facelessuser** [comment]
I guess it is easy enough to write a simple extension that when included first would remove default mkdocs default extensions (excluding `toc`).

Mkdocs could include such an extension that resets defaults (removes default extensions) if included first:

```
markdown_extensions:
    - mkdocs.reset_defaults
    - myotherextension.etc
```

This isn't really a huge deal for me. For those who prefer nested fences, `superfences` seems to play nice with `fenced_code` (as long as `fencd_code` is included first).  And I always use `tables`.

**Comment by waylan** [comment]
> I'm definitely interested in a way to "exclude" defaults. I'd even be willing to create a pull, but I would kind of want to get an idea of what would be viewed acceptable before attempting.

I'm open to suggestions.
