### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mikemadeja** [mkdocs/mkdocs#1468]
Hi, I stood up a new MKDOCs site and it looks great. The problem is search doesn't work.. I've looked at other issues here and it doesn't seem related but I am not sure?

I've tried a bunch of themes and the same result. 

The query appears like this: https://python-iaa.azurewebsites.net/mkdocs/site/search.html?q=SCRIPT

I'm utilizing Azure App Service as Windows.

mkdocs - version 0.17.3
python - version 3.5.4

**Comment by waylan** [comment]
Does search work with the dev server? Try running `mkdocs serve` locally and testing search there. If that works, then the problem is likely related to your server config, which will require more information for us to help you.

As an aside, search has been completely rewritten and the new search will be available in the next release (1.0.0). It's not likely that any potential bug found here still exists in the current codebase.

**Comment by mikemadeja** [comment]
So I tried locally and I can search. I tried with python 2.7.

When I setup python 2.7 in Azure App Services I can't search... weird :-/.

What kind of details would you need? I am running Azure App Services with Python extensions. I can definitely compile my markdown files and the site builds. But when I search it doesn't work.

**Comment by waylan** [comment]
My best guess is that the server is incorrectly reporting the content type for a certain file type or two and that should raise some errors in the browser. Does your browser's debug tools report any errors?

**Comment by mikemadeja** [comment]
This resolved it. I created a web.config file with this below and now search works.

`<?xml version="1.0" encoding="UTF-8"?>
  <configuration>
    <system.webServer>
      <staticContent>
        <mimeMap fileExtension=".json" mimeType="application/json" />
        <mimeMap fileExtension=".mustache" mimeType="text/template" />
      </staticContent>
    </system.webServer>
  </configuration>`
