### ISSUE TITLE
Live reload keeps looping through custom plugin when altering pages

### ISSUE THREAD

**Issue by Nebulosar** [mkdocs/mkdocs#1479]
I followed the steps in https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/plugins.md for developing my plugin. Right now it looks like this:

```Python
class MyPlugin(BasePlugin):
    """
    The entry point of the plugin.
    Extends mkdocs.plugins.BasePlugin
    """
    def on_config(self, config):
        """
        When MkDocs yaml configuration file is valid, will execute
        """
        config['pages'].append({'Homepage': 'index.md'})
        with open(config['docs_dir']+'/index.md', 'w') as index_file:
             index_file.write('# Hello')

        return config

```
When running live server, it will check for changes.
When changing the `index.md` file it will restart and go through the `on_config` again.  
Below the console output where you can see it loops due to the waiting file:

```

    INFO    -  Building documentation...
    [I 180427 11:00:34 handlers:93] Reload 1 waiters: docs/mkdocs.yml
    [I 180427 11:00:35 handlers:133] Browser Connected: http://localhost:8001/index.html
    INFO    -  Building documentation...
    [I 180427 11:00:35 handlers:80] Ignore: docs/source/index.md
    INFO    -  Building documentation...
    [I 180427 11:00:36 handlers:80] Ignore: docs/source/index.md
    INFO    -  Building documentation...
    [I 180427 11:00:37 handlers:80] Ignore: docs/source/index.md
    INFO    -  Building documentation...
    [I 180427 11:00:38 handlers:93] Reload 1 waiters: docs/source/index.md
    [I 180427 11:00:38 handlers:133] Browser Connected: http://localhost:8001/index.html
    INFO    -  Building documentation...
    [I 180427 11:00:44 handlers:93] Reload 1 waiters: docs/mkdocs.yml
    [I 180427 11:00:44 handlers:133] Browser Connected: http://localhost:8001/index.html
    INFO    -  Building documentation...
    [I 180427 11:00:45 handlers:80] Ignore: docs/source/index.md
    INFO    -  Building documentation...

```

It would be nice to be able to have some kind of variable in the `config` that tells me whether the command `serve` is executed or that it's a reload.  
Another option is to add a function that can determine if it's a reload or an initial fire of the `serve` method.

Maybe there already is a way do determine this and I don't know about it. Then it should be documented if not. Cause page altering during on_config is not very unlikely to happen with a plugin I think.

**Comment by Nebulosar** [comment]
I already found a hacky way of doing this, but there must be a better way than putting this before my actual code:
```Python
if not config['site_dir'].startswith('/var/folders/') and 'tmp' not in config['site_dir']:
    #  Is initial fire because it's not in temp dir so alter page here
```
I don't even know if MkDocs uses `var/folders` always,, or only on mac.. And if `tmp` is always present so i guess this is not a smart solution..

**Comment by waylan** [comment]
Yes, your hack would only work on a Mac as you are using the Mac specific location of temp files. We ran into a similar problem with the search plugin which was addressed in #1388. However, that was a little simpler to do as we were simply adding an item to the `extra_javascript` config setting.  All we needed to do was check if the value already existed in the setting and only add it if it didn't.

Moving on to your problem... you are creating an infinite loop. The server will reload every time a file is changed in the `docs_dir`. And every time it reloads, your plugin writes to a file in the `docs_dir`. However, I see that you are adding the page to the `pages` config setting. So why not check if the page is already listed? Alternatively, you could check if the file already exists and only write the file if it does not.

MkDocs wasn't designed to have the contents of the docs_dir changed mid-build, so perhaps a better solution would be to leave the file in the `docs_dir` as-is (an empty dumby file would work fine) and use the `on_page_read_source` event to return your custom content rather than reading the content of the actual file. That way you never need to write anything to the file and avoid the infinite loop altogether.

Also, there is the `in_serve` event which only ever gets called when the local dev server is used. You could use that event to assign an attribute to your Plugin class as a way of identifying when MkDocs is running under the dev server.

I suppose as a last resort, you could run the server with the `--no-livereload` option and avoid the problem altogether.

**Comment by Nebulosar** [comment]
> MkDocs wasn't designed to have the contents of the docs_dir changed mid-build.  

I think you are right about this, but in this case the pages are always being build `pre-build`. 
However, I think simply checking the config pages won't satisfy, because these get reassigned every time the `on_config` is called.  

I think the best solution here is to define the logic into two methods, both the `on_config` and the `on_pre_build`. This way, adding the pages and building the pages are separated. It may take something more that that, but I will figure this out along the way.  

I still think it would be a awesome addition if in the `on_config`, you can determine whether it's a build or serve call. The way you described using the `on_serve` method won't do, because it always gets called after the `on_config` call.

**Comment by waylan** [comment]
> The way you described using the `on_serve` method won't do, because it always gets called after the `on_config call.

So it does. However, you could alter the "watcher" to ignore the files you want to modify from the `on_serve` event.

Also when using the server, the `site_url` is overridden to point to the `site_url`. Specifically, the domain of the `site_url` should equal the `dev_addr`. So something like this may work for you:

```python
if config['site_url'] == 'http://{0}/'.format(config['dev_addr']):
    # Local server is running
```

**Comment by waylan** [comment]
This will be easier to accomplish in 1.0. The work in #1504 includes adding a `files` plugin event. That event would allow you to include files which are not in the docs_dir. Therefore, your plugin would never need to copy files to the docs_dir. The plugin would simply add the files to the `files` collection. Then the files would be copied from their original location directly to the site_dir as part of the build.

That being the case, we will not be making the changes requested here.
