### ISSUE TITLE
Using custom theme without name doesn't load mkdocs_theme.yml

### ISSUE THREAD

**Issue by kolbma** [mkdocs/mkdocs#1514]
Is there a reason why there is the check for self.name at
https://github.com/mkdocs/mkdocs/blob/94bc83ba21d17462438fbb6fd8a145126199a823/mkdocs/theme.py#L46 ?

In your documentation you tell people to use name = null with custom_dir to use only the custom theme.
And I'm wondering why the hell it doesn't find the variables specified in mkdocs_theme.yml in this directory.

Now I know. But this check doesn't make any sense for me.

**Comment by waylan** [comment]
This was an intentional design decision. Perhaps the documentation could be improved to make this more clear, but the `mkdocs_theme.yml` file is only used for "packaged themes".  The `custom_dir` only uses the  `theme` config option of `mkdocs.yml`. The idea is that "custom_dir" would only contain a one-off theme which is unique to a specific project. Therefore the config for it can be defined directly in the project's config.

If you are using `custom_dir` for a theme which is being used in multiple projects, then that was not an intended use case. You are welcome to do it, but you will need to manually replicate the config in each project.
