### ISSUE TITLE
Docs wont deploy on gh pages

### ISSUE THREAD

**Issue by PotatoeTrainYT** [mkdocs/mkdocs#1525]
I followed all the instructions etc on mkdocs.org on how to deploy the docs with gh pages, i do `mkdocs gh-deploy` and it says:
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\sebfa\docs\docs\site
INFO    -  Copying 'C:\Users\sebfa\docs\docs\site' to 'gh-pages' branch and pushing to GitHub.
INFO    -  Your documentation should shortly be available at: https://PotatoeTrainYT.github.io/potatoetrainyt.github.io/
```
and it isnt showing up on my gh page, only my readme from master branch shows

**Comment by waylan** [comment]
Are you using User/Organization Pages (rather than project pages)? If so, the `gh-deploy` script does not work in the current release as User/org pages do not commit to the `gh-pages` branch, but the `master` branch of a separate repo from the project. You will need to use the `build` command, and then use [ghp-import][1] directly to deploy the built site. This has been fixed in #1376 and will be available in the next release. In the meantime, use this workflow:

```sh
cd project-repo
mkdocs build
cd ../pages-repo
ghp-import -b master -p ../project-repo/site 
```

If you are not using user/org pages, then I'll need more info to help. Perhaps point me at you repo.

[1]: https://github.com/davisp/ghp-import

**Comment by waylan** [comment]
As there appears to be no actionable item here, I'm closing this.

**Comment by lrdegeest** [comment]
Was this ever fixed? Because I just downloaded mkdocs today for the first time, followed the deployment instructions in the manual, and got *exactly* the same outcome as @TwistedAsylumMC. Only the readme.md shows up on the project page. I am not using an individual/organization page. I also tried other suggestions (https://github.com/mkdocs/mkdocs/issues/973) to no avail.

**Comment by MaxandreJ** [comment]
What it is is just that it takes between five to ten minutes for the github page to work after running `mkdocs gh-deploy`  (at least for the first time), but the command does work.
