### ISSUE TITLE
Link validation should be better or more clearly advertised as incomplete

### ISSUE THREAD

**Issue by ubershmekel** [mkdocs/mkdocs#1570]
I noticed a few broken links in my project did not generate warnings and started wondering.

After reading that MkDocs relies on http://wummel.github.io/linkchecker/ to validate links (see https://github.com/mkdocs/mkdocs/issues/1084 comments) I would like to ask the question - does MkDocs aspire to validate links well or would rather rely on a separate tool for a complete verification? Currently, a user can easily believe that they're getting good validation when they aren't. I built a reproduction of the problem here https://github.com/ubershmekel/mkdocs-warnings and you can get the gist of it in this example:

```
## Testing links warnings during build

[1 working link](works.md)

[2 working link](/works.md)

[3 working link, but it probably should not](/works/)

[4 working link, but it probably should not](/works)

[5 not working link, yes warning because ends with .md](/worksasdf.md)

[6 not working link, no warning](/worksasdf)

[7 not working link, no warning](/worksasdfasdf.qqq)

[8 not working link, no warning](worksasdfasdf)
```

**Comment by waylan** [comment]
Which version of MkDocs are you using? This part of the code was completely refactored recently. The new code is in version 1.0 which is currently available as a release candidate (1.0rc1). Note that link validation only concerns itself with links to other MKDocs files. It does not care about external links.

However, what is an internal link and what is an external link can vary from project to project. For example, some users host the root of their MkDocs site in a subdirectory of their domain. And other files are hosted in the parent directory and/or other subdirectories which are not part of the MkDocs site. Yet, it is still completely appropriate that their URLs to those external pages be relative. In fact, some users insist on being able to use relative URLs to external pages on the same domain. Therefore, it becomes very difficult to determine which links we should verify and which we should not, let alone which we should issue warnings on.

**Comment by charlesreid1** [comment]
You can try adding `strict: true` to your `mkdocs.yml`

**Comment by waylan** [comment]
> After reading that MkDocs relies on http://wummel.github.io/linkchecker/ to validate links

I missed that the first time. No, we **do not** use LinkChecker to validate links when building a site. We do however, use LinkChecker in our test framework to validate all links in our own documentation.

The only link validation that we do when building a site is to validate internal links. Note that internal links must use the form `page.md` (relative and point to the source md file). Anything else is assumed to be an external link and not validated (including `/page.md` as it is absolute; see #1592). Note that we validate internal links for the sole reason of converting them (ex: `page.md => page/`). If it it not a link we need to convert, we just pass it through without any validation.

The problem here is that what the user considers to be an internal/external links may be different than what MkDocs considers to be internal/external links. Then the user is surprised that links which they considered internal were not properly handled by MkDocs. However, we do [document clearly][1] what is a proper internal link. If users don't follow those instructions, how do we know that they may be intentionally linking to something other than an internal link?

On the other hand, we do not document anywhere that we validate links. Therefore, any expectation that links are validated is misplaced. We don't need to document that validation is incomplete, because we don't even suggest that we validate links at all.

Finally, I will point out #1564. In an early beta of version 1.0 we noted all links which did not point to known internal documents. The thinking was that by getting a list of such links, the user could review it to confirm that all the links were actually external. Of course, the problem is that users then think that there is a problem with their correct external links. So the messages were downgraded to `debug` level. Run the `build` command with the `--verbose` flag to see a list of all external links. You can then confirm whether any links you indented to be internal are included and, if, so, edit them to be proper internal links.

[1]: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/writing-your-docs.md#internal-links

**Comment by ubershmekel** [comment]
I guess what through me off was https://mkdocs.readthedocs.io/en/0.13.3/user-guide/configuration/#strict

>strict
> Determines if a broken link to a page within the documentation is considered a warning or an error (link to a page not listed in the pages setting). Set to true to halt processing when a broken link is found, false prints a warning.

The definition of `broken link to a page within the documentation` is a bit broader than what it actually means. Would the following be an improvement in your opinion?

> Determines if a broken relative link to an `.md` file within the documentation is considered a warning or an error (link to a page not listed in the pages setting). Set to true to halt processing when such a broken link is found, false prints a warning.

**Comment by waylan** [comment]
Ah, now I understand your confusion. Yes, that documentation was removed because it was not correct. Actually it had multiple errors in it. In fact, it was removed for a different reason than the one brought up here.
