### ISSUE TITLE
Search hangs forever when ENTER is pressed

### ISSUE THREAD

**Issue by alexandrezia** [mkdocs/mkdocs#1584]
Using mkdocs, version 1.0
theme: readthedocs

Search works when typing search term, but when pressing ENTER it loads "Search results" page (/search.html?q=test) and then hangs forever showing "Searching ..."

**Comment by waylan** [comment]
I can confirm [here][1]. Interestingly, if you type into the search form in the `search.html` page it works fine. The problem seems to be with the search term being in the query string. In fact an error is raised (`worker.js:102 Assets for search still loading`). The message with the search term is not supposed to be sent to the worker until everything is loaded. Apparently we have a bug there when getting the search term from a query string.
