### ISSUE TITLE
Internal link to non-page/non-media artifact

### ISSUE THREAD

**Issue by marcelstoer** [mkdocs/mkdocs#1619]
I'm still working through the 0.17 -> 1.0 migration issues. I made a habit of always using strict mode but this now prevents having relative internal links to non-page/non-media artifacts.

Repo type: GitHub

Question / request: how do I tell MkDocs to not validate relative paths that point outside the `docs` directory?

**Directory layout**
```
|-- CONTRIBUTING.md
|-- LICENSE
|-- Makefile
|-- README.md
|-- app
|   |-- Makefile
|   |-- driver
|   |   |-- Makefile
|   |   |-- algo.c
...
|-- docs
|   |-- css
|   |   `-- extra.css
|   |-- en
|   |   |-- build.md
...
```

**Linking from documentation to code**

Let's say I want to link from `build.md` to `algo.c`. I would write `yadayady [algo.c](../../app/driver/algo.c)` in the Markdown file.

On a purely file level this will work. Meaning, if you open `build.md` on GitHub the relative link to the code works. 

Before MkDocs 1.0 it didn't complain about invalid link and we have JavaScript in place to fix the link at page load-time (replacing relative path with absolute path to GitHub incl. correct branch). This is a hack I know but we didn't see any other way.

MkDocs 1.+ now complains about "a link to ... which is not found in the documentation files." which prevents running e.g. `mkdocs serve` successfully.

**Options**

I _could_ make all those relative links (we have close to 100 of them) static pointing to `https://github.com/user/repo/etc.`. However, we would loose the ability to point to the file in the correct branch i.e. the same branch the doc file sits on.

**Comment by waylan** [comment]
The difference between 0.17 and 1.0 is that in 0.17, MkDocs only knew about pages and therefore, could only validate links to pages. In 1.0 is knows about all files and therefore validates all internal links. We always intended to validate all internal links, but couldn't because we didn't have the necessary data. In other words, your hack worked due to an incomplete feature (in a pre 1.0 product). Now that the feature is complete, I don't see any way around it except to use absolute links.

This is how I see the various pieces of this feature in **order of importance**:

1. Validate all internal links
2. Support external links
3. Support relative internal links when browsing on GitHub.

You could theoretically avoid validating the links if you could convince MkDocs that they are not internal links. But how would you do that? Markdown doesn't offer a way to differentiate so we are left with absolute verses relative as the only differentiater. Ironically, you want to validate internal links, but you don't want to validate external links which are indistinguishable from internal links.

**Comment by marcelstoer** [comment]
You're right, a good summary.

> Ironically, you want to validate internal links, but you don't want to validate external links which are indistinguishable from internal links.

The question is: _internal_ to what? Shouldn't MkDocs only be concerned with "artifacts" in the docs directory (pages or not)? I see this as the MkDocs world of the project universe. Couldn't you just ignore relative links the leave your world? 

Ok, then question is if the link is _supposed_ to point outside your world or whether the author made an error in the relative path. Tricky.

**Comment by waylan** [comment]
> Ok, then question is if the link is supposed to point outside your world or whether the author made an error in the relative path. Tricky.

Yes, that is the problem. As we can't tell the difference, we always assume an error was made by the author.  We can't have it both ways.

Therefore, you have two options:

1. Disable strict mode and ignore the warnings.
2. Keep strict mode and use absolute URLs for all external resources

**Comment by waylan** [comment]
To help in understanding how MkDocs defines internal/external resources, all "internal resources" are files which are included in the `site_dir`. If a resource is not included in the `site_dir`, then it is an "external resource" and must use an absolute URL.

Note that the above does not require that an "internal resource" be included in the `docs_dir`. In fact, there are at least two ways to get MkDocs to consider an external file to be an internal resource:

1. Use symbolic links within the `docs_dir` which point to files outside the `docs_dir`. 

2. Use a plugin which adds items to the `files` collection. There is no requirement that the source path of all files must be within the `docs_dir`. In fact , this was the very use case for adding the [on_files][1] event. 

Note that in both cases, while the actual source files are outside of the `docs_dir`, they will still be copied/included in the built site (`site_dir`). Therefore, links to those files could be relative URLs pointing to known internal files. 

[1]: https://www.mkdocs.org/user-guide/plugins/#on_files
