### ISSUE TITLE
livereload.js fetching issue when using domain name.

### ISSUE THREAD

**Issue by legatoo** [mkdocs/mkdocs#1652]
I start my doc using `mkdocs serve --no-livereload --dev-addr="a.b.c.d:8416"`.  Accessing doc using http://a.b.c.d:8416 works, but when I using domain name http://my-domain to access the site, something strange happened on fetching livereload.js. The framework seems to add an extra port: http://my-domain:8416/livereload.js, which hangs opening the site.

Mkdoc version: 0.17.3

**Comment by waylan** [comment]
> Mkdoc version: 0.17.3

Since releasing 1.0 we no longer support older versions.

That said, your report doesn't line up. You indicate you are using `--no-livereload` yet you say there is a problem fetching ` livereload.js`. Why would you be attempting to fetch ` livereload.js`? With `--no-livereload`, the ` livereload.js` is not available to fetch and the code which causes it to be fetched is not injected into the pages.

> The framework seems to add an extra port: `http://my-domain:8416/livereload.js,` which hangs opening the site.

I'm assuming you are not using `--no-livereload` here. This is the behavior of the livereload server. Two servers are started, a simple flat file http server and a websocket server. The `livereload.js` script connects to the websocket server and listens for messages instructing it to reload the page. The second server with the extra port that you are seeing is likely the websocket server.

IIRC, when you don't use the default address/port, the livereload server does something slightly differently than when using the defaults. However, that is all contained in [lepture/python-livereload][1], which we only provide a light wrappper for. You may need to report your issue upstream.

[1]: https://github.com/lepture/python-livereload

**Comment by waylan** [comment]
On more thing:

I'm not sure why you feel the need to use a domain name rather than a local IP address. As a reminder, the server is intended only for development purposes. If you are attempting to use a domain name with the goal of using it to serve the documents outside of the local machine, this is not supported. You should be using a separate third party server which is built for this purpose.

That being the case, I'm not all that concerned that domain names don't work. In fact, I consider it a good thing as it discourages users from trying to use the server in ways we don't support. That said, this is all handled upstream and out of our control anyway.

**Comment by legatoo** [comment]
I was not clear about what liverelead does, now I set --no-livereload in prod deployment, everything is fine. Thank you.
