### ISSUE TITLE
How can I use Markdown to configure the Nav

### ISSUE THREAD

**Issue by wizardforcel** [mkdocs/mkdocs#1688]
It's so wired that an item cannot be both an article and a group. Markdown is closer to HTML and more handy. I think Markdown is a better way to configure the Nav.

**Comment by waylan** [comment]
Do you mean "Navigation"? TOC is a list of section headers within a single Markdown page.

**Comment by wizardforcel** [comment]
@waylan Yes..

**Comment by waylan** [comment]
The decision to use YAML to define the navigation has been in place from the beginning and is integral to the underlying design of MkDocs. It has been that way since before I got involved, so I can only speculate on why that choice was made.

In any event, there are no current plans to alter the existing implementation. However, there is a `nav` plugin event which could be used to alter/replace the navigation. I'm not sure whether that would be practical, but you are certainly welcome to explore creating your own third-party plugin to address the issue.
