### ISSUE TITLE
Trailing # is stripped in title

### ISSUE THREAD

**Issue by thomaslevesque** [mkdocs/mkdocs#1693]
For this markdown title:

```markdown
### From C#
```

I expected it to be rendered like this:

> ### From C#

But it's rendered without the final `#`:

> ### From C

See the result here: https://fakeiteasy.readthedocs.io/en/stable/raising-events/#from-c

**Comment by facelessuser** [comment]
@thomaslevesque, this is because we are following the Markdown spec.  See: https://daringfireball.net/projects/markdown/syntax#header.

Also note that almost all Markdown parsers do this: https://johnmacfarlane.net/babelmark2/?text=%23%23%23+From+C%23%0A.  You will notice though that CommonMark does not, but keep in mind that CommonMark is a derivative of Markdown, it has created it's own Markdown spec which it follows. GitHub uses CommonMark.

Interesting though, I was going to suggest escaping via `\#`, but that seems to not work, not even in the reference implementation. This is a bit unexpected to me.  But you can do this `### From C# ###` And that will work. It seems you can also place a single space at the end as well `### From C# `.

**Comment by thomaslevesque** [comment]
@facelessuser thanks for your reply.

I don't suppose there's an option to use CommonMark in mkdocs?
If not, I'll use the suggested workaround (the current workaround is to use `&#x23;`)

**Comment by thomaslevesque** [comment]
> * While the examples all show a space before the closing hashes, the reference implementation does not require a space, and therefore, neither does Python-Markdown.
> 
> * IIRC, Commonmark dropped the closing hashes as almost no one actually uses them. But, as mentioned, Python-Markdown is not a Commonmark implementation.

Looks like the spacing is significant. CommonMark and others strip the trailing hashes, but only after a space.

**Comment by waylan** [comment]
> I don't suppose there's an option to use CommonMark in mkdocs?

Officially no. However, technically it should be possible to develop a Python-Markdown extension which altered its behavior to match Commonmark. At the very least, one could create an extension which alters the behavior of closing hashes for headers. 

However, that is outside the scope of the MkDocs project. Of course, anyone is welcome to develop their own extension as MkDocs [supports][1] using any third-party extension.

[1]: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions
