### ISSUE TITLE
Confusing Plugin Parameter Documentation

### ISSUE THREAD

**Issue by mike-schiller** [mkdocs/mkdocs#1715]
My apologies if this is poor form for an issue in this project, but I'm new to building plugins for mkdocs, have encountered a couple areas where things could be improved, and have a couple questions...

First,  https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/plugins.md#on_page_read_source
and
https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/plugins.md#on_page_read_source

both list `__page__` as the first argument. However, in one case, this is the positional argument described at: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/plugins.md#on_event_name and in the other, it is a keyword argument.

It would be extremely handy if the documentation for each event handler indicated which arguments are positional vs which are keyword. This will help developers to write more descriptive event handlers in their plugins. It is also now necessary to have the correct function signature and to understand the behavior when multiple plugins are installed with the the introduction of the recent PR: https://github.com/mkdocs/mkdocs/pull/1703 

With respect to that PR, I'm confused by two things....

1. Since a plugin may modify an object that is then passed to another object, how does one determine the order of plugin execution? Is it simply the order in mkdocs.yml ?

1. Maybe I'm misreading the code introduced by 1703, but the way I read https://github.com/mkdocs/mkdocs/blob/master/mkdocs/plugins.py#L96 it seems like if the initial item passed to run_event is None all called plugins will generate new objects, but only the object generated by the last plugin will have any effect. Is that the desired behavior?

**Comment by waylan** [comment]
> It would be extremely handy if the documentation for each event handler indicated which arguments are positional vs which are keyword. 

All arguments are keyword arguments. That is, all arguments are assigned to a keyword. Of course, as each keyword is positional, you could use positional arguments if you wanted. However, to future-proof your code, it is generally better to use the keyword in the event a future version moved the position.

To clarify, we do show `**kwargs` in the examples. However, that is also to future-proof your code. We are not actually passing any additional keywords at this time. Of course, a future version could include additional keyword arguments. By you including `**kwargs` your plugin will continue to work without needing any changes. Regardless, all documented arguments are passing to your plugin events as keyword arguments by MkDocs. I guess we assumed there was nothing to document because they are all the same. There should be no need to differentiate.

That said, if you see any inconsistency in the documentation, a PR is always welcome.

> 1. Since a plugin may modify an object that is then passed to another object, how does one determine the order of plugin execution? Is it simply the order in mkdocs.yml ?

Yes. If multiple plugins define the same event, they are called in the order they are loaded from the configuration.

> 1. Maybe I'm misreading the code introduced by 1703, but the way I read https://github.com/mkdocs/mkdocs/blob/master/mkdocs/plugins.py#L96 it seems like if the initial item passed to run_event is None all called plugins will generate new objects, but only the object generated by the last plugin will have any effect. Is that the desired behavior?

You are misreading. Not all events return an item. For example, the `on_pre-build` and `on_post_build` events will never return a modified item. The changes in #1703 simply ensure those events are properly identified. If an event is intended to return a modified item, then `item` will never be `None`. If an earlier plugin happened to return `None`, we use the previous value of `item` so, again, `item` should never be `None` except for events that do not modify items.
