### ISSUE TITLE
404 Page not built for theme in custom_dir

### ISSUE THREAD

**Issue by oxr463** [mkdocs/mkdocs#1724]
# Reproduction Steps

```terminal

git clone https://gitlab.com/lramage/pitch-dark

cd pitch-dark && mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /usr/src/pitch-dark/site

ls site/
about           css             js              posts           sitemap.xml     vendor
contact         index.html      package.json    scss            sitemap.xml.gz
```

## Configuration Files

- https://gitlab.com/lramage/pitch-dark/blob/develop/mkdocs.yml
- https://gitlab.com/lramage/pitch-dark/blob/develop/theme/mkdocs_theme.yml

**Comment by oxr463** [comment]
# Solution

`static_templates`, must be defined in `mkdocs.yml` otherwise it will not see it.

```diff
git diff mkdocs.yml
diff --git a/mkdocs.yml b/mkdocs.yml
index a7d0a32..0757323 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -12,6 +12,8 @@ remote_branch: master
 theme:
   name: null
   custom_dir: theme
+  static_templates:
+    - 404.html

 nav:
   - Home: index.md
```

**Comment by waylan** [comment]
Yes, this is expected behavior. If you have a theme defined in `custom_dir` then you need to manually define all config settings for the theme in the `theme` config of `mkdocs.yml`. MkDocs can only load a theme config from a "named" theme, not from `custom_dir`.

Note that "named" themes, must define a ` mkdocs_theme.yml ` file which defines such settings. However, that file is not loaded from a `custom_dir`. The `custom_dir` uses the `theme` config of `mkdocs.yml` only.

**Comment by oxr463** [comment]
Thanks for the quick response!
