### ISSUE TITLE
how to disable sitemaps?

### ISSUE THREAD

**Issue by paddylernt** [mkdocs/mkdocs#1735]
how can I disable the creation of a sitemap?

**Comment by waylan** [comment]
There is no official mechanism to do so. However, you should be able to accomplish this with a [plugin][1].

1. The sitemap is built from it's template because the template is included in the [`theme.static_templates`][2] config setting. A plugin should be able to remove that file from the setting.
2. The `sitemap.xml` template is contained in the Jinja environment directory `mkdocs/templates`. A plugin should be able to remove that directory from the environment.

One or both of those facts should provide some insight into where to start with a plugin.

[1]: https://www.mkdocs.org/user-guide/plugins/
[2]: https://www.mkdocs.org/user-guide/configuration/#static_templates

**Comment by paddylernt** [comment]
Well, I was kicking out any mention of sitemap.xml of /usr/local/lib/python3.5/dist-packages/mkdocs/tests/theme_tests.py and it keeps drawing those sitemaps.

**Comment by waylan** [comment]
The `tests` directory is only accessed when tests are run. It has no effect on a `build`.

**Comment by paddylernt** [comment]
That directory was the only occurance of "static_templates".

**Comment by waylan** [comment]
Not true. `static_templates` is defined at [mkdocs/theme.py#39][1] (which is where `sitemap.xml` is added), updated with the user config at [mkdocs/theme.py#L54][2] and updated with the theme config at [mkdocs/theme.py#L106][3].

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/theme.py#L39
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/theme.py#L54
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/theme.py#L106

**Comment by leonardehrenfried** [comment]
For everyone subscribed to this issue: I was finally annoyed enough by this that I wrote plugin outlined by @waylan.

https://github.com/leonardehrenfried/mkdocs-no-sitemap-plugin

**Comment by pawamoy** [comment]
Nice ! Would you like to contribute it to the [best-of-mkdocs list](https://github.com/mkdocs/best-of-mkdocs)?

**Comment by leonardehrenfried** [comment]
Would it be immodest of me to claiming that my code is "best of"? :flushed:

**Comment by pawamoy** [comment]
It's called a best-of list but we try to reference every plugin/theme/extension there :wink:

**Comment by whompyjaw** [comment]
In case anyone comes across this while trying to get your docs published on gh-pages using GitHub Enterprise, the plugin by leonard worked.
