### ISSUE TITLE
MarkDown links is valid in title and breadcrumbs, sidebar

### ISSUE THREAD

**Issue by Doarakko** [mkdocs/mkdocs#1745]
Is there any way to invalid it?

Example: my github pages
- [MkDocs](https://doarakko.github.io/mkdocs-github-pages/event/dena-techcon-2019/)
- [Sphinx](https://doarakko.github.io/event/dena-techcon-2019/index.html)

**Comment by waylan** [comment]
Do you perhaps mean "invalid" rather than "valid? Because if it is valid, then there is no problem.

Regardless, no there is not a way to disable it, except perhaps by customizing a theme by [overriding template blocks][1].

Also note that there has been some significant updates to the theme in #1594 which will be available in the next release. I don't recall exactly what all that addresses, but it may be relevant.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks

**Comment by Doarakko** [comment]
Sorry for the lack of explanation.
Fixed.
> Is there any way to avoid it?

And thanks for suggestions and information.
I try it.
