### ISSUE TITLE
Behavior changes after adding and then removing extension "mdx_inlcude"

### ISSUE THREAD

**Issue by craigphicks** [mkdocs/mkdocs#1761]
I made a fresh install of *mkdocs* on Ubuntu 18.04.
Vanilla `mkdocs.yml` with only `site_name: my title` as content.
The documents had a number of sections beginning 

```
<details><summary>
## section title 
</summary>
*some markdown content*
</details>
```
which were all completely translated by the default mkdocs markdown settings.

Then I added an extension via the `mkdocs.yml` - 
```
site_name: my title
markdown_extensions:
  - mdx_include: 
      base_path: docs
```
and installed the extension with 
    pip3 install mdx_include

Unfortunately, after that the markdown contents of the `<detail>` blocks were no longer translated.  So i returned `mkdocs.yml` to original state with only `site_name: my title`, uninstalled the extension
    pip3 uninstall mdx_include

and purged and reinstalled mkdocs - 
```
apt purge mkdocs
apt install mkdocs
```
However the ability the markdown contents of the `<detail>` blocks were still no longer translated.

Using the debug flag `-v` I can see the extensions now used:
    DEBUG   -  Config value: 'markdown_extensions' = ['meta', 'toc', 'tables', 'fenced_code'] 

Unfortunately I have no record of what was used originally while the `<details>` block were getting translated.

Perhaps adding and deleting the "mdx_include" changed the environment somehow?

Any clarification would be appreciated.

Note: I am aware that "transclusion" is not a feature `mkdocs` supports, so I am not asking about that.  I'd just like to know how to get back to the original fresh state.

**Comment by waylan** [comment]
I can't say for certain but my best guess is that you had an older version of Markdown before. Older versions did not recognize newer HTML5 tags as block-level tags. It is likely that when you installed the Markdown extension, the extension listed a newer Markdown version as a dependency and updated Markdown. The newer version then changed the way that the raw HTML was parsed.

This is further supported by the fact that you indicate that you are using `apt` to install MkDocs rather than Python tools (`pip`). We only activity support MkDocs distributed through Python's tools. Various other systems have been known to make their own modifications to the package and do not always offer the most recent version. The packages are available on those systems because some third party took it upon themselves to create the package, which our license does not prohibit. But we are not responsible for it, they are.

**Comment by craigphicks** [comment]
Hello again @wayland

Your guess sounds absolutely right.  If it didn't recognize the HTML tags it would surround them with `<p>`s - 

    <p><description><summary><\p>
    ### Title

which is known to allow markdown to process within the block.  
The what's I discovered yesterday by indenting `<description>` by one space from line start, which also causes the above surrounding by `<p>`'s.
