### ISSUE TITLE
Apostrophe in a File Name 

### ISSUE THREAD

**Issue by Ad-An** [mkdocs/mkdocs#1776]
In the `mkdocs.yml` it doesn't recognize a file whose path has an apostrophe (') due to its name.

For example

```
nav:
- 'path/file's_name.md'
```
Is there a requirement to not be apostrophes present in the file names or is there a way to use them without having this problem?

**Comment by waylan** [comment]
This is specific to YAML, which is very clearly defined by specification and not something we can change or have any control over.

That said, you have an invalid string. You were correct to try to quote it. However, as you used single quotes, the end of the string is you “apostrophe” (`path/file`). Everything after it is just extra text which I’m assuming that YAML parser is ignoring. The problem is that the parser can’t tell the difference between the quotes and the apostrophe.

Of course, the solution is to use double quotes:

```yaml
nav:
    - “path/file’s_name.md”
```

I suppose you could also escape the apostrophe if you really wanted to use single quotes. Although it is less readable:

```yaml
nav:
    - ‘path/file\’s_name.md’
```

Notice the backslash before the apostrophe, which tells the parser to treat is as a literal character and not a quote.

**Comment by Ad-An** [comment]
I didn't know that, thanks! On a side note, I had tried to escape the apostrophe but it didn't work.
