### ISSUE TITLE
JS files are served with wrong mime type which breaks search.

### ISSUE THREAD

**Issue by ceranco** [mkdocs/mkdocs#1790]
Hi,
I'm using mkdocs 1.0.4 to generate documentation with ReadTheDocs theme.
When using the `mkdocs serve` command, search works on *Internet Explorer* but not on *Chrome*.

The errors in the console are:

> Refused to execute script from 'http://127.0.0.1:800/search/lunr.js' because its MIME type ('text/plain') is not executable.

and 
> Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:800/search/lunr.js' failed to load.

**Comment by ceranco** [comment]
The problem seems to be in the web server that  `mkdocs serve` uses because the problem isn't replicated when hosting the site on nginx.

**Comment by waylan** [comment]
Which versions of `livereload` and `tornado` do you have installed?

And given you mention Internet Explorer, I assume you are on Windows?

**Comment by waylan** [comment]
This would appear to be a duplicate of #897 except that that was fixed (in the python-livereload package) back in 2016 and hasn't been changed since. There are a few things you can try to help narrow the problem down.

Confirm whether the problem is unique to the livereload server by using `mkdocs serve --nolivereload`. Does the problem persist?

If the problem only occurs when using livereload, then verify the version of livereload (you can use `pip freeze` to get a list of all installed packages with their version numbers).

If the problem persists when not using the livereload server, then tornado must be returning an incorrect mime type (liverload wraps tornado and only assigns its own mime type if tornado doesn't return one). There are two possible causes for this to happen:

1. Tornado has made a change, which seems highly unlikely. But check the version and tornado's release notes to be sure.
2. More likely, the system is improperly configured. Tornado relies in the `mimeypes` module in the standard lib, which relies on the OS to define mime types, You may need to confirm that your copy of Windows has the proper mime type defined for `.js` files. 

To confirm what `mimetypes` (and by extension tornado) returns, you can run the following command from the command line:

```bash
python -c "import mimetypes; print (mimetypes.guess_type('lunr.js'))"
```

It should return `('application/javascript', None)`. If it returns anything else, then see https://stackoverflow.com/a/3452261/866026 for instructions on defining a mime type on Windows.

**Comment by ceranco** [comment]
The problem was the incorrectly configured *MIME* type for `.js`.
Once I fixed that, everything started working.

Thanks for the help!

**Comment by cbrit** [comment]
I am having this issue (Windows 10) but my '.js' key in the registry is properly configured with "application/javascript".

The following command is returned a "text/plain" MIME type for lunr.js:

```
>> python -c "import mimetypes; print (mimetypes.guess_type('lunr.js'))"
>> ('text/plain', None)
```

I still have python 2.7, not sure if that could be the issue.

**Comment by cbrit** [comment]
Updating Python and reinstalling mkdocs did not fix it.

**Comment by waylan** [comment]
If `python -c "import mimetypes; print (mimetypes.guess_type('lunr.js'))"` is returning the wrong mime type, then that is a system configuration issue and outside the scope of anything we can help you with here. I suggest following up elsewhere (such as Stackoverflow, the python mailing list or similar).

**Comment by cbrit** [comment]
Thanks, you were right. The linked stack overflow question suggests a different registry key location than the one that was at fault.

For future readers, check HKCR:

```
reg query HKCR\.js /v "Content Type"
```
