### ISSUE TITLE
nav not working when building site

### ISSUE THREAD

**Issue by AlexandreKempf** [mkdocs/mkdocs#1798]
Hello all,
First thanks for mkdocs, I discovered it this week end and I'm loving it :heart_eyes: 

I have a problem using the classic format for `nav` in the yml file and then building the static site: 
```
nav:
    - Home: index.md
    - About: about.md
```
The website works **perfectly** with the `mkdocs serve` command. But the website is not working with the `mkdocs build` command. To be more precise, when I'm clicking on the links 'Home' or 'About', I get the access to the directory above these files (but on the browser). I think the links are not complete (missing a '/index.html' at the end).

I think I'm not reopening an issue, but I'm not sure (see #1746).

So far I managed to make it works by doing this:
```
nav:
    - Home: index.html
    - About: about/index.html
```
But this is not really elegant.

Do you have any idea how to fix this? 

I'm using Mkdocs 1.0.4 and Material 4.3.1

**Comment by waylan** [comment]
This is by design. For the links to work they need to be behind a server which is configured to support index pages (a request for the directory returns the index page). You can turn this off with the [use_directory_urls][1] setting set to `False`. However, be aware that other features such as search will not work when not behind a server.

[1]: https://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by AlexandreKempf** [comment]
Thank you for your reply :) I wasn't sure if it was normal or not ! You reassured me :)
