### ISSUE TITLE
Recursive config options for plugins?

### ISSUE THREAD

**Issue by k4kfh** [mkdocs/mkdocs#1808]
Is it possible to have recursive config options for plugins? Something like this:

```yaml
- plugins:
  - myPlugin:
    - parent:
      - child1: true
      - child2: false
```
I can't find much info on this in the documentation.

**Comment by waylan** [comment]
The only documentation for plugin configs can be found [here][1], which. admittedly, is not very informative. There are no restrictions in what can be defined in your plugin's config so long as it is doable in the config system. I suggest looking at the [source code][2] for MkDocs for an idea of the sorts of things you can do.

For example, notice that [plugin][3] validator expects a completely separate instance of a a config scheme for each "plugin". However, each scheme is completely independent and has no knowledge of any other schemes. I'm not sure what you mean by "recursive", but nested is possible as long as each instance doesn't need to know about any other instance.

For comparison, consider the [markdown extensions][4] option. It simply accepts a nests structure and leaves the actual validation of the pieces to the Markdown library (there is no scheme for the nested pieces). The point is, you can do whatever you want so long as it is contained within a single scheme.

[1]: https://www.mkdocs.org/user-guide/plugins/#config_scheme
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py
[3]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py#L565
[4]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py#L514

**Comment by k4kfh** [comment]
Okay, that answers my question that it is possible. But I am having a lot of trouble figuring out how to implement this. I don't understand why I can't just say ``("parent", config_options.Type(dict))`` in my config scheme. I also tried ``SubConfig()`` but that doesn't work either. I guess I am just not understanding exactly how this config scheme fits into the YAML parser?

**Comment by waylan** [comment]
```yaml
- parent:
      - child1: true
      - child2: false
```

Perhaps it would help to understand how YAML will parse your example. The above YAML will result in the following Python:

```python
[{
    'parent': [
        {'child1': True},
        {'child2': False}
    ]
}]
```

Note that as each of `child1` and `child2` start with a hyphen (`-`), they are list items. So the value of "parent" is a list of dicts, not a dict. You would need `("parent", config_options.Type(list))` to properly validate that. However, there is nothing checking that the items of the list are actually dicts, or that the keys of those dicts are known keys.

If you want a single dict object rather than a list of dicts, then you need this (note the lack of hyphens):

```yaml
- parent:
      child1: true
      child2: false
```

That will give you:

```python
[{
    'parent': {
        'child1': True,
        'child2': False
    }
}]
```

Note that in this case, the value of "parent" is now a single dict object which contains two key/value pairs. However, while `("parent", config_options.Type(dict))` will validate that that is actually a dict, it will not validate that `child1` and `child2` are known keys or that the values are valid values for those keys. To validate that, you will need to create your own custom `BaseConfigOption` subclass which checks all of those things.

In fact the `mkdocs.config_options.Plugins` class is such a subclass which takes a plugin config (with its own separate scheme) and  calls its validation. Of course, that subclass is specific to plugins and probably it not useful within nested items for a specific plugin. My guess would be that it  would be easier to simply validate the dict manually than try to adapt that to define a nested scheme.

**Comment by k4kfh** [comment]
Ah, yes, that makes a lot more sense. I think I understand a little better how things work. Thank you.
