### ISSUE TITLE
Page Title ignores setext-style headers

### ISSUE THREAD

**Issue by Rylon** [mkdocs/mkdocs#1826]
Hi!

I'm trying to create some internal documentation for a project that has a mix of custom and third-party code in it. Some of the third-party code has Markdown documentation I'd like to include, however some of the page titles aren't working, I think because these third-party docs use an alternative style of Markdown, where the headers are designated using either = or -, for example:

```
This is the title
=============

This is some content

This is a second title
------------------

Some more content

This is a final title
------------------

The end
```

In this case the title is not detected, and the filename README.md results in a title in the sidebar of 'Index'.

Is there anything I can do here to support this style of header? Do you have any suggestions?

Thank you!

**Comment by waylan** [comment]
Setext-style headers (as they are called) definitely are supported by Python-Markdown and should work fine in MkDocs. Could you provide the HTML generated by the example above? That may help us understand what problem you are having.

**Comment by Rylon** [comment]
Hi, it might be easiest to show you the Markdown file itself. The project I'm generating docs for contains Ansible roles, and here's an example of a README for a role which uses 'setext-style headers', and results in the name of 'Index':

https://github.com/andrewrothstein/ansible-etcd-cluster/blob/master/README.md

Thanks!

**Comment by waylan** [comment]
Again, I don't see a problem. Could you please provide the generated HTML?

**Comment by Rylon** [comment]
Hi again,

I've removed all the plugins and themes and just generated a super simple example using all the default options. In the default theme it's a bit less pronounced because the sidebar is actually the table of contents, but you can see the nav bar itself shows the page name as 'Index'.

I've attached the generated HTML as a .txt file, and also a screenshot of it in action:

<img width="887" alt="Screenshot 2019-07-14 at 23 45 11" src="https://user-images.githubusercontent.com/438452/61190282-d70e0600-a691-11e9-9aed-89e523048ce1.png">

[index.txt](https://github.com/mkdocs/mkdocs/files/3390492/index.txt)

The theme I'm hoping to use in production is https://squidfunk.github.io/mkdocs-material/ and this shows nav on the left, table of contents on the right, and it's the nav where the issue is, so sorry for any confusion in the original post.

**Comment by waylan** [comment]
It appears that the "page title" is being determined by using the file name. The process for determining a page title is documented [here][1]. Of relevance there is item 3:

> 3. A level 1 Markdown header on the first line of the document body.

The code which checks for a level 1 Markdown header assumes a hash header. Therefore a setext-style header is ignored. As no other methods for defining a title are found, MkDocs fails back to using the filename (item 4 in the above-linked documentation). "Index" is used rather than "Readme" as MkDocs treats a `README.md` file as an `index.md` file if no `index.md` file exists (see [docs][2]). 

Of course, as this is an "index file," changing the filename to set the page title is not an option. Therefore, you must define the title using one of the other three methods. However, until such time as setext-style headers are supported for page titles, you will either need to use something other than the page title (items 1 or 2) or use a hash header for at least the first header of the document.

At a minimum, the documentation should be updated to indicate that only hash headers are used for determining a page title. We could add support for setext-style headers as well, but I'm inclined not to.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data
[2]: https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages

**Comment by Rylon** [comment]
Hi,

Thanks for the explanation, that does seem to match what I'm seeing. The downside here is that these are docs from third-party roles, which can be upgraded via Ansible Galaxy. I'm not able to make direct modifications to them to use a hash header, although I would agree that's the best solution.

There's two modifications that I think would make this behaviour more flexible for situations like this - one is adding support for setext-style headers, and the other is taking the first header in the Markdown file, regardless of level because sometimes people use a level 2 header as the first, I guess for aesthetic reasons (it isn't as big a font size).

Again these issues only affect third-party docs that we don't have control of, but I was really hoping to be able to combine them with our real docs so it's all in one place, it feels like I'm very close here.

Maybe another alternative would be a plugin that can hook into the pages list to do this, but I'm not sure if it's too late at the point the plugin would be invoked?

I'd be happy to have a look at making a PR with the necessary modifications myself, but I'm not at all familiar with the code, would you be able to recommend where to start looking at all?

**Comment by waylan** [comment]
The page title is set in [`mkdocs.structure.pages.Page._set_title`][1].  The [`mkdocs.utils.get_markdown_title`][2] function actually extracts the title from the Markdown source and would need to be significantly refactored as it currently assumes the header is contained on one line only (it doesn't support setext-style headers because they take 2 lines). Note that the title is set on the page before the Markdown source is rendered to HTML and this is non-negotiable. It would be easier to get the header from the rendered HTML (which would eliminate any concern about which format was used), but MkDocs needs the title to be set at an earlier stage than when it renders the Markdown to HTML. This is documented behavior in the Plugin API which we have promised to continue supporting. Also, I will only consider a change which enforces the use of an H1. If the first header is an H2, then the page title should be defined elsewhere (such as in meta-data) and a custom theme template would presumably be inserting the page title as an H1 separate from the page body.

Finally, this is very much something which could be addressed by a plugin. I expect either the [on_page_markdown][3] or [on_page_content][4] events could be used to overwrite the page title based on the Markdown source or rendered HTML respectively. As a third-party plugin, you could then use whatever criteria you want to define a page title.

[3]: https://www.mkdocs.org/user-guide/plugins/#on_page_markdown
[4]: https://www.mkdocs.org/user-guide/plugins/#on_page_content
[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/structure/pages.py#L143
[2]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/utils/__init__.py#L332

**Comment by Rylon** [comment]
Thanks for the advice, that's very helpful. 😊

I think I've made the necessary changes in `mkdocs.utils.get_markdown_title` and got the behaviour I was looking for, but first I'll take a look at the plugin approach you've mentioned, to keep this nice and modular. 👍

**Comment by Rylon** [comment]
Hi, I've managed to make a small plugin that does everything I want here, however I'm left with one last hurdle to jump - if the page title changes, I need to be able to make sure the navigation is re-sorted into alphabetical order based on that.

I'm not sure if this is actually possible with the available events, as `on_nav()` seems to get called before the Markdown files have been processed in `on_page_markdown()`, so any changes to the titles don't affect the order of the nav, although they do show up when the nav is rendered, resulting in out-of-order items in some cases.

What would be your advice for this situation - could I possibly hook into the nav when it's being rendered to HTML and modify the order there, or do you have a better suggestion?

Thanks again.

**Comment by waylan** [comment]
The `nav` is sorted on filename regardless of any title. This is not unique to your plugin. That said, the `on_env` event is run after the `Page` objects are populated, but before any pages are passed to the theme. In other words it is called after `on_page_content` but before `on_page_context`.  It also has access to the `nav` object. You might want to try sorting the `nav` there.

Please consider adding any plugin you release on the [wiki][1] so others can find it.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

**Comment by Rylon** [comment]
Hi @waylan, so I did indeed release a small plugin to make these title and nav changes. I wasn't able to get the sorting to work, but I thought I would look at that another time, as for now it's doing mostly what I wanted. I'll add it to the wiki in case others find it useful.

https://github.com/rylon/mkdocs-nav-enhancements

Thanks for the help!
