### ISSUE TITLE
Search on github hosted page

### ISSUE THREAD

**Issue by smarie** [mkdocs/mkdocs#1871]
I just realized that search was not working on my mkdocs-generated pages hosted on github.

For example https://smarie.github.io/python-makefun/

From what I read around the web it seems that there is both some client-side search and server-side search happening: server-side works when I host the web page using `mkdocs serve`, but client-side search does not seem to work.

Before posting this issue on the `material` theme I wanted to check that this was not some known issue with latest version of mkdocs (client-side search not available anymore).

Thanks!

**Comment by waylan** [comment]
The material theme provides their own search implementation which is different from the default.  Please report your issue to them.

**Comment by smarie** [comment]
ok thanks for the answer !

**Comment by smarie** [comment]
It seems that the issue was not directly related to the `material` theme but to a behaviour of the `--dirty` flag : https://github.com/squidfunk/mkdocs-material/issues/1279

I do not know if that is on your side or on theirs, but @squidfunk advised me to report it to you. Thanks !

**Comment by waylan** [comment]
Ah, that makes sense. Of course the `ditry` flag is never meant to be used for a production build. It's only purpose is to speed up development, with the caveat that it doesn't result in a completely working site, as it only re-builds the changed page(s). If those changes effect the navigation or search index or any other global elements, then those should not be expected to work with the `dirty` flag. But that is why is comes with a warning.  There is no bug here.

**Comment by squidfunk** [comment]
@waylan we definitely need some way to better categorize issues into mkdocs and mkdocs-material or educate the users how to better narrow down problems. Happy to discuss any ideas. Too many half-baked issues recently. Time is precious.

**Comment by waylan** [comment]
> @waylan we definitely need some way to better categorize issues into mkdocs and mkdocs-material or educate the users how to better narrow down problems. Happy to discuss any ideas. Too many half-baked issues recently. Time is precious.

I agree. See #1629 where I propose a refactor of the documentation. Note in particular the paragraph regarding themes. I suspect that proposed change would help immensely with the MkDocs vs. theme problem. If only I had the time to do the work... Please feel free to provide any feedback on the idea in that issue rather than here.

Also, we could ask reporters to confirm that the issue is unique to a specific theme. I know you recently created an 'issue template.' I'm not sure if that is included or not. I could probably do the same. Although, I'm not particularly fond of those sorts of templates (I feel like they box me in when I'm trying to report an issue).

In any event, those are a few ideas. Not sure if they will help or not.
