### ISSUE TITLE
Broken Read the Docs link in deployment user guide

### ISSUE THREAD

**Issue by matthewcornell** [mkdocs/mkdocs#1884]
https://www.mkdocs.org/user-guide/deploying-your-docs/#read-the-docs links to https://read-the-docs.readthedocs.io/en/latest/getting_started.html#in-markdown in the "Follow the instructions on their site", but that link's broken. I found https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html?#using-markdown-with-sphinx , but I don't know what Sphinx is. Question: What is the correct page? Following your helpful https://www.mkdocs.org/#getting-started section, I created a GitHub repo for the project and then naively created a RTD account, linked it to my GitHub one, and selected the repo, but it did not find my docs/ dir. Obviously I need to learn "to arrange the files in your repository properly". Thank you.

**Comment by matthewcornell** [comment]
OK, I figured it out: I had to change "Documentation type" from "Sphinx Html" to "Mkdocs (Markdown)". Thanks.

**Comment by waylan** [comment]
RTD reformatted their documentation and moved the MkDocs specific stuff to a separate page: [Getting Started with MkDocs][1]. If you had hit the "next" button when viewing the Sphinx page, you would have found it.

As it turns out, this was reported and fixed in #1816 and will be available with the next release. I'm closing this as a duplicate.

[1]: https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html
