### ISSUE TITLE
gh-pages deploy via Circle-CI

### ISSUE THREAD

**Issue by casperdcl** [mkdocs/mkdocs#1898]
There should be a working example of how to use Circle-CI to deploy to gh-pages.

Unfortunately I couldn't get it to work using ssh (related to #1803 and #1413 but opening a new issue as per https://github.com/mkdocs/mkdocs/issues/1803#issuecomment-546980763).

e.g. https://circleci.com/gh/openworm/openworm_docs/574 fails despite having a github ssh user key with read/write access (https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys) and no default (read only) deploy key

```
WARNING -  Version check skipped: No version specificed in previous deployment. 
INFO    -  Copying '/home/circleci/repo/site' to 'gh-pages' branch and pushing to GitHub. 
ERROR   -  Failed to deploy to GitHub with error: 
ERROR: Permission to openworm/openworm_docs.git denied to openworm-bot.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 
Exited with code 1
```

The only way I could fix this was switching to https (see https://github.com/openworm/openworm_docs/commit/e85a00793c0cac4d311f3483651b817e45371442), which doesn't make much sense to me.

**Comment by waylan** [comment]
I've never used Circle-CI and and am not familiar with the service. Therefore I can't be of much help with configuring for the service and am not qualified to author any documentation about how to work with the service. Of course PR's adding to our documentation are welcome.

The first thing I need to now is if this is a bug in our code or not. If it is, then we will fix it. If not, then you need to work out the permission issues outside of MkDocs, then apply the solution to MkDocs itself. If it happens that MkDocs is missing support for something, we will consider adding it, but we need to verify the problem is actually with MkDocs first. And you have not provided enough information to determine that. 

To determine if the problem lies with MkDocs or elsewhere, try using the `ghp-import` directly:

```
mkdocs build
ghp-import site
git push origin gh-pages
```

Please report back the results you get from that and then we will know how to proceed. In short, if that works, then we presumably have a bug in MkDocs. If the problem persists there, then the problem is not with MkDocs, but elsewhere and is is not something we can help you with. In that case, I would suggest taking the issue upstream to [davisp/ghp-import][1]. If the problem is a configuration error on your part, any solution which works with `ghp-import` should also apply to MkDocs.

[1]: https://github.com/davisp/ghp-import

**Comment by casperdcl** [comment]
still an issue, opened https://github.com/davisp/ghp-import/issues/77
