### ISSUE TITLE
Support Subressource Integrity

### ISSUE THREAD

**Issue by nbraud** [mkdocs/mkdocs#1905]
Subressource Integrity is a standard feature of HTML, that lets a webpage specify a hash when loading a ressource (say, a script, a CSS stylesheet, ...).

Currently, `mkdocs`' default themes load ressources from `cdnjs.cloudflare.com` without specifying their hash, so both CDNJS and Cloudflare (or anyone successfully impersonating them) could inject evil content there.

Please consider:
- adding support for Subressource Integrity;
- enabling it by default;
- letting users specify their own preferred CDN for loading 3rd-party javascript.

**Comment by waylan** [comment]
A PR is welcome to add the appropriate hashes to the `<link>` and `<script>` tags in the existing themes.

As for letting users specify their own CDN, you can already do this by either [creating your own theme][0], or [customizing][4] an existing one. Additionally, an individual theme could offer the option through [theme configuration settings][3]. There is nothing that needs to change in the MkDocs core to do that.

Finally, for the record, here is the [W3C Spec][1]. Also see [Mozilla's overview][2].

[0]: https://www.mkdocs.org/user-guide/custom-themes/
[1]: https://www.w3.org/TR/SRI/
[2]: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
[3]: https://www.mkdocs.org/user-guide/custom-themes/#theme-configuration
[4]: https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks

**Comment by waylan** [comment]
Upon further review, and the extensive discussion in #1906, this is being punted to be implemented via a third party theme and/or plugin. Initially I was expecting a PR to simply add a few hashes to existing URLs, but on further review it is clear that it is much more complicated than that -- especially if we need to update the hashes with every future change. However, the solution proposed in #1906 demonstrates that an entire working solution can be contained within a theme.

Therefore, a custom theme or a fork of an existing theme could implement a fully working solution. Alternatively, a third party plugin could be developed to compliment a theme. The higher security should not be necessary for the average site containing static documentation. Any organizations which need the higher security (due to internal policies) should also have the resources to provide their own solution.

**Comment by limakzi** [comment]
@waylan As I see, this issue is pretty old.
Indeed, #1906 demonstrates that entire solution can be contained inside a theme.
Said that, I see a lot of examples, where `extra_javascript` is necessary, for example `KaTeX`, `MathAjax` support and it has nothing to do with a `theme`, per se.

A proper include should look like:

```html
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js" integrity="sha384-PwRUT/YqbnEjkZO0zZxNqcxACrXe+j766U2amXcgMg5457rve2Y7I6ZJSm2A0mS4" crossorigin="anonymous"></script>
```

This `integrity` has is extremely important for other websites, in case `cdn.jsdelivr.net` gets compromised.

**Comment by tomchristie** [comment]
> Indeed, https://github.com/mkdocs/mkdocs/pull/1906 demonstrates that entire solution can be contained inside a theme.

Agree. I think this is a theming issue.

We probably *should* be ensuring the ReadTheDocs and MkDocs themes have nice clear overriding for their `css` and `js` sections. We probably *shouldn't* be considering subresource integrity as a feature.

**Comment by squidfunk** [comment]
Just for completeness: this could be implemented as part of the [privacy plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/), which, albeit bundled with Material for MkDocs, is theme agnostic, and thus works for all themes. Most of the logic is already in place, as the plugin identifies and downloads all external resources, so it could compute the `sha384` of the resource and add that to the reference. Whether the element is self-hosted could be made optional.

If desired, we can discuss this over at [Material for MkDocs](https://github.com/squidfunk/mkdocs-material).
