### ISSUE TITLE
Expand the search plugin to use clauses built in to lunr

### ISSUE THREAD

**Issue by martinbira** [mkdocs/mkdocs#1914]
## Description

Extend the search capabilities of the MkDocs search plugin using the built in clauses in lunr to include strict or fuzzy matches.

**Disclaimer:** I'm not that good at Python or JavaScript, so definitions and methods may not be 100% correct, but it's my interpretation of the source code.

### Use Cases

Depending on the knowledge level of a user of what to search for, a strict term presence may increase matching for experienced users when using multiple terms, or a fuzzy match when the target user group may be less knowledgeable. Taking stemming into account, a strict term presence can assist in separating hyphened words.

###  Mockups

The search capabilities should be defined in the  `mkdocs.yml` file.
```
search:
    method: (undefined)|default|strict|fuzzy
```

#### Suggested options
**(undefined)/default:** The default/current search behavior is used.
**strict:** The search query should use the option `presence: lunr.Query.presence.REQUIRED` requiring all terms to be present in the result.
**fuzzy:** The search query should use the option `editDistance: 1` 

If no method is set, the search method should use `default` search behaviour.

**Note:** These options could perhaps be combined if there is a use case for it as they appear not to be mutually exclusive. I guess the different themes for MkDocs have different default implementations. 

---

Depending on the theme the search method could be consumed in different manners. An example of consumption based on what I've seen in Material for MkDocs where the rendered HTML include tokenizer and search languages could be:

``` 
<meta name=lang:search.method content=strict>
```

### Backwards compatibility

If no method is set, the search method should be `default`, thus not requiring users of older MkDocs versions to alter their `mkdocs.yml`-file

### Performance implications

Unsure if there will be any major implications of performance.

### References

https://lunrjs.com/guides/searching.html
https://lunrjs.com/docs/lunr.Query.html
https://lunrjs.com/docs/query.js.html#line76

**Comment by waylan** [comment]
As it stands now, [boosts][1], [fuzzy matches][2], and [term presence][3] are all possible now by using special characters in the search query. In other words, every feature you are asking for is already available with no code changes.

Of course, I realize you are asking for the default to be changed. However, you need to remember that the people who use search are the readers of your site, not necessarily the creators. And those users may have a very different default preference than you. Therefore, allowing the default behavior to be changed globally for a site by the creators may not be best for the users. 

Instead each user of the search feature should be able to chose their own behavior. And the current implementation allows that. Although, perhaps we could document it better rather than relying on lunr's documentation.

That said, I should note that the search interface is theme dependent. So there is nothing preventing a theme to implement its own different defaults. A theme could even provide an "advanced search" feature which provided various options to the user to alter the search behavior. But even then, no changes to the plugin need to be made. In fact, the Material theme provides their own client side implementation of search and only rely on the plugin to provide the data for the index. In other words, Material's search behavior is completely independent of the default provided in the plugin.

Given the above, I'm inclined to suggest that any such settings could be added to a theme, rather than the plugin itself. Yes, the theme devs would need to write their own JavaScript to make use of those settings, but there is no need for any changes on the Python side.

[1]: https://lunrjs.com/guides/searching.html#boosts
[2]: https://lunrjs.com/guides/searching.html#fuzzy-matches
[3]: https://lunrjs.com/guides/searching.html#term-presence

**Comment by martinbira** [comment]
Ok so it is more of a theming issue then. Got it.

**Comment by squidfunk** [comment]
It's fine, we'll implement it downstream. I thought it may benefit all themes and it's basically the same as the tokenization configuration, so just one more parameter to pull through. I always try to reflect on new feature requests whether they make sense for Material or for all themes and considered this to be a good candidate.

**Comment by waylan** [comment]
Yes, this is a good feature for all themes, However, for the reasons stated above, IMO this should only be set by the end user (the site reader) never by the theme or MkDocs. And if it is set by the end user, then it must be implemented in the theme. There should be no settings forcing the end user into a box unless you also give them a way to change the defaults (for example: advanced search).

**Comment by waylan** [comment]
As noted in [this comment][1], Material is using a different method for searching which does not support the [querystring functions][2] provided by lunr.js. As this is different that the default implementation provided by the `search` plugin, it would make sense for that theme to provide the customizations requested here. However, it would not make sense for the default implementation to do so as all of the customizations are built into the quearystring.

[1]: https://github.com/squidfunk/mkdocs-material/issues/1362#issuecomment-562186349
[2]: https://lunrjs.com/guides/searching.html
