### ISSUE TITLE
mkdocs should warn that "readme.md" is ignored

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#1923]
The following code results in a 404 when trying to reach "Overview":

```
nav:
  - Overview: "readme.md"
```

I usually symlink the repo root README.md into docs/readme.md.

Maybe mkdocs should warn that readme.md is ignored (https://github.com/mkdocs/mkdocs/pull/1767/files) in addition to the 404, because it was a bit surprising.

I fixed that by renaming the readme.md symlink to overview.

**Comment by waylan** [comment]
As [documented][1] `readme.md` is an alternative name of an index file. So it wouldn't be ignored, unless you also have an `index.md` file in the same directory, in which case it would be ignored. Presumably, if you have both files, then the `readme.md` file is for informational purposes in the source code (perhaps hosting on GitHub or the like), not as content for your site.

It would be weird to issue a warning for the default documented behavior. Additionally, a warning would cause `--strict` mode to fail when ignoring the file is an expected behavior as described above. Finally, the current behavior is fully documented. As there is no actionable item here, I'm closing this.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages
