### ISSUE TITLE
Document that filenames which begin with a dot are ignored.

### ISSUE THREAD

**Issue by spbrogan** [mkdocs/mkdocs#1924]
I have a folder in my documentation titled ".pytools" and within the folder I have a readme.md.  I list this in my TOC but when building the output is never there and the link goes to a 404.  My understanding is "." is a valid URL character so it seems like it should work.

**Comment by waylan** [comment]
Yes, all files and directories which begin with a dot are ignored. This is intentional as many private files and directories (especially on unix systems) traditionally use this naming convention. In fact, many web servers will not serve files using such a name format for the same reason. In other words, even if we accepted such names, the server wouldn't recognize them anyway.

Note that this only applies to file and directory names which **begin** with a dot. Names which contain a dot anywhere other than the first character are fine.

Finally, it appears that we have not documented this behavior. That needs to be done.

**Comment by spbrogan** [comment]
Makes sense.  Thanks for clarifying and updating docs
