### ISSUE TITLE
Strange handling of HTML tables

### ISSUE THREAD

**Issue by martin-frydl** [mkdocs/mkdocs#1927]
I'm using HTML `<table>` tag to create more complex tables with row and column spans, embedded lists etc. The problem I found is that mkdocs ignores any markdown constructs inside table when the tags are right at the beginning of line. When they are indented, for example by 4 characters to include in lists, it works fine. When trying to resolve the problem, I found it works even with single character indent - which does not create any special constructs around. Attached is example project [test.zip](https://github.com/mkdocs/mkdocs/files/3960203/test.zip) and here is what it generates:
![Selection_059](https://user-images.githubusercontent.com/26817338/70792349-4d29ac80-1d99-11ea-9f94-a38ca811503a.png)

**Comment by waylan** [comment]
All Markdown processing is handled by [Python-Markdown/markdown][0]. Any issues with the Markdown parser should be addresses there.

That said, this is the expected behavior of Markdown. As the [rules][1] explain (emphasis added):

> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.
> 
> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and **the start and end tags of the block should not be indented with tabs or spaces.** Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.
> 
> ...
> 
> Note that **Markdown formatting syntax is not processed within block-level HTML tags.** E.g., you can’t use Markdown-style *emphasis* inside an HTML block.
>
> ...
> Unlike block-level HTML tags, Markdown syntax *is* processed within span-level tags.

One of the requirements of block-level tags is that they not be indented by even a single space. If they are indented, then Markdown does not see them as block-level and they get treated as span-level tags. However, this is not a workaround to get Markdown processing within the tags as they also get wrapped in `<p>` tags, which you don't want.

Finally, for future reference, it is not helpful to provide a screenshot of your rendered page. Instead, you should be providing the HTML in a code block (you may need to use your browser's "view source" tool to get it). Also, the Markdown which resulted in that HTML should be provided. Without the two it is nearly impossible to help you debug any Markdown processing issues.

[0]: https://github.com/Python-Markdown/markdown
[1]: https://daringfireball.net/projects/markdown/syntax#html

**Comment by martin-frydl** [comment]
Just FYI, there was a zip file attached with markdown source and config yaml. That tiny link on rendered page is probably easy to miss.

**Comment by waylan** [comment]
Sorry, but I generally don't download random files from people I don't know.
