### ISSUE TITLE
Performance Questions ¿?

### ISSUE THREAD

**Issue by RicardoBritoBrens** [mkdocs/mkdocs#1960]
Hello

I got this questions

¿ How scalable is mkdocs ?
¿ Does Mkdcos support long site ?
¿ Is there any project using Mkdocs that can be use as a demostartion of the amount of pages i can include ?

Looking forward for your answers.

**Comment by waylan** [comment]
We have not done any formal performance testing at all. However, if you search through the closed issues and PRs you will find some users who have reported various useful pieces of info. For example, some have reported projects with thousands of pages.

Note that the entire collection of pages (as Markdown and as HTML) will need to fit in memory all at the same time. That is probably the most restrictive constraint, but given memory sizes these days, should not be a problem for all but the largest of sites. 

The second most likely constant is time. We do not use multithreading/processing so the time is linear. Assuming each page is roughly the same size, the total time would be the time for one page multiplied by the total number of pages plus some additional time for the config setup, etc. With the small sites I manage (no more than 20 pages), a build appears nearly instantaneous on a modern system. However, reports from some users with much larger sites report notable wait times for a build.

If you are using the dev server, some things you can do to speed things up are use `--no-livereload` or `--dirtyreload`. The first is easier on memory as there is no need to "watch" the files for changes. The second speeds up rebuilds as it only updates pages which are changed (rather than the whole site). However, a "dirty" build could result in menu items being broken on unchanged pages.

There is also the issue that some themes do not handle large numbers of pages well in the global navigation. However, that is not a performance matter, but a design issue.

**Comment by trel** [comment]
```
Done: Processed 202 articles, 0 drafts, 57 pages and 0 hidden pages in 7.25 seconds.
```

**Comment by RicardoBritoBrens** [comment]
Hello Mr. @waylan 

I really appreciate the time you take to share you know knowledge and experiences using Mkdocs.

I am so impress by the amount of possibilities Mkdocs is capable of, in addition i am currently working in an inside project on my department, to begin using MKdocs as a point of center all the documentations about Standards, Company Policies, Business Glossary etc.

Now is currently integrate with AzureDevops using CI/CD and Hosted at Azure Portal it is just awesome that with a single push to current branch i working on the hole build and publish process is complete in about `40` to `52` seconds.

Thanks also to @trel, to show me your results, this will give more show cases to convince my boss.

Regards from The Dominican Republic
