### ISSUE TITLE
Don't show code blocks line numbers in search preview

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#1965]
I am not sure if this depends on Lunr.js or the search plugin itself. Opening to get an idea if this is possible or not 🙂 

Using the mkdocstrings plugin, we can auto-generate doc from the code. It adds Python code blocks inside an admonition to show the source code of a function/method/class.

When searching for a function/method/class name, the preview shows the immediate content following a match, and in our case it shows the line numbers of the source code (see attachment).

![search_preview](https://user-images.githubusercontent.com/3999221/73193966-b425d980-412b-11ea-90d4-ef2e5f9c70bc.png)

https://github.com/pawamoy/mkdocstrings/issues/35 for reference.

Would it be possible to somehow hide these line numbers from the preview?

A simple solution would be to move the "Show source code" block lower, so it's not immediately after the match and doesn't appear in the preview, though I'd be interested in other possible solutions.

**Comment by waylan** [comment]
The search plugin simply extracts the plain text from the HTML for a page, which is then passed on to lunr.js to create an index. I suppose you are requesting that when the plain text is extracted, we skip the line numbers.

Interestingly, this would generally not be a problem with the builtin themes as they rely on a JavaScript library to handle syntax highlighting and line numbering in the browser, which is done after the search index has been created. That said, we certainly should support users (and themes) who desire to have syntax highlighting etc completed in the static content rather than on the client.

That said, if the mkdocsstrings plugin is always including line numbers for code blocks, that could be a problem and it would create a conflict with the JavaScript highlighter used by the builtin themes. It is not really clear to me if this is an issue unique to that specific plugin or not.

**Comment by squidfunk** [comment]
I believe it could be solved by ignoring the element with the `.lineno` class CodeHilite inserts in here:

https://github.com/mkdocs/mkdocs/blob/44f3ae212d85a60750769df0e9fa8022274166c8/mkdocs/contrib/search/search_index.py#L193

I understand that this would create an implicit dependency to CodeHilite but a lot of people use it together with Material. Another idea: add an option to the search plugin to ignore certain elements (via selector matching).

**Comment by waylan** [comment]
@squidfunk that’s not a bad suggestion. It would make the code a little more complex, but simply skipping any content within a ‘.lineno‘ element is a reasonable way to address this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by facelessuser** [comment]
One way that I've gotten around this is to provide a special custom inline style through Pygments. It creates spans for each line, but stores the line numbers in `data-linenos` then uses CSS to write the content of the spans with the data that was stored in `data-linenos`. No indexing of line numbers in search, and with a little CSS (like forcing the numbers to be sticky), it feels pretty much the same as the tables.

https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#line-number-styles. The style is called `pymdownx-inline` and you just use it instead of `table`.

![eDSh9KTFtI](https://user-images.githubusercontent.com/1055125/74614726-a256a700-50d7-11ea-9fde-40f20af9bf40.gif)

With that said, it'd be nice to avoid this issue with traditional Pygments tables, but it can be worked around in the short term. I personally don't use the table format anymore.

**Comment by waylan** [comment]
When Python-Markdown/markdown#816 is complete, users should be able to tell the CodeHilite extension to use Pygment's `inline` style, which would be a great way to avoid this problem. However, the issue is that the CSS needs to be different for that to work properly. I would encourage themes to add support for the format, then we can start encouraging users to adopt it either using `pymdownx-inline` (available now) or Python-Markdown Codehilite (coming soon).

>  it could be solved by ignoring the element with the `.lineno` class CodeHilite inserts 

By the way, initially I suggested that this could be a good solution. However, upon further reflection and remembering how Python's HTMLParser works, this would be extremely complicated to solve. It is certainly possible, but would require a complete state machine to be implemented within the HTMLParser subclass. That's a lot of work for very little gain. Switching to Pygments `inline` style and adding a few CSS rules is a lot easier solution which can serve a lot more use cases.

**Comment by facelessuser** [comment]
Pygments default inline style does not hide the numbers though. It injects them straight into the span content. So it will not really fix the issue. I don't know if I clarified enough that it is custom inline mode implemented in pymdown-extensions. Something like this could be ported over to Python Markdown, but I do not know if that is desired or not.

**Comment by facelessuser** [comment]
Though, for those not interested in using pymdown-extension to achieve this, when paired with Codehilite's inline functionality, with mkdocs plugins, you may be able to post process the HTML and retroactively create a similar end result.

**Comment by squidfunk** [comment]
> https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#line-number-styles. The style is called pymdownx-inline and you just use it instead of table.

We could definitely support this in Material, which is the theme the author is using. Care to PR the necessary changes in the refactoring branch, @facelessuser?

**Comment by facelessuser** [comment]
Yeah, I can do that.

**Comment by waylan** [comment]
> Pygments default inline style does not hide the numbers though. It injects them straight into the span content. So it will not really fix the issue. 

Ah, I missed that detail.

**Comment by squidfunk** [comment]
@facelessuser but the line numbers are at least tied to the respective line of code, so they wouldn't show up like in the screenshot, right? It's at least an improvement in regard to the current situation.

**Comment by squidfunk** [comment]
> By the way, initially I suggested that this could be a good solution. However, upon further reflection and remembering how Python's HTMLParser works, this would be extremely complicated to solve. It is certainly possible, but would require a complete state machine to be implemented within the HTMLParser subclass. That's a lot of work for very little gain. Switching to Pygments inline style and adding a few CSS rules is a lot easier solution which can serve a lot more use cases.

@waylan I'm quite astonished filtering out selectors would be that complicated to implement with the HTML parser. It's effectively just pruning subtrees, which I would expect to work with a DOM as well as SAX based parser. However, if it's that complicated, it's definitely not worth it.

**Comment by facelessuser** [comment]
Oh that's true. The line numbers are within the code blocks on the line numbers, and since code is excluded from search (at least I think it is) it would still be an improvement.

**Comment by squidfunk** [comment]
@facelessuser nope, it's part of the search. There was an issue in Material some time ago where JavaScript code blocks were executed when rendered in the search ;-)

**Comment by facelessuser** [comment]
I guess I'm confused, maybe I misunderstood your original statement. Pymdown-inline should be hidden from search. It's tied to the lines, but the content is hidden until the CSS writes the content into the span. This is an improvement. The screenshot is showing this inline behavior working.

Normal pygments inline just write it into the code blocks. It would still get indexed in search. So not an improvement.

**Comment by facelessuser** [comment]
The live example is found here: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#uml-diagram-example. Just scroll down till you see it.

**Comment by squidfunk** [comment]
Ah I see, so it would not show up in search because it's implemented as `data-attributes`. So this is again behavior where Pygments differs substantially from CodeHilite 🤓Too much stuff to maintain. Too many possibly combinations. Let's discuss the possibility for dropping CodeHilite from Material entirely and switching to Highlight over at [squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material).

**Comment by pawamoy** [comment]
Hey all, thank you very much for searching for a solution to this issue.

I have trouble following though. What highlighting extension should we use, and why? There's `pymdownx.highlight` and `codehilite`, right? Which one uses, or can use Pygments? Is it better to *not* use Pygments? Why? If not using Pygments, are there javascript files we need to add in `extra_javascript`? Which ones :grin:?

Sorry for the noob questions!

It seems the built-in themes and the material one are using different highlighting strategies, and also the highlighting extensions are being refactored? I'm a bit lost here :smile: 

I only noticed that `pymdownx.highlight.Highlight` is very easy to use in Python code, both for inline and not inlined code.

**Comment by waylan** [comment]
@pawamoy there is no clear answer. It all depends on your specific needs which is better for you. That said, each theme has a set f defaults which usually work best for that theme. For example, the builtin themes (`mkdocs` and `readthedocs`) both include `highlight.js` by default. The JavaScript Library and CSS necessary for that highlighting lib are included with the theme. However, they both provide the option to disable highlight.js with the `theme.highlightjs` config setting (as [documented][1]). Therefore, if you were to use one of those themes with Pygments, you would need to (1) enable the Markdown extension, and (2) provide your own CSS. In other words, it is more work that simply enabling another method.

In fact, that is the root of @squidfunk's last comment. As the developer of the `material` theme, apparently he was considering adding builtin support for all of the various highlighting methods. However, as each is so different from the next in various ways, if is not practical to do so. In the end, the simplest way forward would be to use the whichever option was chosen by the theme you are using. For anything outside of that, you will need to do some [customizing][2].

To be clear, outside of the themes, MkDocs itself makes no assumptions about how highlighting is done. In other words, we do not restrict support in any way. That is completely up to a theme. While the builtin themes have made a choice, that choice is not forced on any other themes in any way. So in the end, for most users, choosing which highlighting option to use is directly connected with choosing which theme to use.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#mkdocs
[2]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by squidfunk** [comment]
@waylan @pawamoy we added support for `pymdownx-inline` with the help of @facelessuser in Material for MkDocs 5, still undocumented though. If you're using Material for MkDocs, you can now use two different ways for line numbers:

__Table layout (classic)__

``` yaml
- markdown.extensions.codehilite:
      guess_lang: false
```

__Inline layout__

``` yaml
markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
```

For the inline layout, line numbers won't appear in search, but due to fixed positioning, horizontal scrolling is a little jaggy on Firefox Mobile

**Comment by pawamoy** [comment]
Hey everyone, coming back to this. I re-read the comments and I think that the `pymdownx-inline` style is the solution to this ([explanation by @facelessuser](https://github.com/mkdocs/mkdocs/issues/1965#issuecomment-586766725)), so I'll close the issue, but feel free to comment again or repoen 🙂
