### ISSUE TITLE
mkdocs/structure/toc.py, line 59, in _parse_toc_token TypeError: string indices must be integers

### ISSUE THREAD

**Issue by pawamoy** [mkdocs/mkdocs#2002]
It seems to be because of this change: https://github.com/mkdocs/mkdocs/pull/1970/files#diff-568fb30129902a6310b43ce5e37dfbb6R10 (from v1.0.4 to v1.1.0).

I'm using `page.toc = get_toc(getattr(md, "toc", ""))` in my code.
Supposed quick fix on my side (not tested yet):

```diff
-page.toc = get_toc(getattr(md, "toc", ""))
+page.toc = get_toc(getattr(md, "toc_tokens", []))
```

I'm not sure if this should be considered breaking change or not (is `structure.toc.get_toc` considered public API?). Maybe it was already deprecated some time ago and I missed the warning?

I'll update my code asap so feel free to close, I just opened for the sake of reporting 🙂

**Comment by waylan** [comment]
Are you using this in a plugin?

While it is not private (it does not start with an underscore), it is not documented, so it cannot be relied upon to be stable. In fact, in most cases, I would expect `page.toc` to get populated internally (which is why I didn't see a need to document this). However, I suppose a plugin which overrides page behavior would need to replicate some of that internal behavior. We probably should have documented the change. Thanks for the reminder.

**Comment by pawamoy** [comment]
> Are you using this in a plugin?

Yes I am! In [mkdocstrings](https://github.com/pawamoy/mkdocstrings)

> However, I suppose a plugin which overrides page behavior would need to replicate some of that internal behavior.

It's exactly what I am doing (re-rendering parts of contents). If I don't, then the TOC is not up-to-date.
Anyway, my plugin is not stable so it's not a problem. I will also change how it works (though still keeping the current output), and `get_toc` won't be needed anymore.

> We probably should have documented the change.

I guess it's hard to know who is using what part of the code and how :blush:
