### ISSUE TITLE
On build --site-dir  the README.md is ignored

### ISSUE THREAD

**Issue by ppKrauss** [mkdocs/mkdocs#2004]
Seems a **bug**. To reproduce it:

```sh
cd my_software_project_with_READMEs
mkdocs build --site-dir /var/www/mySite.org/docs
```
results in 
```
INFO    -  Cleaning site directory
INFO    -  ...
WARNING -  Documentation file 'SubDocsFolder/etc.md' contains a link to 
          'SubDocsFolder/index.md' which is not found in the documentation files.
```

But `SubDocsFolder/README.md` exists (!).  So, in that condiction `mkdocs build` is ignoring my `README.md` file.

------

Also relative path to folders that are not into /docs are ignored. For example my `/assets` for images and my `/src` no navigate on source-code, all are working on Github navigation at `/docs` but not with mkdocs navigation.

**Comment by waylan** [comment]
> But `SubDocsFolder/README.md` exists

True, but you linked to `SubDocsFolder/index.md`, which does not exist. Yes, both files could result in the built page `SubDocsFolder/index.html`. but that doesn't make the two source files the same. You need to link to a real file that exists in your `docs_dir`.

As a reminder, one of the reasons we go through all the trouble of doing the path matching and conversion is so that links still work while browsing the source (for example here on GitHub). Your link does work in that context, therefore, MkDocs doesn't recognize it as a link either (both are relying on the same method logic - a relative path to a file which exists). There is no cleverness going on, nor should there be.
