### ISSUE TITLE
Incorrect wording

### ISSUE THREAD

**Issue by danielhoherd** [mkdocs/mkdocs#2009]
https://github.com/mkdocs/mkdocs/blob/c9032bd6bfde09ead2f4f879e85590d7cd6e68a6/mkdocs/config/config_options.py#L357-L359

I discovered this error when trying to set `docs_dir: .`, which produced:
```
$ mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent
directory of the config file. Use a child directory instead so that the config file is
a sibling of the config file.
```

The first confusing thing that caught my eye was "the config file is a sibling of the config file."

The next thing that caught my eye is that using `docs_dir: .` does not make the docs dir the parent of the config file, it would make it a sibling of the config file.

**Comment by waylan** [comment]
I've reread the error message multiple times and I don't see anything incorrect in the statement. 

Where `cwd` is the current working directory, given the following file structure:

```
cwd/
    mkdocs.yml
    index.md
```

You would get the error above if you set `docs_dir: .` In that case, `.` would expand to `cwd/` which is the parent directory of `mkdocs.yml`. Therefore the statement:

> Error: The 'docs_dir' should not be the parent directory of the config file.

is correct as it identifies the actual situation nd states that that is not allowed. What you should have instead is this:

```
cwd/
    docs/
        index.md
    mkdocs.yml
```

And then you can set `docs_dir: docs`. In this situation, the value of `docs_dir` is a child is `cwd` (addressing the first half of the second sentence) and `cwd` is a sibling of `mkdocs.yml` (addressing the second half of the second sentence.

If course, you don't need to use the directory name `docs`, which is why we allow you to set your own value. However, we do not expect the directory layout to change from the example above.

**Comment by waylan** [comment]
Ah, now I see the problem. The message should state:

> ERROR   -  Config value: 'docs_dir'. Error: The 'docs_dir' should not be the parent directory of the config file. Use a child directory instead so that the <del>config file</del><ins>'docs_dir'</ins> is a sibling of the config file.
