### ISSUE TITLE
404 on get for search_index.json

### ISSUE THREAD

**Issue by RanVargas** [mkdocs/mkdocs#2040]
The search bar doesnt work, and when I debug I see that the search_index.json throws a 404, but this doesnt happen when on local hosting. My version of mkdocs is 1.1 and the theme is material.

**Comment by waylan** [comment]
Is your site being hosted from the server root, or from a subdirectory?

Do you have the `site_url` config setting properly set?

**Comment by RanVargas** [comment]
It is hosted from a subdirectory. And yes, the site_url is properly set.

**Comment by waylan** [comment]
Does the `site_url` include the subdirectory?

**Comment by RanVargas** [comment]
It only includes the website per se.

**Comment by waylan** [comment]
The `site_url` setting needs to include the entire URL to the homepage, including any subdirectory.

**Comment by RanVargas** [comment]
Could you give me an example please? 

In my site_url i have the plain link to the site as it appears on the browser like: 'https://somewebsiteforexmple.azurewebsites.net/'
should it be something different than this?

**Comment by waylan** [comment]
Previously you stated:

> It is hosted from a subdirectory.

Therefore I assumed that the home page of the MkDocs site is at a subdirectory. Perhaps `http://example.com/subdir/`. Therefore, that entire string would need to be the `site_url`.

However, now it appears that your site is actually in a subdomain (rather than a subdirectory). Regardless, `site_url` should be set to the entire URL to the home page. Unfortunately, you still haven't convinced me that you have it set correctly.

So, if you homepage is at `http://sub.example.com`, then that should be the `site_url` and the search index file should be at  `http://sub.example.com/search/search_index.json`.

If your homepage is at `http://example.com/sub/`, then that should be the `site_url` and the search index file should be at  `http://example.com/sub/search/search_index.json`.

In either case, if the URL to `search_index.json` is returning a 404, then one of two issues exist:

1. When you uploaded/deployed your site, you failed to include the `search_index.json` file.
2. If the file has been properly deployed, then the server is not properly configured to serve a `json` file.

However, if MkDocs is looking for the file at the wrong location, then that is a bug. Unfortunately, I don't have enough information from you to determine if that is the case.

**Comment by RanVargas** [comment]
The server was not configured to serve json files, which was configured adding a web.config file to the project. Thanks for your assistance.
