### ISSUE TITLE
livereload doesn't work when browser connects to default ports 80/443

### ISSUE THREAD

**Issue by boskkrkbuh** [mkdocs/mkdocs#2046]
**mkdocs 1.1 and livereload 2.6.1**

- This is also valid when mkdocs runs behind a forward proxy like nginx.
- To reproduce install mkdocs and run it locally with '--dev-addr 127.0.0.1:80'

Background:
We had to setup a two day conference of five groups distributed over the world. At every location screens were installed to show the results of the other groups without the need to refresh manually. For this mkdocs has been chosen. Due to regulations of the local IT administration we had to use TLS and the default port for HTTPS. So we noticed the lack of the livereload-feature.

As noted [here](https://www.w3schools.com/jsref/prop_loc_port.asp) the default port isn't set in some browsers. This has been seen on Firefox and MS Edge.

For a quick (and dirty) workaround we have changed serve.py from the livereload package to use always the port 443:
`live_script = escape.utf8(live_script % '443')`

But this can't be a sustainable solution for everyone. We suggest to set the port based on the protocol used to 80 or 443 if not provided.

**Comment by waylan** [comment]
> This is also valid when mkdocs runs behind a forward proxy like nginx.

First I must point out that this is not a supported use of the server included with MkDocs. The dev server is **only** intended to be used on a local machine for local development. We will not support anything outside if that use case. Any bugs which are reported will not be fixed. You should be using a production ready server to serve the flat files which are built by MkDocs.

Second, regardless of the above, I suspect this is an issue with the upstream package at [lepture/python-livereload][2]. To confirm if this is the case, I suggest building the MKDocs site and then using python-livereload directly to serve the site. If the problem persists, then you should report the issue upstream. However, if the problem is not exhibited by python-livereload, report back here and we will decide whether we want to support ports 80 & 443 (I suspect not as a means discouraging use cases that we don't support).

[1]: https://github.com/lepture/python-livereload

**Comment by gagalago** [comment]
seems that it's already reported https://github.com/lepture/python-livereload/issues/194. So we have to wait :sleeping:

**Comment by boskkrkbuh** [comment]
This has been already be solved by a commit, still waiting for approval.

**Comment by oprypin** [comment]
The fix is present in the latest version of the "livereload" library, so this works.

Moreover, the "livereload" isn't used anymore on latest `master`, and I also confirmed that with the new implementation `mkdocs serve` works without a port.

So this can be closed.
