### ISSUE TITLE
List or table of all officially supported basic styling commands avaliable in mkdocs with examples

### ISSUE THREAD

**Issue by dynamiccontent** [mkdocs/mkdocs#2047]
Hello,
Is this available anywhere? I am looking and looking and coming up with nothing. I would like to test and use as many commands as possible to style my documentation and make it pretty and clear for people to read without using CSS. Just keeping it simple. I am already using one of officially supported themes now I just need to style my text.

Is this https://daringfireball.net/projects/markdown/syntax really all that is available?
I also found this https://guides.github.com/features/mastering-markdown/ & https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

How can I make this kind of styling without extra CSS or JavaScript:
https://imgur.com/AmusidY
https://imgur.com/dTRqDIj
https://imgur.com/MzQLz5n
Also how can I make an external url open in new page on web browser?

Is it possible? Thank you for reading.

**Comment by waylan** [comment]
> Is this https://daringfireball.net/projects/markdown/syntax really all that is available?

That is what is available from Markdown. However, we also include some Markdown extensions by default. Those are documented [here][1]. Of course, you can [add additional extensions][2]. You should see the documentation for any specific extensions that you use. There are also a number of third party MkDocs [plugins][3] which may add additional features. You can find the documentation for each extension you use documented by the developers of that extension.

Finally, you should check the documentation for the theme you are using. Some themes may include hooks that others do not. For example, the built-in `mkdocs` theme supports some [user configurable options][4]. Also, as it is a bootstrap theme, it contains the necessary CSS and Javascript to support all of Bootstrap's [hooks][5].

That said, Markdown is pretty basic by design. As the rules [explain][6]:

> Markdown is not a replacement for HTML, or even close to it. Its syntax is very small, corresponding only to a very small subset of HTML tags. The idea is not to create a syntax that makes it easier to insert HTML tags. In my opinion, HTML tags are already easy to insert. The idea for Markdown is to make it easy to read, write, and edit prose. HTML is a *publishing* format; Markdown is a *writing* format. Thus, Markdown’s formatting syntax only addresses issues that can be conveyed in plain text.
> 
> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself.

In case is its't obvious, to make use of Bookstrap's hooks, one would need to use raw HTML within your Markdown documents. But then we have things like the [Admonition Extension][7] to Markdown, which provides a way to use Markdown rather than relying on raw HTML. However, as that extension is not on by default, we don't document it as any user to specifically enables it would need to know about its existence to be able to enable it. Then they would need to provide the necessary CSS for it to work properly. That said, you may find that some third party themes include the CSS by default. You simply need to enable the extension.

This is all a long way of saying, we already have all of the documentation we can possibly have on the subject.

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
[2]: https://www.mkdocs.org/user-guide/configuration/#formatting-options
[3]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
[4]: https://www.mkdocs.org/user-guide/styling-your-docs/#mkdocs
[5]: https://getbootstrap.com/docs/4.4/components/alerts/
[6]: https://daringfireball.net/projects/markdown/syntax#html
[7]: https://python-markdown.github.io/extensions/admonition/

**Comment by dynamiccontent** [comment]
@waylan Thank you very much. This is exactly what I was looking for. Thank you for taking the time and explaining it to me. Everything is clear now and on my search for information I actually was already using some mix of html and markdown to satisfy all requirements for my documentation. It was working ok. Will check everything else you noted in you post. Thanks again.
