### ISSUE TITLE
[Questions] Are there other sources of (community) support?

### ISSUE THREAD

**Issue by Andre601** [mkdocs/mkdocs#2055]
I really like to use MkDocs (Thanks for this software guys), but to be honest, the support for it is "limited" to say the least.

While IRC is a good platform does not everyone like to use it. And the same also goes for the Google Forum about MkDocs: While it may be a place for asking questions and receiving answers does not everyone like to actually be part of it (especially if it makes you watch every forum post there by default D:<)

Other options like GitHub issues or StackOverflow questions are again not the best option as it could be slow to receive an answer to an urgent question (or you don't get an answer at all \*glares over to StackOverflow*)

So I was asking if there's any other platform (i.e. a (Community) Discord server) for receiving support for various questions regarding MkDocs...

**Comment by waylan** [comment]
@Andre601 the places you already mentioned are where the dev team (mostly only me these days) watch. Anything else isn't watched by anyone in the community that I know of. Personally, my time is stretched way too thin as it is. I'm actually trying to cut back on the places I follow. Github is the one for-sure place to get me most days. The Google Group and Stackoverflow are a once-a-week thing anymore. Oh, and posting the same question on multiple forums just annoys me because I now need to answer the same question multiple times.

Of course, the supports limited because we are all volunteers working in our spare time. If you would like things to improve, then volunteer and help us out.

**Comment by Andre601** [comment]
I understand this and I would like to help volunteer (mostly in support-related stuff), if my knowledge of MkDocs wasn't that limited, which it sadly is.
And I myself already have many places where I help people out, so I can understand all too well how it can feel like to often answer the same question multiple times.
Thanks for the detailed response for this.
