### ISSUE TITLE
Main menu are broken

### ISSUE THREAD

**Issue by godskiy** [mkdocs/mkdocs#2057]
Just installed my mkdocs version 1.1. Selected theme called "readthedocs".  Tried to add some nodes and subnodes to main menu, but menu is completely broken after build(It doesn't reflect the menu tree at all).

Also I have this error in console:
![image](https://user-images.githubusercontent.com/18336447/78984800-d1195880-7b2f-11ea-9214-68609efb6b86.png)

Any ideas?

**Comment by waylan** [comment]
What do you have in the `nav` option?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by godskiy** [comment]
Absolutely nothing. I Tried to generate menu via nav option, but had same issues

**Comment by waylan** [comment]
I’m going to need some more details so I can replicate your situation 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by godskiy** [comment]
Ok, [here](https://vimeo.com/user112677852/review/407080694/813a30a1e8) it is.

Also my mkdocs.yml
![image](https://user-images.githubusercontent.com/18336447/79108515-3020dc80-7d7f-11ea-8864-7de830a83650.png)

**Comment by waylan** [comment]
Your link is broken. Although it appears to point to Vimeo. I'm not sure how that would help me replicate your setup. You need to provide the file layout, etc. Everything should be in a text format so we can copy/paste.

**Comment by godskiy** [comment]
Okay. As I said before I installed mkdocs v 1.1

My mkdocs.yml:


```
site_name: My Docs
theme: readthedocs
```

docs/node/subnode1/subsubnode1.md:

`# Subsubnode 1 head`

docs/node/subnode2/subsubnode1.md:

`# Subsubnode 1 head`

docs/index.md: 

```
Welcome to MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).

Commands

* `mkdocs new [dir-name]` - Create a new project.
* `mkdocs serve` - Start the live-reloading docs server.
* `mkdocs build` - Build the documentation site.
* `mkdocs -h` - Print help message and exit.

Project layout

    mkdocs.yml    # The configuration file.
    docs/
        index.md  # The documentation homepage.
        ...       # Other markdown pages, images and other files.

```

docs/index-copy.md: 

```
Welcome to MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).

Commands

* `mkdocs new [dir-name]` - Create a new project.
* `mkdocs serve` - Start the live-reloading docs server.
* `mkdocs build` - Build the documentation site.
* `mkdocs -h` - Print help message and exit.

Project layout

    mkdocs.yml    # The configuration file.
    docs/
        index.md  # The documentation homepage.
        ...       # Other markdown pages, images and other files.

```

I'll try to describe my problem:

Theme creates those plus / minus things, but I can't get the logic of how it opens / closes them. It seems just randomly. Also I cant get when the theme generates them(for example you can click on node/subnode1/subsubnode1 in menu, then it creates plus / minus elements cuz of header inside)

**Comment by waylan** [comment]
I just recreated your project and now I see the problem. Thank you.

The documentation for the `readthedocs` theme [states][1] (emphasis added):

[1]: A clone of the default theme used by the [Read the Docs][2] service, which offers the same restricted feature-set as its parent theme. Like its parent theme, **only two levels of navigation are supported**.

As stated there, "only two levels of navigation are supported" but you have three: `node => subnode1 => subsubnode1`. The third level is treated by the theme as a header within `subnode1` rather than a separate page. If instead you eliminated one of the levels everything would work as expected.

Note that, as documented, this theme emulates the behavior of the upstream Sphinx theme which it is a clone of. And that upstream theme only supports two levels. Therefore, we will not consider expanding our clone to support more levels. If you need more than two levels, then you need to use a different theme.

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs
[2]: https://readthedocs.org/

**Comment by godskiy** [comment]
Thanks you! I'll try out another theme then.
