### ISSUE TITLE
livereload reloads for every file that changes

### ISSUE THREAD

**Issue by Stanzilla** [mkdocs/mkdocs#2061]
Currently when developing a theme, having mkdocs run via serve reloads the page as often as each file changes in a theme. So if run my theme's build process, it reloads the page around 34564564564640 times or more.

**Comment by waylan** [comment]
Then I would suggest shutting down the dev server when you build your theme. Note that the builtin themes have no build process but are rather simple. And wow, that is a lot of files for a theme.

**Comment by Stanzilla** [comment]
Yeah that is what I am doing at the moment and trying to avoid :)

**Comment by squidfunk** [comment]
This is indeed super annoying and shouldn't be too hard to fix by batching updates. It can easily be reproduced by checking out [squidfunk/mkdocs-material/](https://squidfunk.github.io/mkdocs-material/), start `mkdocs serve` in one session and the Webpack watcher with `npm start` in another one. After Webpack rebuilds, `mkdocs serve` will reload more than 5.000 times for every asset that's contained within the build.

**Comment by waylan** [comment]
The MkDocs `serve` command is a light wrapper around [lepture/python-livereload][1]. When used directly, that tool provides a `--wait` option which causes the watcher to delay sending the reload signal by the specified number of seconds. Would adding that option to MkDocs address this? If so, a PR is welcome.

Note that as this is not needed by the core dev team, it is a low priority and not something we are likely to implement ourselves. However, I am happy to review a PR if someone else wants to do the work.

As a workaround, you can always use python-livereload directly.

[1]: https://github.com/lepture/python-livereload

**Comment by squidfunk** [comment]
I understand that this is not a priority. However, note that there’re more than 900 forks of Material for MkDocs which all have this problem, so quite an audience.

**Comment by squidfunk** [comment]
I think there's something that needs to be done on that front.

Material for MkDocs now bundles 5k icons, which is what the OP is referring to. Not only will python-livereload queue up every file and reload the page, again and again, the general rebuild time has also increased. In https://github.com/squidfunk/mkdocs-material/issues/1598, the OP says that a reload now takes 10.5s as opposed to 4.5s before (which also is quite slow).

Additionally, python-livereload [is looking for maintainers](https://github.com/lepture/python-livereload) and seems rather abandoned (the last commit was 6 months ago), so maybe this is a good time switching it for something faster and less annoying.

Again, I understand, that this is not a priority from the maintainers' perspective, but given the sheer amount of people using Material for MkDocs, which accounts for 40% or more of all MkDocs installations, it would be great, if alternatives could be evaluated.

**Comment by waylan** [comment]
I just created PR #2093 which adds a `--wait` flag to the `serve` command. However, I'm not perceiving any change in behavior. But then I don't have a need for the delay. If someone could try it out and report back that would be helpful. Please follow up on the PR rather than here.

**Comment by waylan** [comment]
I am reopening this issue as #2093 has been reverted in #2285.

Note that no one should be writing to the `docs_dir` during a build. A plugin would instead use a `File` object to point to an outside location. However, it is understandable that a theme developer may need to "build" their theme (render CSS from LESS, SCSS, SASS, etc) and we need some way to support that without rebuilding every time a new file is written to the theme dir by the theme's "build" process.

The issue reported here (specific to themes) is avoided by the fix in #2094 as the theme dir is no longer watched by default. However, if a theme developer is using the `--watch-theme` option introduced in #2094, then this issue still exists.

**Comment by oprypin** [comment]
The way to observe this issue currently, regardless of themes:

`mkdocs serve`
Wait for the first build to finish and open another terminal.
`find . -name '*.md' -exec touch {} \;`
If there are N files, you will see the site rebuild itself in a loop N times, without any interaction whatsoever.

**Comment by oprypin** [comment]
Unfortunately the 'livereload' module indeed provides no way to batch multiple filesystem updates into one.
It only kinda attempts to alleviate this problem here
https://github.com/lepture/python-livereload/blob/4a8e4031b3bb1322beb5ce285fac84104b4151ce/livereload/handlers.py#L80
but that applies only if the callback's duration is very small, if it works at all (I wasn't able to observe this "ignore" behavior)

It is possible to hack around it, by adding a wrapper with a tiny (non-configurable) delay and waiting for it to produce another callback in that period, for the purpose of batching them.

Or, I found this alternative implementation (seems like the author just wanted a better rewrite of livereload), and it appears to do the right logic for batching here:
https://github.com/thanethomson/httpwatcher/blob/373bddf1af99f5cc84917b5c8d4075ce3725a2ad/httpwatcher/filesystem.py#L64-L68

**Comment by waylan** [comment]
> Or, I found this alternative implementation (seems like the author just wanted a better rewrite of livereload), and it appears to do the right logic for batching here:
> https://github.com/thanethomson/httpwatcher/blob/373bddf1af99f5cc84917b5c8d4075ce3725a2ad/httpwatcher/filesystem.py#L64-L68

Awesome! I hadn't seen that before. I would be okay with exploring switching to an alternate livereload server. The existing server has been one of the largest pain points and our requests for upstream changes often go unheard as the package has a different goal (see lepture/python-livereload#131 for example). Interestingly, the README for httpwatcher specifically [mentions][1] that it was build to support a static site generator. I also find it interesting that is uses [watchdog][2] rather than reinventing that wheel.

[1]: https://github.com/thanethomson/httpwatcher#background
[2]: https://github.com/gorakhargosh/watchdog

**Comment by oprypin** [comment]
Sadly, seems abandoned :( https://github.com/thanethomson/httpwatcher/issues/2
Though reviving it isn't fully out of the question

**Comment by waylan** [comment]
> Sadly, seems abandoned 

That is unfortunate.

**Comment by jleclanche** [comment]
Maybe take a page from FastAPI's playbook and consider using [uvicorn](https://www.uvicorn.org/) as server. It [does have live reload implemented](https://www.uvicorn.org/settings/#development).

**Comment by oprypin** [comment]
I am presenting a new livereload implementation without these shortcomings.
See #2385, and I welcome people to try it out.

**Comment by oprypin** [comment]
Then you're in a great position to try out https://github.com/mkdocs/mkdocs/pull/2385. Please let me know if it helps for that situation.

**Comment by charlescurley** [comment]
On Fri, 07 May 2021 14:45:04 -0700
Oleh Prypin ***@***.***> wrote:

> Then you're in a great position to try out
> https://github.com/mkdocs/mkdocs/pull/2385. Please let me know if it
> helps for that situation.
> 

Sorry, no go. I cloned the mkdocs repo, got the patch files (add
'.patch' to the URL for the two commits in your pull request), and
tried to apply them.

```
***@***.***:~/versioned/mkdocs$ git apply ~/mkdocs.patch1.diff
error: patch failed: mkdocs/__main__.py:169
error: mkdocs/__main__.py: patch does not apply
error: patch failed: mkdocs/commands/serve.py:1
error: mkdocs/commands/serve.py: patch does not apply
error: patch failed: requirements/project-min.txt:1
error: requirements/project-min.txt: patch does not apply
error: patch failed: requirements/project.txt:3
error: requirements/project.txt: patch does not apply
error: patch failed: setup.py:53
error: setup.py: patch does not apply
***@***.***:~/versioned/mkdocs$ ls
```

And that leaves the problem that I am not a python programmer, and have
no idea how to install from the git repo if I could apply the patch.


-- 
Does anybody read signatures any more?

https://charlescurley.com
https://charlescurley.com/blog/

**Comment by waylan** [comment]
@charlescurley you should be able to install from @oprypin's branch directly using this command:

    pip install git+https://github.com/oprypin/mkdocs.git@reload

I know I would certainly like some feedback from a user who has a need for this.

**Comment by oprypin** [comment]
Thanks for your report. I could reproduce this if I also configure my editor "Kate" to write to the local directory instead of a separate global one (which emacs really should be doing instead...)

I think what saved the previous implementation is that it was checking for files' modification times before concluding that the file changed.
https://github.com/lepture/python-livereload/blob/ecabebaeee2a40743f5a8216e1856c9f9150913f/livereload/watcher.py#L180

In our case I have pushed new code to rely only on "file close" events that editors always emit on save, and disregard "file modified" events which get tripped by these swap writes.

Please try this again and let me know how that goes. *Now* it really should be better than the old server.

Regarding ignoring certain filenames: I think it's not a clean approach, and would end up being the usual whack-a-mole...

**Comment by oprypin** [comment]
Well I can guess that it will work for you, but I also see that this approach completely doesn't work on Mac and Windows, so nevermind...

**Comment by jobveldhuis** [comment]
I am currently in the middle of reviving httpwatcher and I see this has been mentioned here before. Is there any feature you need/require that is not in the httpwatcher module?

**Comment by oprypin** [comment]
@jobveldhuis Thanks for the mention. No, I have no interest in httpwatcher, as I'm quite convinced that the implementation from https://github.com/mkdocs/mkdocs/pull/2385 basically makes it obsolete (unless you have the specific requirement of integrating with "tornado" server). httpwatcher runs on 1-second polling, with (as I realize now) most of the same flaws in terms of batching incoming events. If you're looking for a good livereload server, I can look into releasing this as a library.
