### ISSUE TITLE
Avoid loading all docs in memory at the same time

### ISSUE THREAD

**Issue by djuarezg** [mkdocs/mkdocs#2065]
When building a site with a lot of documents, the memory usage skyrockets. This is an issue as when using automation this can involve OOM process killing.

Is there any way to avoid loading all docs in memory? Kind of doing it in batches?

We are running OOM even with 8Gi...

**Comment by waylan** [comment]
> Is there any way to avoid loading all docs in memory?

No. In fact, this was a recent addition in version 1.0 as many users were requesting features that required this. If we reverted, many things would break. For example, building the nav requires that all pages be read to get all age titles. Therefore, we can't pass the first page to the template until we have finishes reading all pages. That being the case, there is no plan to make such a change. How do other, competing projects deal with this (like Sphinx)?

That said, it might be possible to cache the pages somehow rather than keeping them in memory. I suspect we could keep all the `Page` instances in memory with meta-data, but perhaps cache the `markdown` and `html` attributes which hold the body of the pages. However, I certainly don't have the time to work on such a feature and have no personal need for it myself. However, I would be willing to review a PR.

**Comment by aphive** [comment]
I would strongly recommend using the `mkdocs serve --dirtyreload` option to ease the amount of reloading that needs to happen when developing or making edits to only the pages that are updated.

My experience is that each edit tends to reload the entire site if you do not use this option and my memory spikes when I am working on our internal docs site with tons of pages.

Hopes this helps.

**Comment by pawamoy** [comment]
That's a common issue with Python programs, which allocate lots of memory and do not give it back to the OS even if it goes unused. As mentioned previously, changing that would break many, many projects in the ecosystem. So if we still want to provide a way to achieve that, it would have to be through the plugin system. Since there's nothing actionable right now, this issue was closed. I'm tempted to move it to discussions, but given the very few replies here, it looks like there isn't a lot of interest to work on this.

**Comment by tomchristie** [comment]
*"I'm tempted to move it to discussions ..."*

Aside... Yep discussions are *really* helpful. Pointing contributors towards discussions as a starting point, and only later escalating into issues if required seems like a really decent palicy to me.
