### ISSUE TITLE
Support for SVG favicon

### ISSUE THREAD

**Issue by oxr463** [mkdocs/mkdocs#2079]
I have an `.svg` file in a repository that I would like to use as the favicon.

Here are the two options I had in mind:

1. Generate `.ico` from `.svg` via `mkdocs build`; implemented as a separate plugin.

2. Allow `.svg` extension in addition to `.ico` for themes.

See: https://en.wikipedia.org/wiki/Favicon#How_to_use

**Comment by waylan** [comment]
You can implement either of those with no changes to MkDocs.

> 1. Generate `.ico` from `.svg` via `mkdocs build`; implemented as a separate plugin.

You can create a plugin which does this.

> 2. Allow `.svg` extension in addition to `.ico` for themes.

You can [customize a theme][1] so that the template points to an `.svg` file rather than an `.ico` file.

Bug then, you seem to already know all that. Was there a question here? A feature request? A bug report?

[1]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

**Comment by oxr463** [comment]
> But then, you seem to already know all that. Was there a question here? A feature request? A bug report?

Perhaps I should clarify. By themes, I meant the default themes included with mkdocs; specifically, the readthedocs theme. But I guess I can just extend it as you say.
