### ISSUE TITLE
control the text in sidebar

### ISSUE THREAD

**Issue by Alcampopiano** [mkdocs/mkdocs#2085]
Hello,

First of all, thank you very much for this incredible tool!

My question is this:

In my documentation I have a list of functions with their function signatures. For example, here is the first function in the docs:

![fs](https://user-images.githubusercontent.com/4624246/80647147-fff26280-8a3b-11ea-9ba3-de24a2ee76c5.png)

Since I link to this function in the docs, the entire function signature will show up in the sidebar as follows:

![sb](https://user-images.githubusercontent.com/4624246/80647228-21534e80-8a3c-11ea-8e65-da36c06f72b9.png)

I apologize if this is a silly question, but is there a way to link to that function but only show the function name in the sidebar (not the function signature)?

Any nudge in the right direction would be much appreciated.

**Comment by waylan** [comment]
MkDocs uses the `toc` Markdown extension to generate the Table of Contents (TOC). That extension includes support for [custom labels][1] if you are also using the [attr_list][2] extension.

First, to enable the `attr_list` extension add the extension to the [markdown_extensions][3] config setting in your `mkdocs.yml` file:

```yaml
markdown_extensions:
    attr_list
```

Then, in you Markdown you can use the `data-toc-label` attribute to define the text used in the TOC:

```markdown
# function_name(foo, bar) { data-toc-label="function_name" }
```

Then `function_name` will be used in the TOC rather than the full text `function_name(foo, bar)`.

[1]: https://python-markdown.github.io/extensions/toc/#custom-labels
[2]: https://python-markdown.github.io/extensions/attr_list/
[3]: https://www.mkdocs.org/user-guide/configuration/#markdown_extensions

**Comment by Alcampopiano** [comment]
That is simply incredible. Thank you very much!
