### ISSUE TITLE
Google Analytics documenation

### ISSUE THREAD

**Issue by TheJaredWilcurt** [mkdocs/mkdocs#2101]
I'm trying to switch from Docsify, where, at runtime I would have this JS run:

```js
let googleAnalyticsId = 'UA-1234567-50'; // default to dev
if (window.location.host.includes('apps-test.example.com')) {
  googleAnalyticsId = 'UA-1234567-59';
} else if (window.location.host.includes('apps.example.com')) {
  googleAnalyticsId = 'UA-1234567-51';
}
window.$docsify = {
  ga: googleAnalyticsId,
};
```

The documentation is vague and does not explain what the code is, or how it works:
```yaml
google_analytics: ['UA-36723568-3', 'mkdocs.org']
```
* https://www.mkdocs.org/user-guide/configuration/#google_analytics

Is the second argument a name? Something to match against before analytics are enabled? How would you go about defining which ID to use based on the current environment (dev/test/prod/local)? Can you hook into this on page load (since GA is just running in JS anyway) so the above logic can stay in the JavaScript?

Can the docs be updated to have these answers?

It looks like there is some theme or template file for analytics, but there is no example.

* * *

For others looking for a work around to the lack of proper documentation, here's the best thing I could come up with:

1. In the root of your project create a `theme` folder
1. Put `footer.html` in the folder
1. Edit it and add this:

```html
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

let googleAnalyticsId = 'UA-1234567-50'; // default to dev
if (window.location.host.includes('apps-test.example.com')) {
  googleAnalyticsId = 'UA-1234567-59';
} else if (window.location.host.includes('apps.example.com')) {
  googleAnalyticsId = 'UA-1234567-51';
}

ga('create', googleAnalyticsId, 'auto');
ga('send', 'pageview');
</script>
```

**Comment by waylan** [comment]
In the `mkdocs` theme, those config options are used in the template here: 

https://github.com/mkdocs/mkdocs/blob/a4eb4eb42be5b2b7f401f51baf8c0863f54fe63d/mkdocs/themes/mkdocs/base.html#L44-L56

And for the `readthedocs` theme:

https://github.com/mkdocs/mkdocs/blob/a4eb4eb42be5b2b7f401f51baf8c0863f54fe63d/mkdocs/themes/readthedocs/base.html#L55-L76

Of course, for third-party themes, things may be different.

Regarding the two values, they are the two values passed to `ga(create...)`. Of course, back when the documentation was written, it corresponded with Google documentation and was clear. Google has since changed their documentation which makes ours less clear.

In any event, a PR with suggested changes is always welcome.

**Comment by sorenwacker** [comment]
The documentation says something like:

```
extra:
  analytics:
    provider: google
    propertyl: UA-...
```

Which one is correct now??

**Comment by tomchristie** [comment]
Let's close this off in favor of https://github.com/mkdocs/mkdocs/issues/3630

Including GA should be supported as a template override, not a config option.
Any docs here should probably be generic - we can leave it to analytics providers to deal with their own "here's how to include us on your website" docs.
