### ISSUE TITLE
PymdownxDeprecationWarning

### ISSUE THREAD

**Issue by rxlxrxsx** [mkdocs/mkdocs#2134]
Whenever I enter mkdocs serve I always get this warning. Do you guys know any solution for this one?

![image](https://user-images.githubusercontent.com/64377055/86001662-c80a9a00-ba41-11ea-8bd9-74c9f6620aed.png)

**Comment by facelessuser** [comment]
It's because you are using the tab feature for tabbed code blocks in the pymdown-extensions' SuperFences. You should migrate over to using the general purpose Tabbed extension, which is in pymdown-extensions as well. This is because the SuperFences tab feature will be removed at some time in the future as Tabbed is meant to replace that functionality. It's all in the warning. It has nothing to do with MkDocs except for the fact you are using the library in your MkDocs environment.

**Comment by rxlxrxsx** [comment]
Sorry, but how do I migrate it over the Tabbed extension?

**Comment by facelessuser** [comment]
Checkout Pymdown Extensions' documentation. It's covered there, so I won't spend time exhaustively going over it here: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#tabbed-fences. It talks about the change, and it also links to the new extension's documentation: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/.

If you have specific questions after reading the docs, you can ask questions over at the pymdown-extensions repo. MkDocs is not really the appropriate place.
