### ISSUE TITLE
possible to use mkdocs as python module without the CLI 

### ISSUE THREAD

**Issue by moshir** [mkdocs/mkdocs#2186]
Hi ,

is it possible to use mkdocs as a python package and generate documentations from python script, eg.:
```python
import mkdocs
mkdocs.build(root="mkdocs.yml")
```

**Comment by gaborantal** [comment]
HI!

You can try it yourself. I tried and no, you cannot use it as a package. There is nothing about it in the documentation, and also you cannot use it in the way you mentioned.

**Comment by waylan** [comment]
MkDocs is not designed with this use case in mind. However, it should not be impossible to do. You would basically need to replicate the code in [`__main__.py`][1]. Note that you need to load the config yourself, and then pass that to the `build` function. `build` won't do that for you. And then each of the CLI commands corresponds to a file in `mkdocs/commands/` (build, serve, etc). With a little spelunking through the code, you should get something that works.

A word of warning though. As we don;t document the internal structure of the code, we don't guarantee backward compatibility. Any future release could completely break your code.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/__main__.py#L152

**Comment by matanox** [comment]
I believe it makes sense to add that use case, otherwise documentation building cannot be tested as part of a live project requiring automated tests, where the documentation building is part of the project. This applies to any programming project actually, if it bundles its own documentation within its own repo (or even as a separate one that is automatically being tested for correctness)
