### ISSUE TITLE
Proper way to test python code in docstrings?

### ISSUE THREAD

**Issue by arogozhnikov** [mkdocs/mkdocs#2216]
I use python built-in `doctest` module, which works with the following format
```python
>>> 1 + 2
3
```

To make this work with mkdocs, I need to coonvert this example into

````
```python
>>> 1 + 2
3

```
````

note that besides triple quotes I need to add an empty line.

I need some more readable  alternative that still works with mkdocs and allows testing of docstrings

**Comment by waylan** [comment]
Markdown parsing is handled by [Python-Markdown][1]. Please take all Markdown parsing issues there.

[1]: https://github.com/Python-Markdown/markdown

**Comment by arogozhnikov** [comment]
Python markdown maintainers quite expectably consider this not to be out of their scope:
https://github.com/Python-Markdown/markdown/issues/1060

I agree with them, since they do not claim any support for docstrings (mkdocs scenario). 


Documentation package is  *expected* to have a recipe for docstring testing; sphinx supports default doctests - but mkdocs neither supports existing solutions nor suggests an alternative.

**Comment by facelessuser** [comment]
These things should be implemented by MkDocs plugins or Python Markdown plugins, whichever is most relevant.

**Comment by arogozhnikov** [comment]
@facelessuser can you recommend such a plugin? I've came through the list, but didn't find one

**Comment by facelessuser** [comment]
I'm not saying if one exists or not, I'm only stating that is why the plugin APIs exist. MkDocs provides an API so things like this can be created. Python Markdown has its own API that allows for the Markdown syntax to be extended.

MkDocs more focuses on site templating and building. All other site-specific needs can be implemented via plugins. That is the intent. If the desired feature doesn't exist in currently available plugins, one can maybe contribute to an existing plugin to bring about the desired feature, or create a new plugin that implements the desired feature.

MkDocs itself doesn't really provide a list of plugins to do X, Y, and Z, but there is a [community wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins) that outlines a number of available plugins. Additionally, Python Markdown also has a [wiki](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions) of some available 3rd party extensions. If what you are looking for isn't found there, and a google search doesn't turn up any results, it may be a good project to look into.

**Comment by waylan** [comment]
First I want to start by stating that I did not understand what this issue was requesting as first. Sorry about that, but now that I do understand I went back and reread the initial post and I do not see how I could have understood from that alone. Perhaps if you had been more clear we would not have sent you on a wild goose chase.

And now to the issue at hand. If I understand correctly, you want to auto-generate some documentation based upon your doctests. That is not something MkDocs offers out-of-the-box. In fact, we don't provide any method for autogenerating any content. It is expected that everything will be created manually as prose in Markdown documents. Of course, many of our users have created systems which autogenerate content. In the past it was all vai private scripts they wrote to generate Markdown that MkDocs would then understand.

However, after the introduction of the Plugin API, various users have created plugins which generate documents from code comments. Many are listed in the wiki under the [API documentation building][1] section. However, I'm not aware of any that only pull in doc tests. 

If one doesn't exist, you will need to build your own or find someone to build it for you. Personally, I don't have the need for such a feature or the time to build it.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building
