### ISSUE TITLE
mkdocs build pages

### ISSUE THREAD

**Issue by HUGHNew** [mkdocs/mkdocs#2241]
the **hyperlink** for offline/local serve is OK (which is focused on Markdown file)
But when using the index.html (built by mkdocs build) the hyperlink is only a reference to the directory not an index.html that I directly want
Through after an afternoon's effort, I used the diff way solve this problem **with [bash and C++](https://gitee.com/HughNew/Shell/tree/master/Basic/MkDocs)**
So is it allright for you to develop the feature?

**Comment by waylan** [comment]
Sounds like you need to turn off the [use_direcotry_urls][1] config option.

[1]: https://www.mkdocs.org/user-guide/configuration/#preview-controls

**Comment by waylan** [comment]
I understand people who don't understand how servers work (or what an index page is) not understanding why things are broken or what the `use_directory_urls` does. But it seems clear you understand the issue. So, I'm curious, why would you spend an afternoon developing a workaround in bash and C++ but not bother to look through the configuration options?

I ask because we seem to receive a lot of requests for features we already support, albeit not by default. What can we do different to get people to look at the options?

**Comment by HUGHNew** [comment]
thanks for the remind
However, I only had seen the [Home Page](https://www.mkdocs.org/) and thought that's all

**Comment by HUGHNew** [comment]
Thanks for your explanation on it

**Comment by flywire** [comment]
> What can we do different to get people to look at the options?

> I only had seen the [Home Page](https://www.mkdocs.org/) and thought that's all

Interesting, scary. Fundamental fail of whole interface concept.
