### ISSUE TITLE
Relative link inconsistency...

### ISSUE THREAD

**Issue by lovettchris** [mkdocs/mkdocs#2249]
I have a simple mkdocs website here [XmlNotepad](https://microsoft.github.io/XmlNotepad/) with source code here [github](https://github.com/Microsoft/xmlnotepad)

You can see the markdown for the home page at [index.md](https://raw.githubusercontent.com/microsoft/XmlNotepad/master/docs/index.md) is able to use a relative link to "help/overview" and that works, but when the [overview](https://raw.githubusercontent.com/microsoft/XmlNotepad/master/docs/help/overview.md) page wants to also use relative links to the "sibling" pages in the same folder as "overview.md" it has to use "../" on each link in order for things to work.

Note that I get the same problem whether index.md uses the relative link "help/overview.md" or "help/overview/".

This inconsistency is creating much pain as I try and integrate an "xmldoc" generator with a much bigger site I'm working on where the generation of magic ".." links is a real headache for the tool to deal with.

Can someone explain this to me?

**Comment by waylan** [comment]
This is documented in detail [here][1]. When you use the correct form of the link, MkDocs will reformat it on build so that it properly points to the built page. Specifically, use a relative link from the current page to the target page in the source files (using `path/to/file.md`). We assume you already no how how relative links work.

I could provide you with the correct form your your cited example; however, without any knowledge of your file structure, I can't be sure. You can find an example [here][2].

[1]: https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links
[2]: https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-images-and-media

**Comment by clovett** [comment]
I see thanks, I'm moving from Jekyll world where you never use the ".md" file extension in relative links.  Note you can see my file structure here under my docs folder in [https://github.com/Microsoft/xmlnotepad](https://github.com/Microsoft/xmlnotepad).

But moving to full file names with .md extension solved my problem, thanks.

**Comment by flywire** [comment]
Duplicate issue - used the [alternate-link plugin](https://github.com/mkdocs/mkdocs/issues/2262#issuecomment-749826218)
