### ISSUE TITLE
Standard Internal links not Supported

### ISSUE THREAD

**Issue by flywire** [mkdocs/mkdocs#2262]
**Issue:** [Reference Markdown Internal Linking](https://daringfireball.net/projects/markdown/syntax#link) not supported.

**Description:** MkDocs supports internal linking:

> [Linking to pages](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages)
When linking between pages in the documentation you can simply use the regular Markdown linking syntax, including the relative path to the Markdown document you wish to link to.
>
> Please see the `[project license](license.md)` for further details.

It does not support the reference implementation as described in the [MkDocs documentation](https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links):

> [Internal links](https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links)
MkDocs allows you to interlink your documentation by using regular Markdown [links](https://daringfireball.net/projects/markdown/syntax#link).

Which [links](https://daringfireball.net/projects/markdown/syntax#link) to:

>> If you’re referring to a local resource on the same server, you can use relative paths:
>>
>> See my `[About](/about/)` page for details. 

Which doesn't work. I'd expect `[About](about)` to work too (ie `.md` is implied).

**Comment by flywire** [comment]
> [I am a Markdown purist of sorts](https://github.com/mkdocs/mkdocs/issues/248#issuecomment-126123517)

... so it should work out of the box

-----

> [link handling is implemented as a Markdown extension](https://github.com/mkdocs/mkdocs/issues/248#issuecomment-395962875
)

https://github.com/cmitu/mkdocs-altlink-plugin#usage
> `[My Page](source-page.md)` can be written as `[My Page](source-page)`

**Comment by waylan** [comment]
This is intentional behavior and will not be changed.

If you want to manually structure your links so that they point to the built URLs, then you can, but then they won't point to the source file in your text editor or when browsing the source on GitHub (or whichever repo host you are using). However, if you use links as we require (relative link to the source page), it will point to the correct document in your text editor and on GitHub, and MkDocs will properly convert it to point to the built page.

By the way, in your example, when a server receives a request for `about/`, it returns the file at `/about/index.html`, not `/about.md`. Of course, if you have `use_direcotry_urls` set to `True` (the default), then `about.md` will be built at `about/index.html` so the link to `about.md` is properly converted to `about/`.

**Comment by flywire** [comment]
> [Python-Markdown is **almost** completely compliant with the reference implementation, although there are a few very minor differences.](https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown)

The scope of this markdown variant is clearer now. Fortunately the [alternate-link plugin](https://github.com/cmitu/mkdocs-altlink-plugin) provides this functionality.

Thanks for highlighting by not using a `*.md` reference there is no link directly to the page in the source repository for editing. I didn't exactly use `about/` as an example but I'm using the `use_directory_urls: false` setting and it is working well.
