### ISSUE TITLE
Exclude file from search index

### ISSUE THREAD

**Issue by Stanzilla** [mkdocs/mkdocs#2288]
Hey there, I'm currently looking for a way to exclude file from the search index, is there a native way or plugin to do this?

**Comment by waylan** [comment]
No, there is to provision for excluding pages from search. I don't think it ever occurred to me that anyone would ever want this option.

**Comment by Stanzilla** [comment]
Interesting! Yeah I guess it might be some kind of fringe case but I have some auto generated pages that are kind of a sitemap that I would want to remove from search because of duplicated results.

**Comment by waylan** [comment]
Ah, a sitemap. I'm assuming you are manually creating your sitemap in Markdown. Perhaps I should have said that there is no way to exclude Markdown content. However, all non-Markdown content is always excluded from search. You could define a template which generates a sitemap from the `nav` config option and that would not be included in search.

You can see an example [here][1], which uses [this template][2]. In that case, the template is provided by the theme, but you could provide your own template using either the [theme.static_templates][3] option or the [extra_templates][4] option regardless of which theme you are using. So long as your template inherits from the theme, it will match the design of the theme. See [Customizing a Theme][5] for details, especially the section on [overriding template blocks][6].

[1]: https://python-markdown.github.io/sitemap.html
[2]: https://github.com/waylan/mkdocs-nature/blob/master/nature/sitemap.html
[3]: https://www.mkdocs.org/user-guide/configuration/#static_templates
[4]: https://www.mkdocs.org/user-guide/configuration/#extra_templates
[5]: https://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme
[6]: https://www.mkdocs.org/user-guide/styling-your-docs/#overriding-template-blocks

**Comment by Stanzilla** [comment]
Ah, interesting. I'm using https://github.com/Stanzilla/mkdocs-plugin-tags to generate my "sitemap".

**Comment by waylan** [comment]
Interesting. I hadn't been aware of that plugin. However, personally I would have expected it to use an `extra_template` (or `theme.static_template`) rather than a Markdown based template. That said, you could recreate the entire thing without any plugin at all. Just point `extra_template` to your template file and in the template loop over either the [nav.pages][1] or [pages][2] variable. You can then access the tags for each [Page][3] via `page.meta.tags`. Of course, the one thing you won't get is a global list of tags. That is the one advantage of using a plugin. I would suggest asking the developers of the plugin to add an option to use a non-Markdown based template.

[1]: https://www.mkdocs.org/user-guide/custom-themes/#navpages
[2]: https://www.mkdocs.org/user-guide/custom-themes/#pages
[3]: https://www.mkdocs.org/user-guide/custom-themes/#page

**Comment by Stanzilla** [comment]
Yeah sadly that plugin seems pretty dead, I tried making it used a non-markdown based template but did not have any luck so far, any pointers?

**Comment by waylan** [comment]
> I guess I'm back to asking if you would be open to adding a native way to this

I won't say no, but it is not a priority for me. About all I I can give to this is the time to review a PR.

**Comment by Stanzilla** [comment]
Okay any pointers on where to start looking in the mkdocs source?

**Comment by waylan** [comment]
I imagine this would be a new config option on the search plugin, which would be defined here: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/contrib/search/__init__.py

**Comment by Stanzilla** [comment]
@waylan awesome, thank you. so would you say comparing config values to the context is a good idea then?

```python
    def on_page_context(self, context, **kwargs):
        "Add page to search index."
        if not context["page"].url in self.config['ignore']:
            self.search_index.add_entry_from_context(context['page'])
```

**Comment by Stanzilla** [comment]
I was able to solve this by using https://github.com/chrieke/mkdocs-exclude-search
