### ISSUE TITLE
other programming language support

### ISSUE THREAD

**Issue by flashpixx** [mkdocs/mkdocs#2310]
Hello, is there any tutorial how to add new programming languages for parsing it with mkdocs?
I would like to add support, if I have a little bit time, for Java and Go, my idea is to use Antlr grammars (https://github.com/antlr/grammars-v4) for do the parsing. 

Can you give me a little bit help for starting / get familiar with this topic?

**Comment by waylan** [comment]
Are you referring to syntax highlighting or autogenerated documentation? Either way, the existing support is provided by third party libraries, not by MkDocs directly. Sorry, but I'm confuse about what this request is about.

**Comment by flashpixx** [comment]
IMHO it is autogenerated Ddocumentation, because for Python I can extract all code documentation automatically by referencing the Python package with:

```
::: mypackage.mymodule
``` 

within the Markdown code, I would like to get a similar support for other programming languages

**Comment by waylan** [comment]
There is a [whole list of plugins][1] which offer support for autogenerating documentation. Some of them may even support other languages. See the individual plugins for details.

To be clear, autogenerating documentation is not a core feature of MkDocs and I expect it never will be. This will always be provided by third party plugins.

[1]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building

**Comment by flashpixx** [comment]
Thank you, so in my case I have to create an plugin which can deal with other language structure for extracting the data and support it as a module for mkdocs

**Comment by waylan** [comment]
That is certainly one option. Another is to provide a backend for the [mkdocstrings][1] plugin (included in the previously links list), which claims to offer support for backends to multiple languages (although it only supports Python so far). That said, I have no personal knowledge of the project and cannot personally endorse it. I only know what is said about in in the previously linked wiki page listing.

Another option might be to create a Markdown extension which does something similar. In fact, that is the approach taken by [MkAutoDoc][2] which was also listed in the previously linked list (and is the only one of those listed which I have any personal familiarity with).

Whichever route you take, yes you will need to create something which extracts the relevant information from the source code and then presents it to some existing API.

[2]: https://github.com/tomchristie/mkautodoc
[1]: https://github.com/pawamoy/mkdocstrings

**Comment by flashpixx** [comment]
I think the second approach is nice, because in Golang it is common to use GoDoc and this pain text markdown style, for Java, C or C++ most JavaDoc style is used and I think it is easiert to convert this to Markdown

**Comment by pawamoy** [comment]
Hi @flashpixx, @waylan 

> ::: mypackage.mymodule

As @waylan pointed, this is allowed by a Markdown extension (not built into MkDocs), and this is exactly what the mkdocstrings and mkautodoc respective extensions do. Do you happen to use one of them @flashpixx?

As for bringing support for other languages, I strongly recommend writing a handler for mkdocstrings (though I'm biased of course since I created mkdocstrings) instead of writing your own Markdown extension from scratch. There are multiple benefits to writing an mkdocstrings handler:

- the Markdown extension is already written!
- you can cross-link to objects, from Python to Go, or Go to Java, or to arbitrary headings, or even sub-headings appearing in Markdown docstrings
- our extension will shift your Markdown docstrings headings according to their parent level
- native way of passing configuration options to your handler
- mkdocstrings is tested (unit tests and regression workflow)
- more niceties like logging, styling, theming, etc.

Also, this has been done already: we now have a Crystal handler! See https://mkdocstrings.github.io/crystal/

In fact, I think GoDoc or godocjson would integrate easily in a handler. I even already opened the feature request here: https://github.com/mkdocstrings/mkdocstrings/issues/93 :smile: Feel free to continue the discussion there!

**Comment by flashpixx** [comment]
Thanks this sounds very well, I will take a look into
