### ISSUE TITLE
markdown code block not highlighted for sh and lua

### ISSUE THREAD

**Issue by laoshaw** [mkdocs/mkdocs#2312]
while most of the code block are highlighted correctly, sh and lua are not, both are shown as plaintext.

**Comment by waylan** [comment]
Which theme are you using? Or are you using a Markdown extension to do your syntax highlighting?

I ask because in either case a third party library is used. Any issues with highlighting should be addressed with this libraries.

The `mkdocs` and `readthedocs` themes use the [highlightjs][1] Javascript Library. Note that the language name is `bash`, not `sh`as used by the lib. However `lua` is a supported language and listed among the "common" languages.

However, if you are using a different theme, then you may be using a different tool which may have different support.

[1]: https://highlightjs.org

**Comment by laoshaw** [comment]
I'm using `readthedocs` theme and no extension was used as shown below. 

```
       site_name: mkdocs
        docs_dir: docs
        theme:
            name: readthedocs
```

shell scripts can now be highlighted, still anything with lua is shown as plaintext, other filetypes work as expected.

**Comment by laoshaw** [comment]
I confirm this is a highlight.js issue, below code will display plaintext, I reported this to highlight.js:

```
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test Lua highlighting</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
<pre><code class="language-lua">
array = {}

for i = 1, 3 do
    array[i] = {}

    for j = 1, 4 do
        array[i][j] = i * j
    end
end

-- accessing the array
for i = 1, 3 do
    for j = 1, 4 do
        print(array[i][j])
    end
end
</code></pre>
</body>
</html>
```

**Comment by laoshaw** [comment]
Tested with highlight 9.18.1 and Lua is highlighted correctly, it seems mkdocs is using a highlight.js version(9.12.0) that can not deal with lua syntax highlighting.

**Comment by laoshaw** [comment]
updated highlightjs for mkdocs and readthedocs theme at base.html to 10.5.0 and now lua works

**Comment by waylan** [comment]
A PR is welcome.
