### ISSUE TITLE
Improve serve performance with on demand page rendering

### ISSUE THREAD

**Issue by jlisee** [mkdocs/mkdocs#2384]
**Proposal**

When using `mkdocs serve --dirtyreload` we switch from pre-generating pages to on demand generation only.   This would be done by inserting another web handler in the stack to catch a possible 404 and if there is a match markdown file invoking the `build` command on the desired page.

Essentially there is no need for a user to wait several minutes for MkDocs to generate hundreds of pages they will never view. Especially when you can see that with the `--dirtyreload` method we can generate a single page fast enough for interactive use.

I would be willing to work on a patch in the next few weeks or months if this is something you would consider.  We could also hide this behind a flag like `--render-on-demand` or `--lazy-rendering`

**Details**

MkDocs is a great project, really makes it easy to go from nice markdown to easy to consume docs.  The main issue we are having is the startup time of `mkdocs serve --dirtyreload` is about 3 minutes.  Now you can write markdown using a light weight viewer, but we take advantage of many of the great [pymdown-extensions](https://facelessuser.github.io/pymdown-extensions/), which complicates that.

Before settling on this approach I thought of two others::

 - Leave the temporary site directory around between runs and rely on the mtime comparison.  This could leave around stale pages or content.
 - Use multiprocess.pool to parallelize initial page generation. This could effect how plugins work and would require more code restructing.

Addition content on my build time:

 - Duration - about 180 seconds (3 minutes)
 - Markdown File Count - about 1250 hand written pages (my goal would be to double or triple this in the next year)
 - MkDocs version - 1.1.2
 - OS - Ubuntu 18.04
 - CPU - 2nd Generation Intel Xeon Scalable (Cascade Lake)
 - Cores - 8 vCPUs
 - Environment - AWS EC2

Also when I run with master and leverage all the hard work by @oprypin I see a 25% reduction in build time which is awesome, but not enough for interactive use.

**Comment by oprypin** [comment]
> when I run with master and leverage all the hard work by @oprypin I see a 25% reduction in build time

Sigh, funny choice of words. You are not leveraging **all** the hard work, because [some of it](https://github.com/oprypin/mkdocs/compare/relpath) was [simply thrown out](https://github.com/mkdocs/mkdocs/pull/2272#issuecomment-813093547).

I would be very curious for you to try out [that branch](https://github.com/oprypin/mkdocs/tree/relpath); with that number of pages you'd probably get another 25% improvement on top.

I would also be curious to see your site and maybe find some quick wins for its build time :D

---

On the topic itself, it is a very interesting idea.
I have also been looking into performance improvements for interactive use, but never even considered skipping the initial build. I was looking more into caching -- basically just a better `dirtyreload`.

Good that the hackery to intercept 404 errors is already mostly done:
<https://github.com/mkdocs/mkdocs/blob/6a694fd87ba5576a51c4060ab111a5cec3a9fbaf/mkdocs/commands/serve.py#L42>

The somewhat unfortunate thing is that upon building each page, I think invoking the whole plugin machinery from scratch (like is being done now even for dirty builds) is unavoidable. That is because plugins (for example) can save some data in a site-wide step, then rely on it in a per-page step.
Well, the plugins are already having a hard time as is. E.g. `search` seems to present only the page that happened to be rebuilt.
But this is just a side thought, I don't think it's a fundamental problem for anything.

**Comment by waylan** [comment]
As MkDocs is a *Static Site Generator* I feel like handling server requests and returning responses is straying too far. Personally, if I was a potential new user looking for a new solution and I saw MkDocs supported this feature, I would look elsewhere. For that matter, I was dragged kicking and screaming into adding dirtyreload to begin with. As @oprypin points out, search is broken. As the documentation notes, the nav can be broken. Why would anyone want to use it?, but I digress (the issue has been discussed at length elsewhere).

To be clear, I do understand the reason why you requested the feature, but every decision is a compromise and your use case is not a high priority for MkDocs in general.

> catch a possible 404 and if there is a match markdown file invoking the build command on the desired page

Interesting idea. However, I very much dislike it for MkDocs. I begrudgingly adding the existing error handler to the server only because the upstream project refused to add it themselves. I still maintain that it should be a feature of the upstream server and not something that MkDocs needs to concern itself with. Adding even more functionality to the handler is not something I am interested in at all. Perhaps some motivated people could create a new project and provide a server specifically designed for static site generators. If it was maintained as a third-party project and better met our needs, I would be happy to swap our Python-Livereload for it.

> but we take advantage of many of the great pymdown-extensions, 

I'm not sure how this matters. We don't even read unmodified pages in `dirty` mode. Which means we don't parse any Markdown for them. That being the case, only one page is rebuilt at a time on a reload. Which means your proposal isn't going to change anything. It will still take as long to build one page.

Perhaps time would be better spent skipping more of the build process in the current solution. Of course, that will mean even more of the site will be broken (including many plugins). But I suppose, if you are only iterating on the Markdown in one page, you don't care about the nav, search, or any other pages. Personally, its not for me, but to each his own...

**Comment by oprypin** [comment]
> > but we take advantage of many of the great pymdown-extensions,
>
> I'm not sure how this matters.

The point was that the Markdown flavor becomes non-standard, so they can't use an external editor for preview.

**Comment by waylan** [comment]
> > > but we take advantage of many of the great pymdown-extensions,
> > 
> > 
> > I'm not sure how this matters.
> 
> The point was that the Markdown flavor becomes non-standard, so they can't use an external editor for preview.

Yeah, okay. Point taken. But my point still stands.

**Comment by jlisee** [comment]
Thanks for responding so quickly and sheparding a project like this for many years.  I definitely understand the desire to maintain coherence.  There is just a tension between "simple end to end system" and "quickly iterate on small part of large body of work".

**Is is still a static site generator?**

So I think it still is!  The POC builds static pages, and snoops on requests instead of responding directly.  Instead of building 1000+ pages upfront it takes a [lazy loading](https://en.wikipedia.org/wiki/Lazy_loading) approach and waits until it sees a request for a page before generating the content on disk and serving as normal.

I even fixed it so the navigation bar works properly with this approach and in `dirtyreload` mode :).

**Better livereload instead?**

So this would be an approach.  It would require MkDocs itself to have an API that lets you build a single page accurately.  I could definitely land just that part of my change if you happy with those changes.  This could in theory enable using MkDocs as a `pandoc` replacement for single pages, where a user could just call `mkdocs build -f mkdocs.yml page/being/edited.md` to see a single page.

**Additional Context** (why the scale, why we don't need search)

I missed one additional bit of context - I am trying to improve a monorepo documentation system for hundreds of developers.  So the use case is a bit different than a system focused on single project documentation systems.  This also means we don't use the built in search system, we use an external whole company search engine that also indexes all of our issues, internal documents, email, chat **and** MkDocs.

**The code**

I should have legal approval within a week to share the POC branch, but here is my commit message:

>serve on-demand-build mode, for lazy page generation
> 
>When developing large sites you can now tell the development server to
>only generate the pages on disk as you want to view, instead of
>generating them all up front.  This can save many minute on initial
>start for sites with large amounts of content (1000+ pages).
>
>Example usage:                                                                                                                                                                                                                                                                                                                                                          
>
>    mkdocs serve --dirtyreload --on-demand-build  
>
>Approach:
>
> - Add an `--on-demand-build` flag to the `serve` CLI command
> - Change the `build()` internal command to be able to work on a
>   single file                                                                                                                                                                                                                                                                                                                                                             
> - Create a method that goes from URL -> Markdown path                                                                                                                                                                                                                                                                                                         
> - Update the livereload `WebHandler` to use that the above method and                                                                                                                                                                                                                                                                                                           
>   `build(the/missing.md)` to generates pages as you visit
> - Use unfortunate `inspect.stack` hack to work around livereload bug
>   and insure only edited pages get rebuilt

**Comment by oprypin** [comment]
Thinking more in this direction, I think I have a great idea.

MkDocs, rather than needing to skip pages, would just change the *order* in which they're built, starting with recently demanded pages. Importantly, pages would become viewable as soon as they're built. And indeed, a 404 event could *on the fly* move that page to the front of the queue.

The large tail of pages that are still building would obviously still be an issue, but to solve that, MkDocs would interrupt the current build as soon as it encounters a need to rebuild.
And yes, this partly neglects `on_post_build`, but few plugins rely on it.

This also brings me to the topic of livereload. Obviously the current used implementation is nowhere close to being able to satisfy these use cases. However, despite what the complicated codebases of *livereload* and *httpwatcher* may lead you to believe, implementing live reload can be done very compactly. https://github.com/mkdocs/mkdocs/pull/2385 presents a near-drop-in replacement that just works better and uses only the stdlib server.
I can propose it as an external library, but with this issue in mind I think it would greatly benefit from being tightly integrated into MkDocs. Which, given the small code size, should not cause worry. In fact, the workarounds for adapting livereload might outgrow that whole implementation.

The big reasons to follow this approach would be that *nothing* is sacrificed there. The site build retains full correctness. There are no workarounds; and it wouldn't need to be hidden behind even more flags.

Well, regardless of this overall change, I'll still be pursuing the replacement of livereload, as it resolves some long-standing issues and workarounds.

**Comment by oprypin** [comment]
Um I think the main idea from my previous message isn't actually doable just like that. It is because pages aren't fully built one by one, but rather first all Markdown of all pages is converted, and then all templates for all pages are finalized. [As seen on my shiny new diagram...](https://github.com/mkdocs/mkdocs/discussions/2386) I had been aware of this but forgot when writing that message.

There isn't anything that can be done to change that kind of flow, it'd break most plugins. If one still attempted to do the closest thing to that idea, they'd have to render all pages' Markdown first anyway, and that takes up roughly half of all the site's build time, so not very helpful.
