### ISSUE TITLE
MkDocs crash from Github action - python:3.9.5-alpine - TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by nvuillam** [mkdocs/mkdocs#2469]
Doc generation was working fine, and suddently a few days ago, mkdocs build did not work anymore, triggering the following error message.

I build from a [docker image](https://github.com/nvuillam/mega-linter/blob/master/Dockerfile) based on python:3.9.5-alpine, from a [Github action workflow](https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/auto-update-linters.yml)

Are there some leads to solve this issue ?

Thanks !

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/mkdocs-1.2.1-py3.9.egg/mkdocs/__main__.py", line 81, in <module>
    theme_choices = utils.get_theme_names()
  File "/usr/local/lib/python3.9/site-packages/mkdocs-1.2.1-py3.9.egg/mkdocs/utils/__init__.py", line 338, in get_theme_names
    return get_themes().keys()
  File "/usr/local/lib/python3.9/site-packages/mkdocs-1.2.1-py3.9.egg/mkdocs/utils/__init__.py", line 314, in get_themes
    eps = set(importlib_metadata.entry_points(group='mkdocs.themes'))
TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Comment by mondeja** [comment]
It seems that [snakefmt](https://github.com/snakemake/snakefmt/blob/master/pyproject.toml) dependency is installing `importlib_metadata==1.7.0`, which doesn't support `group` argument. Mkdocs currently depends on `importlib_metadata > 3.10`. Seeing your dockerfile, you're installing `snakefmt` with `pip3` and `megalinters/setup.py` with `python` (depending on `mkdocs-material` -> `mkdocs` -> `importlib_metadata==4.5.0`), so if these binaries are placed at different locations, [you could be installing the dependencies in different environments](https://stackoverflow.com/a/57155119/9167585).

Maybe using `python -m pip` instead of `pip3` would be the solution.

**Comment by oprypin** [comment]
Thanks @mondeja, I confirm that finding

**Comment by nvuillam** [comment]
thanks !
