### ISSUE TITLE
Better document interlinking.

### ISSUE THREAD

**Issue by tomchristie** [mkdocs/mkdocs#248]
Currently we only support direct links to other documents.
We ought to support a richer style of interlinking that makes it easy to link to particular sections.
This _could_ involve some kind of index, but would probably prefer if that was handled automatically.

The sort of thing I was originally think for this is:

```
See the [Parsers](ref:) documentation.
```

Creates a link to the section named 'Parsers'.

```
See the [Parsers documentation](ref:Parsers).
```

Creates a link to the section named 'Parsers'.

We could then just generate the index based on heading names, and raise errors if an interlink does not match.

**Comment by d0ugal** [comment]
<ericholscher> I would at least recommend trying to implement it in a generic way, similar to the commonmark spec
<ericholscher> having yet another markdown flavor makes me full of sadness
<ericholscher> but pushing forward a spec of generic inline directives is really useful and moves the world to a better place
<ericholscher> http://talk.commonmark.org/t/generic-directives-plugins-syntax/444

**Comment by waylan** [comment]
I have two things to say about this:

1. What's wrong with the existing solution (as @fedelibre pointed out)? `[link to section](file.md#section)` works just fine.

2. If some sort of "reference" feature/directive was added, then each section in the entire site would need to be unique. People already have difficulty keeping all sections in a single page unique. See point number 1.

**Comment by robodude666** [comment]
@waylan I'm personally in favor of this approach:

 * It allows the author to move a section of their documentation to another file without having to worry about breaking any links.
 * It'll make it easy to link to a specific section w/o it being a ## header or using \<a\> html tags, for example linking to a specific paragraph.
 * Currently you need to figure out how a specific header would get sluggified, which can cause invalid hyperlinks if you guessed wrong.
 * Sometimes the slug generated by `toc` or `headerid` is not very author-friendly to type out every time they want to link to it: `how-the-parser-is-determined`. Kind of a PITA to link to `parsers.md#how-the-parser-is-determined`. I'd rather link to `ref:Parsers_determined`

It'll also make it easier once extensions :wink: are supported for developers to create API-documenting extensions that use refs instead of having to remember relative paths of API md files.

**Comment by waylan** [comment]
@robodude666 if you want to define your own slugs, this is already possible with the [Attribute Lists][1] Extension. And I know that you are already aware that you can [define your own slugify function][2].

I think [Markua's crosslinks][3] are interesting. Markua is a Markdown superset designed for writing full length books (novels?). Yet, their syntax for internal linking is fully available with the Attribute List Extension and `#section` type links. While Markua's [meta  data][4] offers a lot of extra stuff (Chapters, Dedication, Epigraph, Table of Contents (or ToC), Foreword, Preface, etc.) that is not needed outside of "Books", much of the basic stuff is still doable. Want to link to a specific paragraph? Attach an attribute list to that paragraph assigning it an id. And Markua is the latest in a growing number of Markdown implementations which support this syntax. As an aside, Attribute Lists are a superset of the much older PHP Markdown Extra [Header Attributes][5] (attribute lists for headers only), which have been copied by even more Markdown implementations.

So I'm opposed to creating a new format when we already have one that works. We already occasionally see people filing bug reports because some feature works differently in the Markdown implementation used by some other tool (their editor's preview function, a competing tool they are migrating to/from, etc). The "reference" macro is not very "markdown-like" IMO and multiple implementations already support an alternate solution which works today with no changes to MkDocs.

I suppose all that was a long-winded way of saying I am a Markdown purist of sorts and am generally opposed to any unique additions to the Syntax. Regardless, what path MkDocs takes is not up to me. However, the farther is drifts from Markdown (and CommonMark is not Markdown IMO) the less interested I am in using it.

[1]: https://pythonhosted.org/Markdown/extensions/attr_list.html
[2]: https://github.com/mkdocs/mkdocs/issues/212#issuecomment-115404162
[3]: https://leanpub.com/markua/read#crosslinks
[4]: https://leanpub.com/markua/read#metadata
[5]: https://michelf.ca/projects/php-markdown/extra/#spe-attr

**Comment by robodude666** [comment]
> * Currently you need to figure out how a specific header would get sluggified, which can cause invalid hyperlinks if you guessed wrong.

@waylan That comment was more in regards to contributors needing to know exactly how your slug function works.

**Comment by devnewton** [comment]
An alternative would be to implements a move command to automatically update references:

`mkdocs move fruits.md#apple aple.md`

`mkdocs move aple.md apple.md`

`mkdocs move apple.md fruits/`

**Comment by nikramakrishnan** [comment]
What about within HTML tags? For example, if I have a custom HTML table, and a link in it, I need to use <a href...> instead of standard markdown link. These links are not handled by MkDocs natively.

**Comment by waylan** [comment]
@nikramakrishnan the link handling is implemented as a Markdown extension. Markdown ignores raw HTML, passing it through unaltered. If we were to implement your suggestion, we would first need to add on an HTML parser. That would be a whole other feature in addition to what is being discussed here.

**Comment by pauloue** [comment]
I wrote a [plugin](https://github.com/pauloue/mkdocs-autoreflinks-plugin/blob/master/autoreflinks/plugin.py) that links bracketed headings like `[My heading]`, similar to Pandoc's `implicit_header_references` [extension](https://pandoc.org/MANUAL.html#extension-implicit_header_references), except that it works across pages.

**Comment by oprypin** [comment]
This functionality will be reserved only to plugins.

The one I personally recommend is https://github.com/mkdocstrings/autorefs
