### ISSUE TITLE
Links to sites using MkDocs

### ISSUE THREAD

**Issue by cpach** [mkdocs/mkdocs#2700]
Have you considered adding some links from the web pages to open source projects that use MkDocs?

That could be very useful for prospective new users who would like to get a feeling for how MkDocs works in practice.

**Comment by CannonballSkippy** [comment]
I was just looking for the same.

**Comment by squidfunk** [comment]
Here are some using Material for MkDocs 😉
https://github.com/squidfunk/mkdocs-material#trusted-by-

**Comment by pawamoy** [comment]
There's this wiki page: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Users

**Comment by squidfunk** [comment]
Actually, I think that MkDocs could do some more marketing, so adding some prominent users to the website or README wouldn't hurt. It would show that the software is mature and trusted by many users and megacorps, which can be an important sign for new adopters. IMHO the GitHub wiki, albeit advertised on the homepage, is more or less within a blind spot. For example, Docusaurus has much better marketing materials: https://docusaurus.io/showcase

**Comment by timvink** [comment]
> Actually, I think that MkDocs could do some more marketing.

I agree. That also extends to plugins. We now have a large amount of high quality, mature plugnis, but on the [plugins page](https://www.mkdocs.org/user-guide/configuration/#plugins) there is no link to the [wiki](https://www.mkdocs.org/dev-guide/plugins/). And there is no mention of plugins in the [getting started](https://www.mkdocs.org/user-guide/configuration/) guide.

I might be biased, but I think mkdocs + mkdocs-material + a subset of plugins is what makes the mkdocs ecosystem so powerful. I would love for more people to discover it :)

**Comment by squidfunk** [comment]
Yup, absolutely. The plugin system is just awesome. The docs for Material for MkDocs include guidance for some plugins and Markdown extensions, mostly those that are (and need to be) natively supported. Listing them on the MkDocs page and having a curated list would lower entry barriers.

Also, and this is my personal opinion, redoing (or changing) the default theme to something more friendly might be something to consider. Of course, I'm biased because I do so much work on Material or MkDocs, which, for some users, is the only thing they know about MkDocs. However, from the eyes of a first-time user, the default theme might be off-putting as it looks pretty dated and has only very rudimentary capabilities.

Just my 2 cents.

**Comment by timvink** [comment]
> redoing (or changing) the default theme to something more friendly might be something to consider

I say mkdocs should use `mkdocs-material` as default theme, drop `mkdocs` theme and separate out `readthedocs` theme into a different repo. `mkdocs` has ~660k downloads/month ([source](https://pepy.tech/project/mkdocs)) on PyPi, and `mkdocs-material` ~690k download/month ([source](https://pepy.tech/project/mkdocs-material)). That's impossible of course because `mkdocs-material` depends on `mkdocs`, but I think it's a reasonable assumption the majority of mkdocs users use `mkdocs-material` anyway.

It's likely this has probably been discussed before.. what are the considerations by the maintenance team?

**Comment by tomchristie** [comment]
Okay, so the closest we currently have to this is...

* https://github.com/squidfunk/mkdocs-material#trusted-by-
* https://github.com/mkdocs/mkdocs/wiki/MkDocs-Users
* https://github.com/mkdocs/catalog

Wrt. @timvink's comment - should consider a complete theme refresh at some point, yes.
This could either involve...

* Having no default at all, and *always* force an installable theme.
* Having material as a default.
* Putting in the work for a new fresh default.

Open to further conversations around this.
