### ISSUE TITLE
Custom subpath isn't applied for `livereload` feature

### ISSUE THREAD

**Issue by robertaistleitner** [mkdocs/mkdocs#2739]
If using a `site_url` including a subpath for development (we're using it behind a proxy), this isn't applied when loading the `livereload.js` script, causing the whole auto-reload feature to break.

I expect it to be loaded from `https://test.local/my/subpath/js/livereload.js` if using `https://test.local/my/subpath` as `site_url`.

**Comment by oprypin** [comment]
Are you sure you're using the latest version of MkDocs, which is 1.2.3?

**Comment by robertaistleitner** [comment]
Yes I am.

**Comment by oprypin** [comment]
Ah yes, I see what you mean now.
Regardless of what subpaths are applied for everything else, just *livereload.js* is always loaded from the root.
It is indeed somewhat of a problem.

* https://github.com/mkdocs/mkdocs/blob/82fcf3115ab9c2e1c9fa8d41a90b0ae3eb307080/mkdocs/livereload/__init__.py#L247
* https://github.com/mkdocs/mkdocs/blob/82fcf3115ab9c2e1c9fa8d41a90b0ae3eb307080/mkdocs/livereload/__init__.py#L195

But that's not all -- then the script itself will also use this other custom endpoint

* https://github.com/mkdocs/mkdocs/blob/dc35569ade5e101c8c48b78bbed8708dd0b1b49a/mkdocs/livereload/livereload.js#L15
* https://github.com/mkdocs/mkdocs/blob/82fcf3115ab9c2e1c9fa8d41a90b0ae3eb307080/mkdocs/livereload/__init__.py#L179

So the problem is slightly complex to solve. Actually, can JS even refer to a path relative to it?
Seems not - https://stackoverflow.com/a/2188506/241039
So actually I don't even have an immediate solution in mind

**Comment by robertaistleitner** [comment]
I changed the behaviour of injecting the javascript to make it easy to fix it, please see my pull request.
