### ISSUE TITLE
MkDocs html-escapes quotes in inline-code blocks

### ISSUE THREAD

**Issue by constb** [mkdocs/mkdocs#2758]
Hi

In inline code blocks like that:
```
`"value"`
```

double quotes get rendered to look like this:
```
&#34;value&#34;
```

This issue persists in mkdocs and readthedocs themes. I can't find any relevant issues or documentation recipes to work around that.

**Comment by facelessuser** [comment]
This could be caused by some plugin you have enabled. By default, this is not how the Markdown parser renders inline code blocks.

```py
import markdown

MD = """
`"value"`
"""

html = markdown.markdown(MD)

print(HTML)
```

```console
➜  example.py
<p><code>"value"</code></p>
```

What I cannot tell from your issue is whether this is what the raw source looks like, or whether this how it is rendered in the browser. If the source looks like what you described, and it is properly wrapped in a code block, this is fine and no cause for concern, though that isn't what Python Markdown does by default as noted above.

You'll often see that the block code highlighter will use HTML entities though, but it will translate them to `&quot;`, but this is not a cause for concern and is perfectly acceptable.

````py
import markdown

MD = """
```
"value"
```
"""

html = markdown.markdown(MD, extensions=["fenced_code"])

print(html)
````

```console
➜  python3 bug.py
<pre><code>&quot;value&quot;
</code></pre>
```

There is nothing inherently wrong if the raw source is translating double quotes to `&#34;` as it is just an alias for `&quot;`, but if you are seeing this, it is most likely some extension or plugin, not Python Markdown or MkDocs directly.

**Comment by constb** [comment]
@facelessuser Oh, now I see. You're absolutely right, I'm including into the site an md-file compiled from protobuf description by protoc-gen-doc. And it's already escaped when MkDocs parser starts to do its work… Didn't expect that… :)
