### ISSUE TITLE
Unable to register extra javascript as type="module"

### ISSUE THREAD

**Issue by ericis** [mkdocs/mkdocs#2850]
I have extra JavaScript that should be registered with `type="module"` in the `<script ...` tag.

**Comment by 6830920** [comment]
me too

**Comment by tsraza** [comment]
you can override the jinja template to include `type="module"`, for example here: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/mkdocs/base.html#L199

or here: https://github.com/squidfunk/mkdocs-material/blob/master/material/base.html#L221

**Comment by tsraza** [comment]
Heads up for anyone using scripts to render pages with mkdocs-material. Do not enable the `navigation.instant` feature or else the script will not fire on page navigation.

**Comment by squidfunk** [comment]
What @tsraza mentions is partially correct – yes, scripts added via `extra_javascripts` are not executed on navigation, which is by design, as the theme can not know whether it is safe to execute a custom script again and again. However, if you wish to execute a script on navigation, just wrap your code in the following block.

``` js
document$.subscribe(() => {
   // this executes after each navigation
})
```

Note that this only applies to [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), which is the only theme supporting instant navigation.
