### ISSUE TITLE
Enable users to change log level

### ISSUE THREAD

**Issue by AngryMane** [mkdocs/mkdocs#2876]
# Proposal/Request
I want to add an option for users to set their own logging level like below. 

```
mkdocs -l WARN build 
```

We can implement this like [this](https://github.com/mkdocs/mkdocs/compare/master...AngryMane:mkdocs:feature/log-level?expand=1). 

# Background
See [this repo](https://github.com/AngryMane/sample-mkdocs-prj). 
This mkdocs project includes many files that should not be registered to nav, and one broken link,

If you build this repo by `mkdocs build`, then you see the following log.

```
$ mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/username/work/git/sample-mkdocs-prj/site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - file_not_registered_to_nav.md
              - file_not_registered_to_nav10.md
              - file_not_registered_to_nav11.md
              - file_not_registered_to_nav12.md
              - file_not_registered_to_nav13.md
              - file_not_registered_to_nav14.md
              - file_not_registered_to_nav15.md
              - file_not_registered_to_nav16.md
              - file_not_registered_to_nav17.md
              - file_not_registered_to_nav18.md
              - file_not_registered_to_nav19.md
              - file_not_registered_to_nav2.md
              - file_not_registered_to_nav20.md
              - file_not_registered_to_nav3.md
              - file_not_registered_to_nav4.md
              - file_not_registered_to_nav5.md
              - file_not_registered_to_nav6.md
              - file_not_registered_to_nav7.md
              - file_not_registered_to_nav8.md
              - file_not_registered_to_nav9.md
WARNING  -  Documentation file 'index.md' contains a link to 'broken_link.md' which is not found in the documentation files.
INFO     -  Documentation built in 0.06 seconds
```

As you can see, too many INFO logs are crowding out the WARNING logs, so you can't notice broken link. 
(My private mkdocs project has 100 or more files that should not be registered to nav....)
On the other hand, `mkdocs -q build` prints nothing, so you can't notice the broken link.
But if user can select log level WARN, user can get the following log and immediately notice broken link! 

```
$ mkdocs -l WARN build
WARNING  -  Documentation file 'index.md' contains a link to 'broken_link.md' which is not found in the documentation files.
```

# My environment 
* Platform: WSL(Ubuntu 20.04 LTS) on Windows 11
* MkDocs version: 1.3.0

**Comment by llwt** [comment]
It would be nice to have this, or maybe have a way to silence deprecation warnings introduced in https://github.com/mkdocs/mkdocs/pull/2907

As of v.1.4, it's really difficult to see warnings now.

![Screenshot 2023-01-25 at 11 16 49](https://user-images.githubusercontent.com/1036428/214537462-32f7bc88-cc52-451a-9dd7-8e16de724242.png)

**Comment by kamilkrzyskow** [comment]
I've been dealing with similar issues developing / debugging hooks and plugins. I wanted the ability to limit the output to specific loggers / scopes. Therefore I've developed a hook, which allows to influence the log output.
ChatGPT helped me in figuring out how to access the root logger, since all of the StackOverflow examples focused on some bizarre `logging.basicConfig`, and practically none mentioned anything about the StreamHandler, which in fact is the base for the solution.

Check it out and let me hear your feedback: [log_manager.zip](https://github.com/mkdocs/mkdocs/files/11298378/log_manager.zip)

I'm not really planning to maintain it, but I might listen to 1 or 2 suggestions if you think they should be included, and you don't know how to add them.

---

In your `mkdocs.yml` file add the `hooks` with a path to the `log_manager.py` relative to `mkdocs.yml`:
```yml
hooks:
    - overrides/.hooks/log_manager.py
```

Then inside the `log_manager.py` you can change the settings to customize the output:
@AngryMane 
`exclude_levels = ["DEBUG", "INFO"]` to exclude both `DEBUG` and `INFO`, it would only show `WARNING`, `ERROR` etc.
@llwt 
`omit_deprecation_warnings = True` it would omit messages starting with "DeprecationWarning"

**Comment by mkusz** [comment]
@AngryMane take a look at the plugin I have developed just for better logging support in MkDocs. It allows you to:
- chose a log level
- have an abbility to log to the console and to the file at the same time
- filtering of logs from plugins
- console log output reformat (with support for code links from where given message is send, works in PyCharm, didn't test elswere)
- automatic cleanup of previous log files
Documentation can be found [here](https://mkusz.github.io/mkdocs-publisher/setup/development/pub-debugger/#console-logging). I'm open to suggestion how to make it better.

**Comment by oprypin** [comment]
In the meantime, the particular messages mentioned in the original post are now individually configurable via https://www.mkdocs.org/user-guide/configuration/#validation

**Comment by AngryMane** [comment]
I think the feature @oprypin  said is enogh, so I'll close this issue. 
Thank you for all your advices!
