### ISSUE TITLE
Mypy error: Missing type parameters for generic type "BasePlugin"

### ISSUE THREAD

**Issue by mondeja** [mkdocs/mkdocs#3071]
I'm getting the next mypy error trying to annotate a plugin:

```
Missing type parameters for generic type "BasePlugin"
```

My configuration is:

```toml
strict = true
python_version = "3.7"
```

Happens at the line which declares the plugin:

```python
from mkdocs.plugins import BasePlugin

class MyFooPlugin(BasePlugin):  # <----
   ...
```

I suppose that happens because Mkdocs has not strict mypy support. Is planned for the public API at least?

**Comment by oprypin** [comment]
Supporting mypy strict will not be seen as a valid request because it includes flags that shouldn't even exist.

https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-untyped-calls

Like, ... what is the deal with this flag? If you set it in your project then suddenly libraries that you use are supposed to have type annotations everywhere, otherwise you report a bug on them?

If you want to prevent untyped defs then just check for them in your own project with the other flag

---

*And* it is a moving target.

> Note: the exact list of flags enabled by running --strict may change over time.

**Comment by mondeja** [comment]
> Supporting mypy strict will not be seen as a valid request because it includes flags that shouldn't even exist.

In future versions I though, but you can support at least X.Y.Z version.

Meh...

**Comment by mondeja** [comment]
`allow_untyped_calls = true` does nothing for this, I suppose that I should test each mypy option to see WTF is happening.

**Comment by mondeja** [comment]
So to make an strict plugin for mypy v0.991 you can use this configuration:

```toml
python_version = '3.7'
strict = true
allow_untyped_calls = true
allow_any_generics = true
```

**Comment by oprypin** [comment]
I think actually you'd need to handle the error with `any_generics` on your side.

`class MyFooPlugin(BasePlugin):`

Now needs to be following the new style
https://www.mkdocs.org/dev-guide/plugins/#config_scheme

```python
class MyPluginConfig(mkdocs.config.base.Config):
    ...

class MyPlugin(mkdocs.plugins.BasePlugin[MyPluginConfig]):
    ...
```
-because BasePlugin *is* now a generic class.

but I would still also advise against this rule.
