### ISSUE TITLE
Customizing themes to avoid GDPR issues

### ISSUE THREAD

**Issue by joho1968** [mkdocs/mkdocs#3090]
I guess this is more of a heads-up for those who don't know (or have chosen to ignore the issue), but resources like webfonts, CDN JS, CDN CSS, and so on doesn't float very well with GDPR.

I ran into this when I started to put up a sample site to showcase MkDocs at Öppet Moln, a website in Swedish talking about open source alternatives. So I'm doing custom versions of some standard themes and download the required .js and .css files from their CDN and serving them locally.

For the built-in/default/pre-packaged themes, it may be a good idea to do this (serve locally), to make it more GDPR friendly out of the box.

**Comment by pawamoy** [comment]
You could use the [privacy plugin of Material for MkDocs](https://squidfunk.github.io/mkdocs-material/plugins/privacy/). It's part of Material for MkDocs but can be used as a standalone plugin (you don't have to use the theme itself), and should be theme agnostic :slightly_smiling_face: If you have any issue with it, please raise an issue at https://github.com/squidfunk/mkdocs-material!

```
pip install mkdocs-material
```

``` yaml
plugins:
  - material/privacy
```

We'll close this as out of scope for MkDocs core since it's proven to be achievable through plugins.
