### ISSUE TITLE
Images should be displayed inline (rather than as block).

### ISSUE THREAD

**Issue by twiecki** [mkdocs/mkdocs#310]
Just published this:
http://quantopian.github.io/zipline/

On the front-page the badges are displayed differently then on:
https://github.com/quantopian/zipline

(e.g. no line breaks)

**Comment by d0ugal** [comment]
Updated the title of this to represent the issue you described. Looks like this is the culprit - https://github.com/tomchristie/mkdocs/blob/0.11.1/mkdocs/themes/mkdocs/css/base.css#L26

I'm not sure if that is safe to change or if we are likely to run into issues.

**Comment by samhatfield** [comment]
When you insert two images one after the other immediately,

     ![Description 1](image1.png)
     ![Description 2](image2.png)

they're grouped within the same `<p>`,

    <p>
        <img alt="Description 1" src="./image1.png">
        <img alt="Description 2" src="./image2.png">
    </p>

However, putting a blank line between the two images in the markdown file causes them to be inserted into separate `<p>`s. Since `<p>`s are `display: block;`, perhaps we can set images to be `display: inline;` in the place you mention d0ugal? Then, if you want a series of inline images, you just need to insert them one after the other, with no line breaks, and if you want a `display: block;` image then just make sure it has blank lines above and below.

**Comment by twiecki** [comment]
:+1:
