### ISSUE TITLE
Rendering of 404.md page doesn't work for invalid sub-path

### ISSUE THREAD

**Issue by Stwissel** [mkdocs/mkdocs#3140]
Problem: when creating a 404.md file, invalid urls containing a path fail to load CSS/JS due to relative path for JS/CSS.

- Works: https://stwissel.github.io/mknotfound/nothere
- Doesn't work: https://stwissel.github.io/mknotfound/not/here

I created a a [minimal reproducer](https://github.com/Stwissel/mknotfound) (rendered [here](https://github.com/Stwissel/mknotfound)).

Potential solution: use absolute path entries based on mkocs.yml site_url (minus the host)?

Initially [reported here](https://github.com/squidfunk/mkdocs-material/discussions/5153)

**Comment by Stwissel** [comment]
Digged a little deeper....

- When  404.md is present, the 404.html gets ignored and the main.html is used for rendering the 404.md page.
- putting `template : 404.html` in the 404.md front-matter restores the use of 404.html

**Comment by Stwissel** [comment]
matching discussion: https://github.com/mkdocs/mkdocs/discussions/3153

**Comment by kamilkrzyskow** [comment]
I assumed this is a custom 404 page, but there might be someone writing a documentation page about the 404 HTTP code and then call it `404.md` with the `use_directory_urls: false` setting...

So even though, it's a rather edge-case, I would consider this issue to be valid, so you don't have to close it if you decide to opt-out of this approach 👌.

**Comment by Varjoissa** [comment]
Somehow I see multiple issues, even in the past, where this 404 page is giving trouble due to broken relative references.
I have a setup where I create branch-related sub-sites, so its slightly more complex.
So I tried injecting the site_url variable into mkdocs.yaml from the pipeline with yq, and multiple other solutions.
It still gave the same issue. It showed the content of the html page, but all content (js/css etc) were broken.

But i found a solution that is in line with what you want; a specific 404 page.
I add the 404 page under my /docs folder.

Since Im using the `material` theme, I add the override folder, with a 404.html page. (See https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks)

Then, instead of using all the templating code, I just add raw html attributes to redirect to the 404.md under my docs folder:

`<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url=https://base.url/404">
<script type="text/javascript">
    window.location.href = "https://base.url/404"
</script>
<title>Page Redirection</title>
`

Replace `base.url` with the site url and path to your site page.
Replace `404` with the complete path to your 404 page in the docs folder.

This works, since it doesn't need any relative references.
If you have changing base_paths, make sure you provide that upon runtime or add an custom script block that determines that from client side.

**Comment by pawamoy** [comment]
> I assumed this is a custom 404 page, but there might be someone writing a documentation page about the 404 HTTP code and then call it 404.md with the use_directory_urls: false setting...

I'm not sure to understand. I tried adding a 404.md page to existing docs, in the top-level navigation, and it works fine: the page is rendered, can be accessed at `<site_url>/404/`, and actual 404 pages return the contents rendered from the 404.html template.

> Somehow I see multiple issues, even in the past, where this 404 page is giving trouble due to broken relative references.

Since the 404.html template is used to render contents that can appear at any sub-URL, links to assets must be absolute. If there was an issue with absolute links before, it's probably fixed by the upcoming MkDocs v1.6.

@Varjoissa also provided a solution for implementing the 404 page as a Markdown page.

Closing as completed, please comment further or open new issues if you still experience problems!
