### ISSUE TITLE
If no title is provided in the mkdocs.yml use the title in the markdown file

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#316]
As per the title, this came up in #308 but it's something I've wanted for a while.

**Comment by ePirat** [comment]
Is this is done, have a look at #318, as this will be even more an issue then.

**Comment by tomchristie** [comment]
I still don't entirely get the motivation for not wanting to maintain a properly listed index. It's essentially zero amount of *real* work/overhead.

**Comment by d0ugal** [comment]
A few reasons.

- Keep the config file as minimal as possible (and remove duplication).
- Reduce steps for new users, list all the pages vs list all the pages and add/check the titles (for example, when I done DRF, this would have really helped).
- We already guess the title based on the filename, we should try somewhere more useful first.

**Comment by tomchristie** [comment]
This one...

> We already guess the title based on the filename, we should try somewhere more useful first.

Is a very good reason, agreed.

**Comment by jniggemann** [comment]
Which one would take precedence over the other? I suggest the following:
title from mkdocs.yml > title from md file (meta) > title from filename (if all else fails)

Would we want to implement that in `_generate_site_navigation()`[here](https://github.com/tomchristie/mkdocs/blob/master/mkdocs/nav.py#L212)?

**Comment by tomchristie** [comment]
Either this:

    mkdocs.yml > md title > filename title

Or this:

    mkdocs.yml > md title > [no title]

Could be okay.

**Comment by d0ugal** [comment]
I'd vote for:

    mkdocs.yml > md title > filename title

That looks like a reasonable place to do it, I've not had a look at this yet.

**Comment by danbohea** [comment]
+1 for this, it would save on a fair bit of duplication. I'd also prefer as above:

```
mkdocs.yml > md title > filename title
```

**Comment by ugocupcic** [comment]
From a discussion with @d0ugal on irc:

**Comment by d0ugal** [comment]
@ugocupcic I think your paste didn't work :)

**Comment by d0ugal** [comment]
@ugocupcic we should also rename `filename_to_title` to something like `file_to_title` as it wont just be looking at the filename anymore.

**Comment by waylan** [comment]
Hmm, so if @ugocupcic's suggestion is implemented, for any file which does not have a title defined in the config, that file is parsed by Markdown twice then? That seems like a bad idea to me.

I have seen other projects address this issue by creating an instance of a class for each document (let's say a class named `Page`). That class holds the raw markdown, the meta-data, and the HTML as attributes on the class. Once all Page instances are created, you also have the navigation data and can then built the site by looping through Page instances (rather than the file system). This results in only one pass through the file system and only one pass through Markdown for each page. The downside is that the entire site it held in memory (in both Markdown and HTML) at once, which could be a problem for large sites.

This is why I have recommended at various times in the past that the TOC extension not be used. If a separate meta-data script was used, then it could extract the meta-data without parsing the Markdown when building the Nav and still be used when parsing the actual Markdown. Something like [docdata][1] might be a good way to go (or your own simple in-house solution).

[1]: https://github.com/waylan/docdata

**Comment by d0ugal** [comment]
@waylan I agree to all of the above, the only issue is the time required to do a large refactor like this.

It is only my todolist and I've been pondering how best to work towards something like this incrementally.

**Comment by ugocupcic** [comment]
https://github.com/mkdocs/mkdocs/pull/472

**Comment by d0ugal** [comment]
Reverted the change in #500 as it wasn't working, my bad for not testing it fully.

**Comment by tkirill** [comment]
Nice feature!  Really willing to have it released.  I see there was an attempt #497 a month ago but it isn't work well.  Does somebody work on it at the moment or it's free?  If it is free I would be glad to work on it.

**Comment by d0ugal** [comment]
I don't believe anyone is working on it at the moment. It is surprisingly tricky, the context needed for loading and finding the title isn't available at the section of code where we generate the navigation. I plan on doing a larger refactor that will make it much easier, but I am not sure when I will have time to do this.

**Comment by facelessuser** [comment]
I don't know if this is desired by anyone else, but I think supported YAML frontmatter to define variables per page would be great. In this way, you could capture title, and maybe the rest, you would just push to the extra, or custom template variables.  You can quickly grab the data without parsing the entire file as well and just parse it as YAML.

I've often wanted this so If I had a page that required a heavy JS lib that isn't required on other pages (maybe I am rendering some flow charts, using mathjax or whatever), I could add a custom template variable to my page that my theme would use to conditionally load that resource.

I don't know, maybe that is more complex than mkdocs wants to go, but I figure if you are going to go ahead and analyze each page for title meta data, why not do that **and** any other custom user stuff as well, in that regard it wouldn't be much more complex than trying to find the title.  And since all info here, except maybe `title` would be custom data, you wouldn't even have to validate it, just pass it through to the custom variables and let it override whatever.

I would even be interested in putting in work myself  (pull request) to make something like this happen, but again, I am not sure if it aligns with what mkdocs wants yet.

**Comment by facelessuser** [comment]
I was just thinking that maybe this will be possible in #206 making this something mkdocs wouldn't even need to consider.  I guess it would just depend on when and where the hooks are available and whether the plugins will have access to the config structure.  If so, I think this could all be handled by a plugin which would make this suggestion unnecessary for mkdocs to implement directly unless it just wanted to.

**Comment by waylan** [comment]
Right, that sort of thing could be addressed with a Plugin API. First, I think the nav stuff needs to be refactored so that instead of a bunch of nav objects, we have a bunch of page objects. Each Page object could then hold the meta-data in addition to what the nav object now holds and perhaps even the markdown source (there could be a memory concern there although I believe some competing products do it this way so maybe not \[^1] ). With all that data, a pre-build hook in a Plugin could extract data from the Page object and add it to the context and all sorts of cool stuff would be possible.

Either way however, I think the title should always be added to the context from the meta-data if it is defined in the meta-data. Unfortunately, even that is not possible without the data from the as-yet unimplemented Page object. The reverted patch actually rendered the Markdown document twice (once to get the meta-data throwing out the HTML and a second time to render the HTML). Obviously, a better solution should be employed.

One method would be to have the front matter be YAML (as mentioned). Of course as the config file is YAML, this makes sense (and is probably my preference as well). Users are already using the format. Consistency would be nice. The concern is whether there would be a backward compatibility issue with existing documents. Requiring users to go through every individual document to manually edit them all would be bad (note [here][1] how many MkDocs project are reportedly hosted by RTD -- that is a lot of documents for users to update). And yes, I realize that given the currently limited usefulness of the meta-data, most documents probably don't have much of an issue. I'm just being thorough. On the other hand, if such a change will be made, it should be made ASAP.

I would be inclined to either use my recently put together special purpose tool for such a thing: [docdata][2] or I would rip out the parts needed and add those directly to MkdDocs (for less dependencies). In fact, I expressly give permission for the later if anyone wants to do the work. Of course, it would be appreciated if an acknowledgement was included in the file.

\[^1]: By "competing products" I mean static site generators, not specifically documentation generators. Off hand, I don't recall which projects do it this way, but I have certainly seen it done (perhaps even Pelican does this). I don't think Sphinx does, but I'm note sure about that as Sphinx is really just a collection of docutils plugins and docutils internals are kind-of a black box to me. (And, yes, I realize GitHub doesn't support footnote syntax, but I don't care; I'm using it anyway.)

[1]: https://github.com/rtfd/readthedocs.org/pull/1305#issuecomment-107232177
[2]: https://github.com/waylan/docdata

**Comment by facelessuser** [comment]
I agree, a refactoring of nav is going to hav to come first.  Glad I am not the only one interested in this.

**Comment by marcelstoer** [comment]
> First, I think the nav stuff needs to be refactored

**Comment by d0ugal** [comment]
> > First, I think the nav stuff needs to be refactored

> Was that done in the meantime i.e. those who were interested in at taking a stab at this feature should come forward again?

Nah, I started but never completed. There hasn't been enough volunteer time available (from me, or anyone else) to push this forward.

**Comment by memeplex** [comment]
If you assume that the first toc entry is the title when there is no title meta, then you will be banning a header structure that reserves headers for sections and set no meta. I don't think there is a safe way to do this without adding an option to let the user signal his intention (at the global level) regarding: first header is title vs first header is section. There are many related issues reported, all revolving around the inability to tell the title appart from the document section outline in a reliable way, so title may be part of the templates, the toc may be consistently build across themes and there is no ambiguity regarding what is the title.

**Comment by memeplex** [comment]
What do you think about my suggestion at https://github.com/mkdocs/mkdocs/issues/1008#issuecomment-237526931. It provides a way to programmaticaly alter the model according to user intentions that are hard to communicate without complicating the configuration file.

**Comment by waylan** [comment]
Hmm, just noticed we implemented this in #1180 (see [nav.pyL213][1]) and never closed this issue. Although, I don't believe it has been documented. I've relabeled this so we don't forget to document the behavior.

[1]: [1]: https://github.com/mkdocs/mkdocs/pull/1180/files#diff-da047634a950ee20ecb0da37c95e229dR213

**Comment by memeplex** [comment]
I don't think this is completely solved. The nav doesn't load page source and both title and meta are tied to the page being loaded in order to resolve properly. Since now title and meta have their own fast parsers (for top header and metadata section in md source), wouldn't it be desirable to load the page, extract title and meta, then unload it unless it's the current page and thus should be rendered? This would remove all inconsistencies regarding the availability and contents of title and meta in different contexts without having to keep the entire site in memory. Indeed, I thought that was the goal of adding the metadata parser.

Related to this: https://github.com/mkdocs/mkdocs/issues/1476

**Comment by waylan** [comment]
This is all being addressed with the [Pages refactor](https://github.com/mkdocs/mkdocs/projects/2), which is happening regardless of this issue. That refactor will address the order in which things happen so any inconsistencies in determining page titles will be addresses by default.
