### ISSUE TITLE
Feature request: in mkdocs.yml, allow pointing nav items to anchor sections in pages

### ISSUE THREAD

**Issue by pereorga** [mkdocs/mkdocs#3223]
It would be great if navigation items set in `mkdocs.yml` pointing to Markdown pages can include anchors, so the browser scrolls to that section automatically.

Related:

- https://github.com/mkdocs/mkdocs/issues/744
- https://github.com/oprypin/mkdocs-literate-nav/issues/24

**Comment by oprypin** [comment]
I thought it works already?

**Comment by oprypin** [comment]
There are just warnings -- it's true, but I'd just like to be clear on what works and what's still an issue

**Comment by oprypin** [comment]
I looked into this, but perhaps this request is conceptually incompatible with MkDocs.

Each page needs to know what its corresponding nav entry is. That is because the displayed nav always highlights the current page. Moreover, the *readthedocs* theme expands the ToC of each page inline in the nav.

So if there are multiple nav entries leading to the same page, all except one of them will necessarily have to be wrong: the user will click on it and instead the menu will jump to a totally different nav entry.

**Comment by pereorga** [comment]
Thanks for looking into this. In our case, we don't have repeated items as of now, but I recognize the point of not being a right fit.

Regarding the warnings / errors on strict mode, should we create an additional issue?

**Comment by pawamoy** [comment]
During a backlog grooming call we decided to close this as out of scope because of the [reasons](https://github.com/mkdocs/mkdocs/issues/3223#issuecomment-1554608505) mentioned by @oprypin. To us this is what the table of contents is for. Feel free to comment further of course :slightly_smiling_face:
