### ISSUE TITLE
The page .. contained a hyperlink to .. which is not listed

### ISSUE THREAD

**Issue by redwards1966** [mkdocs/mkdocs#323]
Just getting started with mkdocs and am hoping to get around this issue. I'd like to generate a static documentation site by specifying only 5 top level pages that point to sub folder index.md files. Each subfolder which represents a 'product' then has many more markdown files that are linked to from the main index.md page in that subfolder or may be interlinked between themselves.

Is there a way to accomplish this with mkdocs without specifying all of the documents in the pages config entry?

**Comment by d0ugal** [comment]
At the moment you can either specify all pages in the mkdocs.yml or none of them (and then all markdown files will be discovered). We don't have a way to do a bit of both.

**Comment by redwards1966** [comment]
Ok, I tried not specifying anything in the pages config entry and I'm still getting the above errror.

**Comment by d0ugal** [comment]
Ah, I see. This is improved in master, but not in the latest release. You can either try the development version or hunt through your docs to find the issue. Sorry about that.

See https://github.com/tomchristie/mkdocs/pull/279

I hope to do a release soon.

**Comment by d0ugal** [comment]
Basically, to explain this a bit more. This happens because we check that all links to markdown files are files in the table of contents (in the mkdocs.yml). However, if you have a broken link then it really isn't helpful, particularly for people that are converting documentation to MkDocs. This has been greatly improved in the development version, it only displays a warning and for it to error like it does now you need to pass a --strict flag.

**Comment by redwards1966** [comment]
I grabbed the dev version but haven't run it yet. The error I'm getting seems to be a bug though because the page that it's linking to does actually exist. I have a page index.md in a sub directory, with a link in it to a page named page1.md. I also have no Pages config option so it should build up all the pages dynamically as you mentioned but still getting the error. Is this perhaps because it's in a sub directory?

**Comment by d0ugal** [comment]
It's possible, I'd probably need to take a look. Is this a public project I can see? There have been some improvements in the path work too, so with some luck it could be fixed too.

**Comment by redwards1966** [comment]
It's not public, just on my local dev. I zipped it up and you can grab it
here, https://dl.dropboxusercontent.com/u/3842763/mktest.zip.

It's just a couple test pages right now.

On Thu, Jan 8, 2015 at 2:33 PM, Dougal Matthews <notifications@github.com>
wrote:

> It's possible, I'd probably need to take a look. Is this a public project
> I can see? There have been some improvements in the path work too, so with
> some luck it could be fixed too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomchristie/mkdocs/issues/323#issuecomment-69235033>.
>



-- 
Regards,

Richard

**Comment by d0ugal** [comment]
Thanks, I'll take a look in a bit. Reopening until I can verify.

**Comment by majkinetor** [comment]
Isn't the whole point of the system not to repeat yourself ? If that is the premise, we should be able to specify TOC within file system not within pages itself. 

Currently, if you put something in the subfolder menu links are useless because of repetition in every link. I suggest an option to generate valid TOC from a file system. That way simply adding the page to the adequate subfolder will produce aesthetically pleasing TOC without any complaining if you want it that way.

**Comment by tomchristie** [comment]
> we should be able to specify TOC within file system not within pages itself.

I can't understand what it is that I seem to be missing here that this comes up repeatedly. Write an index. Everyone. Write an index. It'll take you 0.1% of the time it'll take to write the content. Write an index. You need to so we can determine the layout for the menu bar. Write an index. It's dirt simple. Write an index. It's explicit and obvious. Write an index.

I understand that I'm coming across as a bit of a pig here, but I can't understand why there's this repeated desire to expect the system to magically intuit how we should display and order the documentation when doing so would come at the expense of simple & explicit behavior.

Loves ya folks regardless. :sparkling_heart:

**Comment by d0ugal** [comment]
I agree. Writing the index is fine (my disagreement on the subject was to do with duplicating the title, but that is another issue).

The reason this is still open is that @redwards1966 seems to have found a bug as mentioned here: https://github.com/tomchristie/mkdocs/issues/323#issuecomment-69230286 which is why I reopened it. I completely forgot to investigate tho.

@redwards1966 did you make any progress?

**Comment by tomchristie** [comment]
Yeah, apologies - I was just going off-topic. :p

**Comment by redwards1966** [comment]
@d0ugal No, sorry I haven't made any progress with this.

**Comment by majkinetor** [comment]
@tomchristie, Index is not DRY, that's why. Simple things should be simple.

**Comment by jimporter** [comment]
Writing an index gives you the benefit of being able to specify the title for a folder of pages that's not the same as the folder's name. If I want a collection of pages to go in the "User Guide" grouping, I wouldn't want to name the folder "User Guide"; I'd probably call it `user-guide/` or maybe just `user/`.

In the interests of not having several ways to do the same thing, I think having users write an index is the best way to address this.

**Comment by majkinetor** [comment]
There is nothing wrong with keeping directory names the way you describe, you don't like it and I understand that. Neither way is right or wrong, a matter of opinion.

Which just leads to the fact that both things should be possible. There is nothing wrong of having the several ways to do the same thing since each way is probably useful in specific context.

**Comment by d0ugal** [comment]
There are already several ways to do this. You either specify the full index or no index.

**Comment by d0ugal** [comment]
@redwards1966 I can't reproduce any issues with the zip you linked in https://github.com/mkdocs/mkdocs/issues/323#issuecomment-69237081 - if the problem comes up again, can you open a new issue. Thanks!
