### ISSUE TITLE
Missing pages build the previous page rather than being skipped

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#327]
The output shows a warning and that the page is missing, but we incorrectly re-render the previous page in it's place.

**Comment by samhatfield** [comment]
Hey d0ugal, you might have already fixed it, but have you considered just having it raise a `MkDocsException` [here](https://github.com/tomchristie/mkdocs/blob/master/mkdocs/build.py#L163) instead of logging the error and carrying on? That would get caught in main.py, halting the build. The site directory would still be partially completed mind you.

**Comment by d0ugal** [comment]
@samhatfield thanks - that is where it needs to be fixed, but we should `continue` rather than raising I think. The idea is that we don't want to stop the build if the page doesn't exist, that is quite annoying when you add new pages.
