### ISSUE TITLE
Flag to convert absolute paths on warnings?

### ISSUE THREAD

**Issue by dghubble** [mkdocs/mkdocs#3384]
With the new validation messages in `mkdocs` v1.5, I see warnings about absolute links across a large project. I'd naturally like to fix these links and the warnings in bulk. Is there a recommended way to convert all the various discovered absolute paths warnings? 

`mkdocs` warning output shows that it has a pretty good idea of what the right relative path should be in each case. And the message "it was left as is", makes it sound like there could (later?) be an option to "don't leave as is, fix".

```
Doc file 'guides/foo.md' contains an absolute link '/static/image.png', it was left as is. Did you mean
           '../../static/image.png'?
...
```

Or would you prefer this be left to another tool?

**Comment by oprypin** [comment]
This is impossible to do generally. There may be a tool that tries to guess this and it may even work most of the time, but correctness cannot be guaranteed.

MkDocs looks at these links **already in the HTML tree** and has 0 understanding of which location in the file they originated from or how exactly they were written out. Python-Markdown does not attempt to provide this information for tracing things back.

Furthermore, the links may have even appeared on the fly from any of the plugins and extensions. Maybe it's some alternate way of writing links, or maybe it's an "include" type of plugin meaning that actually the link is written out in a different file.

So yeah, that's why it was made this way - there's no way to make a fixer that works without guessing (sometimes wrongly)

**Comment by oprypin** [comment]
> And the message "it was left as is", makes it sound like there could (later?) be an option to "don't leave as is, fix".

Yes there's some thinking that there could be an option to fix the links, but only on the fly rather than by writing it back into the file.
