### ISSUE TITLE
Adding the same page multiple times results in strange navigation

### ISSUE THREAD

**Issue by johnthagen** [mkdocs/mkdocs#3428]
### Bug description

If the user adds a page twice to their project:

```yaml
nav:
  - index.md
  - Other:
      - other/new.md
      - other/new2.md
  - Other2:
      - other/new.md
      - other/new2.md
```

Then the navigation gets broken in two ways:

1. The title headings are `None`
2. Clicking on the `None` headings does not highlight them, only the "last" in the list.

<img width="521" alt="Screenshot 2023-10-16 at 8 07 33 AM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/7a11ca02-278b-4d74-ae22-943df59803ee">

I'm unsure if this is _supposed_ to be supported, but I think that at a minimum a better error message during `build` could be useful to officially disallow this if it's not supported.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/

### Reproduction

[9.4.6-duplicate-nav.zip](https://github.com/squidfunk/mkdocs-material/files/12916061/9.4.6-duplicate-nav.zip)

### Steps to reproduce

- https://github.com/johnthagen/python-blueprint/tree/material-for-mkdocs-bug-report

1. `poetry install`
2. `nox -s docs_serve`

### Browser

Chrome

### Context

Originally reported at:

- https://github.com/squidfunk/mkdocs-material/issues/6201

Material for Mkdocs author said that this was an upstream issue with MkDocs:

- https://github.com/squidfunk/mkdocs-material/issues/6201#issuecomment-1764379048

**Comment by oprypin** [comment]
* See also: https://github.com/mkdocs/mkdocs/issues/3223

**Comment by rachel-rigdon-sp** [comment]
My team is also experiencing this issue. Is there a resolution?

**Comment by oprypin** [comment]
Yeah I suppose, don't add the same page multiple times?

**Comment by rachel-rigdon-sp** [comment]
> Yeah I suppose, don't add the same page multiple times?

That is a workaround, not a resolution. If it is not technically feasible, then perhaps this issue should be closed to reflect that.

**Comment by tomchristie** [comment]
It's not obvious eg. how "next"/"prev" could possibly work in this context, so it seems like a broken case to me.

My expected optimal behavior here is probably one of...

* Ignore it. Edge cases might do edgy things. C'est la vie. - The *"don't add the same page multiple times"* comment above might be taken as a little flippant, but it's actually sensible advice.
* Raise an error.

Is there a different behavior here that I'm missing, that we should prefer?

**Comment by johnthagen** [comment]
It's been a while since I reported this, but I think raising an error rather than silently producing inconsistent results would be best IMO.

**Comment by trel** [comment]
> Raise an error.

Or at minimum, a warning.  There *could* be a real use case that would be prevented by raising an error.

**Comment by pawamoy** [comment]
A solution is to use [`pymdownx.snippets`](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) to re-use/include the same content in every page. Example:

- create `foo.md`, `bar.md`, `baz.md`
- write real contents in `foo.md`
- write `--8<-- "foo.md"` in `bar.md` and `baz.md` (update path to foo depending on your snippets config, see the extension docs)

@squidfunk let me know that this could cause ranking issue with search engines since the contents of the three pages is duplicated. He suggests the following to bypass it:

- use a custom `canonical` front-matter property in `bar.md` and `baz.md` like:

    ```md
    ---
    canonical: foo.md
    ---
    ```

- use the [`on_page_context`](https://www.mkdocs.org/dev-guide/plugins/#on_page_context) hook to resolve "foo.md" to the right URL using the `Files` collection
- set the `Page.canonical_url` of the bar and baz pages


We consider this use-case to be out of scope for MkDocs core, so we'll recommend the solution above, but we could maybe indeed also add a warning indeed when the same page is referenced more than once in the navigation. However that opens us up to broken builds if some users are already referencing the same page multiple times and fixing the resulting issue their own way :thinking: Then we'll have to add a validation setting to tune down the warning into an info log. That's more work that what we can put into MkDocs right now for a use-case that seems rare enough, so we'll close as out of scope, but feel free to comment further and ask to re-open if you'd like to work on this (adding a warning/validation).
