### ISSUE TITLE
Mkdocs uses grayscale rendering for fonts compared to majority of the sites which use subpixel rendering

### ISSUE THREAD

**Issue by stojan97** [mkdocs/mkdocs#3488]
### Context

**Operating System:** Windows 10
**Font:** Segoe UI
**Static Site Generator 1:** Docusaurus
**Static Site Generator 2:** Mkdocs (any mkdocs theme)
**Browser:** Google Chrome, Microsoft Edge (so far I tested only on these browsers)

### Bug description

I'm coming from Docusaurus and trying to switch to Material Mkdocs for my docs and notes, but the fonts and overall rendering of the text looked a bit **blurry**.

I went into analyzing and inspect the fonts into more detail, and it seems that for any web page from Material Mkdocs, the SSG uses **grayscale rendering** as opposed to **subpixel rendering (when you zoom in you will see colored edges on the font)**.

I checked other Static site generators, and they all seem fine and render it fine, but Mkdocs always renders them a bit blurry.

When I went to inspect the fonts side by side, the difference became clear.

And this does not happen for some fonts, it's the same thing for **any font** in Mkdocs, **LaTeX** as well.

For those who think `font-smooth` or `text-rendering` can do something, try it yourself, they don't change anything.

### Purpose to fix it

Subpixel rendering looks way more clear while reading compared to grayscale rendering

### Related links

- **Subpixel rendering** - [Docusaurus]( https://docusaurus.io/docs#fast-track), [VuePress](https://vuepress.vuejs.org/guide/getting-started.html)
- **Grayscale Rendering** - [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/getting-started/), [Mkdocs](https://www.mkdocs.org/getting-started/)

### Reproduction

You can reproduce it by checking either of the sites that I mentioned above and see it for yourself after zooming in the fonts.

![font-smoothing](https://github.com/mkdocs/mkdocs/assets/10180981/26aa7c89-02ea-4f74-a022-062816d385ea)

### Steps to reproduce

1. Go to either of the sites that I mentioned above
2. Take a screenshot of some of the text
3. Compare them side by side in any image editing tool (Paint 3D for me)

### Browser

Chrome, Edge

**Comment by oprypin** [comment]
@ryuukk Thanks for pointing me towards the `*-font-smoothing` options. I definitely agree with you - if a user has configured their preference for font rendering, what business do individual websites have overriding that preference and standing out like a sore thumb against the entire system?

I am in the opposite camp (grayscale forever!), and I'm guessing probably my browser doesn't support this setting, because I instantly snipe the christmasy-lit-up looking letters when subpixel rendering somehow sneaks into my system, but I've never observed it in Firefox.

And of course for this case, I don't notice if MkDocs themes set it *to* grayscale because that's what I already have. But I will always support removing any such overrides whenever possible :)

So yes, it is sad that the most used theme for MkDocs - "material" - now considers it a fundamental change to *un*-mess with the fonts.

As for MkDocs' built-in themes:
* The "mkdocs" theme never has any mentions of "font-smoothing".
* The "readthedocs" theme unfortunately inherits *some* instances of "font-smoothing". But weirdly, of any noticeable things, it is applied only to admonitions from what I observed, and otherwise it's applied only to tiny controls.

  <blockquote><details><summary>

  (how do I know? my method of testing was:
  replace `-webkit-font-smoothing:antialiased;`  
  with `-webkit-font-smoothing:antialiased;font-family:"Comic Sans MS" !important`)

  </summary>

    ![image](https://github.com/mkdocs/mkdocs/assets/371383/7d0a8523-ba5a-4ada-8eb4-b1e7c090ca2f)

  </details></blockquote>

So the original claim from the issue "Mkdocs (any mkdocs theme)" by @stojan97 is either wrong or simply a different claim than @ryuukk 's

Even more weirdly, @stojan97 links to Docusaurus as a "good" opposite example, but their website sets the exact same CSS as mkdocs-material!  - `-webkit-font-smoothing:antialiased` - so this claim makes even less sense then.

But hopefully we can at least agree that MkDocs shouldn't **start** messing with font rendering in all themes.

**Comment by tomchristie** [comment]
@stojan97 - Thanks for the report. ☺️
I don't think we'll treat this as an issue unless someone's invested enough to proactively deal with a pull request.

**Comment by ValdikSS** [comment]
The issue is caused by `z-index: -1` for `body::before` in base.css:

```diff
 body::before {
     content: ' ';
     position: fixed;
     width: 100%;
     height: 100%;
     top: 0;
     left: 0;
     background-color: var(--bs-body-bg);
     background: url(../img/grid.png) repeat-x;
     will-change: transform;
     z-index: -1;
-    z-index: -1;
 }
```
