### ISSUE TITLE
Case insensitive keys in YAML-style Meta-Data

### ISSUE THREAD

**Issue by venthur** [mkdocs/mkdocs#3567]
[Currently](https://www.mkdocs.org/user-guide/writing-your-docs/#yaml-style-meta-data), the keys in the YAML-style Meta-Data are case sensitive and expected to be lower-case:

> Note that the YAML keys are case sensitive and MkDocs expects keys to be all lowercase. 

Would it be possible to allow (by default, or via configuration) for case-insensitive YAML keys?

**Comment by pawamoy** [comment]
Could you elaborate why you want this feature?

**Comment by venthur** [comment]
Sure, the requirement that all keys are case sensitive and mkdocs expects them to be lowercase, was surprising behavior for me and I only found out about it after specifically searching for case sensitivity in the docs when things did not work for me as expected. In this case I was using uppercase keys and was wrongly assuming case did not matter. 

Since I already have a lot of documents with uppercase keys, I was looking for an configuration option to change the default.

I'm not suggesting that the current default is wrong, I'm just wondering if one could add an config option to make the keys case-insensitive.

**Comment by pawamoy** [comment]
> In this case I was using uppercase keys and was wrongly assuming case did not matter.

I don't think I ever used a tool that allowed case-insensitive keys. I think it is safe to generally assume that YAML keys are case-sensitive, since YAML itself *is* case-sensitive.

> Since I already have a lot of documents with uppercase keys

Do you mean that you have a lot of Markdown pages with front-matter metadata using uppercase keys, to configure for example plugins or your own metadata? Then you'd like to use uppercase for MkDocs own metadata, for consistency's sake?

IMO it is not worth it, and case-insensitivity does not play well with other tools anyway, such as JSON schemas describing possible keys and values. This could also make things confusing: if keys are case-insensitive in front-matter, are they too in mkdocs.yml? if no, why not? etc.

**Comment by oprypin** [comment]
Hm sorry, that's not a convincing use case. Even *you* will be better off by globally replacing the existing keys with a consistent style of keys rather than enabling a case-insensitive mode if it existed.
