### ISSUE TITLE
ModuleNotFoundError: No module named 'mkdocs.tests'

### ISSUE THREAD

**Issue by chuckwondo** [mkdocs/mkdocs#3702]
The plugin `mkdocs-jupyter` attempts to import from `mkdocs.tests.base`, but with `mkdocs` 1.6.0, the `mkdocs.tests` module is no longer exported, resulting in `ModuleNotFoundError: No module named 'mkdocs.tests'`

In `mkdocs` 1.5.3, there was this in `pyproject.toml`: https://github.com/mkdocs/mkdocs/blob/1.5.3/pyproject.toml#L98-L99

In `mkdocs` 1.6.0, this was changed to: https://github.com/mkdocs/mkdocs/blob/1.6.0/pyproject.toml#L96-L97

Was this an intentional change to _not_ expose the entirety of `mkdocs.tests`? Are plugins _not_ supposed to make use of this module?

This has been reported in `mkdocs-jupyter`: https://github.com/danielfrg/mkdocs-jupyter/issues/200

**Comment by pawamoy** [comment]
Hey @chuckwondo, thanks for the report and investigation.

This was done in https://github.com/mkdocs/mkdocs/pull/3522. Looks like an oversight. The confusing part here is that tests are part of the sources but now excluded from distributions.

It should be worth noting that the test modules were probably never meant to be consumed as public API. But they were exposed as such, so, our mistake.

Also note that this was fixed in mkdocs-jupyter by @oprypin himself as soon as the changed was made in MkDocs: https://github.com/danielfrg/mkdocs-jupyter/commit/03654337645f6e17acd92fa68a0e17f9052250b4. I suppose mkdocs-jupyter just needs to release a new version if this is not done already. If @oprypin found this use of mkdocs.tests in mkdocs-jupyter, I think we can safely assume he's searched thorouhgly on GitHub for similar uses and sent patches where needed.
