### ISSUE TITLE
MKDocs is not auto populating sub-sections 

### ISSUE THREAD

**Issue by micdonato** [mkdocs/mkdocs#3889]
Hi all, I was reading through [714](https://github.com/mkdocs/mkdocs/issues/714) and I am confused about how this was solved.

In the MKDocs repo I see this:

```
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide/
  - Developer Guide: dev-guide/
```

And it seems to work well without any plugin directly related to it (or maybe I am missing something)

When I try to do the same (adding a directory as nav element) I get:

```
WARNING -  A reference to 'setups/' is included in the 'nav' configuration, which is not
           found in the documentation files.
```

This is the tree of the project:

```
.
├── docs
│   ├── index.md
│   └── setups
│       └── test.md
├── hello.py
├── mkdocs.yml
├── pyproject.toml
├── README.md
└── uv.lock
```

And this is mkdocs.yml

```
site_name: My Docs
nav:
  - Home: index.md
  - setups: setups/
```

What am I missing here?

**Comment by pawamoy** [comment]
I believe it works in MkDocs' own repo because of this setup:

https://github.com/mkdocs/mkdocs/blob/7e4892ab2dd4a52efd95a9de407eee63310e0780/mkdocs.yml#L65-L67

The nav is populated from the README contents, for example https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/README.md.

See literate-nav's documentation: https://oprypin.github.io/mkdocs-literate-nav/index.html.

I believe we can close as there's nothing actionable for us here :slightly_smiling_face:
