### ISSUE TITLE
Please allow to build *all* markdown files, not just the ones listed in `pages`

### ISSUE THREAD

**Issue by venthur** [mkdocs/mkdocs#471]
If you have a project with *lots* of documentation (i.e. markdown files), you don't want them all to be in the `pages` list. For most of them it might be sufficient to be linked from within another document. Right now it seems that `mkdocs` only builds documents that appear in the pages list. Only if the pages list is empty, it will build all of them, but then they will *all* appear in the navigation bar. I propose to build all documents by default, even if `pages` is not empty.

**Comment by d0ugal** [comment]
Having pages be build but not included in the navigation is a popular request. So, for that reason I kinda like this idea. I think we would need to display a warning for pages that are built but not in the nav or linked from another page - as otherwise they couldn't easily be found.

If we did go down this route, I'd suggest we deprecate the `pages` config and make a `navigation` config. Since the new approach would define the navigation and not which pages are built.

Having said all that, I don't have the bandwidth to do this soon. I'm still not convinced it is exactly what we want to do. However, we should think about it and decide before doing a `1.0` release.

**Comment by waylan** [comment]
I guess I don't understand this request. At least not for documentation where we have previous/next links to move between all the pages. In that type of site, all of the pages need to be in the list to determine their order. Sure, in other types of web sites, that may not be the case, in which case simply converting all pages on the file system makes sense. But how would you order those pages for previous/next links?

Therefore, in my opinion, supporting pages outside of the explicitly defined navigation list is outside the scope of mkdocs. If you want that, then you probably should be using a different static site generator which is intended for your use case. That said, I'm not a developer of mkdocs, so that is just my opinion. 

I suspect that the problem is more to do with the poor documentation regarding how to configure multi-level navigation. Based on the docs, I expect that everyone creates a flat list of pages and then sees that every single page is listed in the top nav bar of the mkdocs theme -- which they don't want. What you need to do, it only set a few pages as top level pages and make all other pages child pages which don't get their own listing in the top nav bar. Unfortunately, the docs don't exactly explain this well.

Of course, if you use the Read the Docs theme, then the multi-level nav is unused (you only get previous/next), so the multi-level config is not needed there. Once I realized that, I stopped using the mkdocs theme and don't expect to ever go back.

I think I understand how to configure multi-level nav after having looked at how the mkdocs.org site is configured. But until I experiment with it, I'm not really sure as the docs don't explain it. And given I don't need it (using a different theme) I doubt I'll ever take the time to figure it out. Perhaps if the pages list was a nested list rather than a flat list it would be more clear. This would also make it easier to support more than two levels (see #6).

**Comment by d0ugal** [comment]
@waylan multilevel is used in ReadTheDocs, depending how you look at it at least. You can see it here for example: http://mkdocs.readthedocs.org/en/latest/

That's a fair point about the documentation - lets improve it. https://github.com/mkdocs/mkdocs/issues/475

And otherwise, yeah, I agree with @waylan - that was very well put. This should be solved by better navigation nesting like #6 will hopefully give us at some point. I suspect we wont show level three items in the navigation (on default themes at least).
