### ISSUE TITLE
smartypants extension error

### ISSUE THREAD

**Issue by bwmarrin** [mkdocs/mkdocs#519]
I'm new to mkdocs and have recently installed it.  I'm running on Windows and am using Python 3.4.

I was walking though some of the mkdocs documentation and wanted to try to use smartypants.  Initially I found out I had to install the extension itself which wasn't mentioned in the mkdocs documentation (might be helpful to add that).  After installing the extension with pip I tried to use it using all 3 of the below configuration formats..

```
markdown_extensions: [smartypants]
```
```
markdown_extensions: 
       - smartypants
```
```
markdown_extensions:
          smartypants:
```

Either way, when I try to run mkdocs serve I get the below error

```
ERROR - Error building page index.md
[E 150512 11:21:27 build:221] Error building page index.md
Traceback (most recent call last):
  File "C:\tools\python\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.12.2', 'console_scripts', 'mkdocs')()
  File "C:\tools\python\lib\site-packages\mkdocs\main.py", line 77, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "C:\tools\python\lib\site-packages\mkdocs\main.py", line 49, in main
    serve(config, options=options)
  File "C:\tools\python\lib\site-packages\mkdocs\serve.py", line 22, in serve
    builder()
  File "C:\tools\python\lib\site-packages\mkdocs\serve.py", line 19, in builder
    build(config, live_server=True)
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 252, in build
    build_pages(config)
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 219, in build_pages
    _build_page(page, config, site_navigation, env, dump_json)
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 173, in _build_page
    extensions=config['markdown_extensions'], strict=config['strict']
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 36, in convert_markdown
    extensions=extensions
  File "C:\tools\python\lib\site-packages\markdown\__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "C:\tools\python\lib\site-packages\markdown\__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "C:\tools\python\lib\site-packages\markdown\__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
  File "C:\tools\python\lib\site-packages\mdx_smartypants\core.py", line 52, in makeExtension
    return SmartypantsExt(configs=configs)
  File "C:\tools\python\lib\site-packages\mdx_smartypants\core.py", line 41, in __init__
    self.configs = dict(configs)
TypeError: 'NoneType' object is not iterable
```

**Comment by d0ugal** [comment]
I *think* this is a documentation bug as smartypants is included in Python-markdown now.

As for why you get that specific error, I'm not sure. I'll look into updating the docs for this and checking.

**Comment by d0ugal** [comment]
Can you try this?

    markdown_extensions:
        - markdown.extensions.smarty:

**Comment by waylan** [comment]
The error is a result of the third-party Smartpants extension not being compatible with the most recent version of Python-Markdown. However, as @d0ugal notes, a version of the extension is now included with Markdown which is named "smarty". It is suggested that you use that extension instead. And yes, the docs should be updated to reflect this.

**Comment by bwmarrin** [comment]
Thanks for the quick response guys.

If I use the exampled from d0ugal I get the below error

```
ERROR - Error building page index.md
[E 150512 11:49:52 build:221] Error building page index.md
Traceback (most recent call last):
  File "C:\tools\python\Scripts\mkdocs-script.py", line 9, in <module>
    load_entry_point('mkdocs==0.12.2', 'console_scripts', 'mkdocs')()
  File "C:\tools\python\lib\site-packages\mkdocs\main.py", line 77, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "C:\tools\python\lib\site-packages\mkdocs\main.py", line 49, in main
    serve(config, options=options)
  File "C:\tools\python\lib\site-packages\mkdocs\serve.py", line 22, in serve
    builder()
  File "C:\tools\python\lib\site-packages\mkdocs\serve.py", line 19, in builder
    build(config, live_server=True)
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 252, in build
    build_pages(config)
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 219, in build_pages
    _build_page(page, config, site_navigation, env, dump_json)
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 173, in _build_page
    extensions=config['markdown_extensions'], strict=config['strict']
  File "C:\tools\python\lib\site-packages\mkdocs\build.py", line 36, in convert_markdown
    extensions=extensions
  File "C:\tools\python\lib\site-packages\markdown\__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "C:\tools\python\lib\site-packages\markdown\__init__.py", line 195, in registerExtensions
    % (ext.__class__.__module__, ext.__class__.__name__))
TypeError: Extension "builtins.dict" must be of type: "markdown.Extension"
```

**Comment by bwmarrin** [comment]
Ah, the below to formats works.

```
markdown_extensions:
    - markdown.extensions.smarty
```

Or 

```
markdown_extensions:
        markdown.extensions.smarty:
```

**Comment by bwmarrin** [comment]
Also,

```
markdown_extensions: [markdown.extensions.smarty]
```

Works as well.

**Comment by waylan** [comment]
Correct, you can't have both the the `-` and the `:` together. Either one or the other.

This is slightly confusing as all other config setting which accept multiple values use lists (start with a `-`), even if there are key/value pairs. However that results in a list where each item in the list is a separate dict with one key/value pair. However, Markdown requires a single dictionary containing all key/value pairs -- unless no config options are specified for any extensions, in which case, a list of extensions names only is acceptable.

I'm not sure of the best way to differentiate this in the docs. Or perhaps a list of dicts should be accepted and then the multiple dicts merged. I'll play with this later and see what I can come up with because I expect users will encounter this issue repeatedly. Besides, I want to move this code to the new config validation anyway. At the very least, users will get a better error message telling them their config is invalid. I'll see if I can put something together later today.

**Comment by facelessuser** [comment]
I think mkdocs should migrate to **one** way of defining extensions (whatever way that is) for a 1.0 release.  It is confusing to have multiple ways.  If there is one way, and it is described well, I think a lot of the confusion will disappear.  That's just my opinion.

**Comment by bwmarrin** [comment]
Well, being new and all - not sure that my thoughts matter much, but...  I also agree that having one way makes the most sense.  One well documented method is definitely much less confusing.

**Comment by waylan** [comment]
I agree that **one** way to ideal. That's why I'll soon have a PR supporting a list with config options. That way, the markdown_extensions config value will always be a list. A little more post-processing is required, but to the end user, it is of little consequence to add config options if it still stays a list.

This is my thinking about how it **should** work. The following examples might even be used in an update to the docs after I get the code working. 

When no extensions have config options set:

    markdown_extensions:
        - smarty
        - extra

When a config option is set:

    markdown_extensions:
        - smarty:
            smart_angled_quotes: True
        - extra

Note that to add an option, only the specific list item needs to be altered (add a Colon to the end and add a nested key/value pair. If an extension does not have any options set, no key/value pair is necessary. However, if a user creates a key/value pair anyway (perhaps the user has removed the option but not the colon), like this:

    markdown_extensions:
        - smarty:
        - extra

Then the right thing happens (no errors). Should be easy enough as we will need to loop through the list anyway to build the structure Python-Markdown expects.

Btw, no matter what we do, other syntax will work, but that is a symptom of YAML supporting multiple different formats which result in the same underlying Python structure (for example the bracket syntax for lists and curly brackets for dicts). However, I think that if we document the above first two examples only, that will lead to the least confusion. Especially as all other multi-value items in the config are lists. In particular, the recently re- factored pages as a list of key/value pairs (see #482) comes to mind. At the time I coded the original support for extension configs, that hadn't happened yet. I suspect that if it had, I would have done this feature with a list as described above rather than as currently implemented.

**Comment by facelessuser** [comment]
I like it.  I recall suggesting the same thing in another issue, but at the time @d0ugal was trying to stay away from another iteration of configuring  extensions; which I completely understand.  But as having two methods to define extensions will be confusing, combining them is probably the most intuitive thing that be done.  I think adopting this way before 1.0 release is fine as it should be expected some things will be in flux before 1.0 release.

And yeah, nothing can be done about canonical formatting of YAML vs non-canonical vs whatever.  But making it clear they are always lists and optionally a key value pair for adding configs should be enough, especially if examples are provided as you have above.

**Comment by d0ugal** [comment]
> Well, being new and all - not sure that my thoughts matter much, but... I also agree that having one way makes the most sense. One well documented method is definitely much less confusing.

@bwmarrin New eyes are often more important, I'm sure we lose some new users due to issues like this. Thanks for taking the time to report it.

**Comment by d0ugal** [comment]
@waylan That proposal sounds great, and I agree, let's document that way of doing it. Users comfortable with YAML can use others if they wish.

I see two offshoots from this.

- Fix documentation to use the builtin smarty extension.
- Update the extension config to use the list based approach.

I'd like to see both of these in 0.13, so if you don't get time @waylan I can have a go at doing it.

**Comment by waylan** [comment]
I have this mostly done, but ran out of time last night. I just have to thoroughly test and document. Should have it done by the weekend.

**Comment by d0ugal** [comment]
Great - no immediate rush!
