### ISSUE TITLE
Incorrect rendering of nested lists

### ISSUE THREAD

**Issue by jiahao** [mkdocs/mkdocs#545]
A list like

1. a
2. b
  - c
  - d
3. e

builds into

1. a
2. b
3. c
4. d
5. e

instead.

**Comment by d0ugal** [comment]
We use Python-Markdown for rendering of Markdown files. I suspect this isn't a bug, but you should ask upstream https://github.com/waylan/Python-Markdown

**Comment by jiahao** [comment]
Thanks for the pointer. This issue turns out to be waylan/Python-Markdown#3

**Comment by d0ugal** [comment]
Ha, now I know. Thanks!

**Comment by rufuspollock** [comment]
Hi, i don't want to change all my existing docs to 4 spaces. Is there a way to configure mkdocs to following 2 spaces as per instructions upstream https://github.com/waylan/Python-Markdown/issues/3

```
markdown.markdown(text, tab_length=2)
```

**Comment by waylan** [comment]
> Is there a way to configure mkdocs to following 2 spaces as per instructions upstream 

No, not directly. MkDocs only allows extensions to modify Markdown behavior. Although, there isn't any reason why an extension couldn't alter the `tab_length` attribute on the `Markdown` class. I suppose you could write a custom extension to do this. But personally, I think your time would be better spent making well-formed Markdown documents.

**Comment by rufuspollock** [comment]
@waylan thanks. I do think it would be useful for most people to have a way to turn this on.

i have a large number of documents, many of them provided by others. Moreover, as you know, the original markdown.pl did not implement nor do many, many implementations in the wild.

Moreover, my reading of the commonmark spec suggests that 2 spaces is permitted: http://spec.commonmark.org/0.27/#lists (please correct me if i has misread this).

**Comment by waylan** [comment]
This seems to be an upstream issue which has been addressed upstream.

As I state in [this comment][1]: "Python-Markdown's behavior is __NOT__ a bug (and not up for debate)."

As I commented [here][2] and [here][3], I do not consider CommonMark to be relevant to this discussion.

To be clear the above are my opinions and not the opinions of the MkDocs team. 

It could be confusing because I am the newest member of the (multi-member) MkDocs team and the (sole, long-time) maintainer of the underlying Python-Markdown library. So let me be clear. Wearing my MkDocs team hat, I say you should take this upstream. But wearing my Python-Markdown hat, I say the matter has already been decided and I won't reconsider. So, I'm acknowledging that taking it upstream its not going to be productive. Even so, this isn't the place to discuss the issue.

Regardless, anyone can create extensions which alter the parser in any way they desire and MkDocs offers full support for such extensions, so MkDocs is not really limiting you. You just need to do a little more work to get what you want. 

[1]: https://github.com/waylan/Python-Markdown/issues/3#issuecomment-63399983
[2]: https://github.com/waylan/Python-Markdown/issues/545#issuecomment-279873966
[3]: https://github.com/waylan/Python-Markdown/issues/338#issuecomment-54697337

**Comment by rufuspollock** [comment]
@waylan how exactly would you go about implementing this as an extension?

**Comment by facelessuser** [comment]
I imagine something like this (assuming I didn't make a mistake):

```
from __future__ import unicode_literals
from markdown import Extension

class ExtendTabExtension(Extension):
    """Adjust Markdown tab length."""

    def extendMarkdown(self, md, md_globals):
        """Register extension instances."""

        md.tab_length = 2


def makeExtension(*args, **kwargs):
    """Return extension."""

    return ExtendTabExtension(*args, **kwargs)
```

If you want to make the length configurable, you'll have to take a look at the default extensions as examples and/or read Python Markdown's documentation, but this should get you rolling.

**Comment by waylan** [comment]
Adjusting tab length as @facelessuser suggests would work. However, that adjusts the tab length for everything, not just lists. In other words, indented code blocks would only need to be indented two spaces as well. Probably not what you want.

I would expect that the extension would need to replace the list processors. You may want to look at the [sane_lists extension][1], which subclasses the built-in list processors and changes their behavior. In fact, those subleases make reference to the `tab_length`. Perhaps a subclass that uses something other than the global tab_length would provide your desired behavior. At the very least, that would limit to change to the lists only, rather than all aspects of the parser. 

[1]: https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/sane_lists.py

**Comment by facelessuser** [comment]
Ah, good point. Pays to read the response closer.

**Comment by biochimia** [comment]
I'm using the minimal extension below to support two-space indented lists. The same approach also works well with `sane_lists`'s `SaneOListProcessor`, and `SaneUListProcessor`.

As for others in this thread, in our use case it is beneficial to keep compatibility with Github (Enterprise), to reduce the surprise factor and friction in onboarding projects to an `mkdocs`-based platform, while we keep adding value to the platform.

```
from markdown.extensions import Extension
from markdown.blockprocessors import (
    ListIndentProcessor, OListProcessor, UListProcessor)


class ShortIndentListExtension(Extension):
    def extendMarkdown(self, md, md_globals):
        original_tab_length = md.parser.markdown.tab_length
        md.parser.markdown.tab_length = 2

        try:
            md.parser.blockprocessors['indent'] = ListIndentProcessor(md.parser)
            md.parser.blockprocessors['olist'] = OListProcessor(md.parser)
            md.parser.blockprocessors['ulist'] = UListProcessor(md.parser)
        finally:
            md.parser.markdown.tab_length = original_tab_length


def makeExtension(*args, **kwargs):
    return ShortIndentListExtension(*args, **kwargs)
```

**Comment by PegasusWang** [comment]
Solved.
Add "mdx_truly_sane_lists" to you requirements.txt or `pip install  mdx_truly_sane_lists`.

Then edit your mkdocs.yml like this:

```yml
markdown_extensions:
  - mdx_truly_sane_lists
```

**Comment by pyr0ball** [comment]
Sorry to nekro this issue, but I'm having the same nested list issue even with the extension above enabled.

Example page here: 
live/html: https://docs.pyroballpcbs.com/config/
src/markdown: https://github.com/pyr0ball/pyr0piezo/blob/master/docs/config.md
mkdocs.yml: https://github.com/pyr0ball/pyr0piezo/blob/master/mkdocs.yml

**Comment by kratsg** [comment]
Sorry to necro, I wanted to add that this package works for me: https://pypi.org/project/mdx-truly-sane-lists/

**Comment by anarcat** [comment]
this is a major hurdle in adopting mkdocs for us here. it requires converting hundreds of markdown documents that work perfectly fine in github, gitlab and other renderers that are less opiniated about following a (non-)standard than most...

i think that, at the very least, the indentation should be customizable in the mkdocs configuration... it seems like the way forward...

alternatively, why couldn't https://github.com/radude/mdx_truly_sane_lists be merged upstream? it could serve as a good bolt-on solution for people without them having to install third party packages...

**Comment by madjxatw** [comment]
Disallowing indentation configuration really sucks! MkDocs should consider using another parser to replace python-markdown.
