### ISSUE TITLE
Move non-functional configuration into extra

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#551]
This is a branch from the changes in https://github.com/mkdocs/mkdocs/issues/144.

> We may even want to move some non-behavioral stuff such as copyright and google_analytics into the extra block. It'll help the maintainance of the project if we can reduce the number of valid settings keys - less moving parts then, and the context stuff all nicely separated out.

This was made possible by #539 but it didn't remove any. I think there needs to be some discussion about what makes a non-behavioural configuration option. For example, site name isn't behavioural but it is required. What about site_description?

**Comment by tomchristie** [comment]
Non-behavioral options should not touch the mkdocs codebase in any way.

Theres a few bits of cleanup we'll want to do to reduce the amount of config that's seen by mkdocs in order to help with this cleanup.

`site_name` is something of an exception, because it seemed like a good idea to force the user to have at least a shell of a config file with at least a single valid item, and it's such an obvious requirement to have a title for the site that it seemed sensible to have it as the sole required item.

**Comment by tomchristie** [comment]
See also #683.

**Comment by waylan** [comment]
I'm deferring this as this is mostly implemented today. While we do have some existing config settings which do not need to be part of the core set of settings, we also have theme specific settings and plugin specific settings. Over time as themes and plugins develop their own settings more and more of the builtin settings can be removed.
