### ISSUE TITLE
Observations/What I Thought I Was Going to Do

### ISSUE THREAD

**Issue by ProfYaffle** [mkdocs/mkdocs#555]
After an IRC chat with d0ugal, I thought I'd share this - it might be useful, or might just be a garbage view of 'that's not what I intended it for'.

I was looking for a way to write documentation once and use it multiple times. The intention was to have an online user guide, but then have fragments of that sync'ed into the application itself as web help (it's a browser-based interface - tvheadend, if you're interested).

Using a markup language seemed the way to go, and I settled on markdown as the most portable and easiest to use given the relatively simple nature of our documentation. This is where I hit a bit of an issue with mkdocs (leaving aside my tribulations with readthedocs...)...

1. I expected 'mkdocs build' to produce html files that were directly equivalent to my md docs. Instead, it produces monolithic pages that include the ToC and navigation panes, which means they're not usable without the whole web site guide (they make no sense as fragments in their own pane as application help).

2. Similarly, I was surprised to see that every input file ends up in its own directory as index.html, rather than keeping any semblance of the original file name (so need post-processing, or I need to rewrite how the application looks for them).

3. A lack of > two-level ToC (or #include directive) means that a really section-heavy document generates an enormous ToC. Bear in mind the 'one html fragment per web page on the application': I was trying to avoid massive pages with lots of content, but multiple pages drive multiple index entries instead.

I was trying to avoid unnecessary workflow or modifications, so maybe I was naive. As it happens, pandoc with additional header files does a great job at converting the md files standalone, so a combination of mkdocs for the main web site and a quick batch pandoc for the fragments seems to be the way to go for now. 

Otherwise, an excellent tool that's showing real promise ... once readthedocs catches up... :wink:

Cheers!

**Comment by d0ugal** [comment]
> leaving aside my tribulations with readthedocs...

I know I told you this, but for anyone else that stumbles on this, they should track https://github.com/mkdocs/mkdocs/issues/554


> 1 I expected 'mkdocs build' to produce html files that were directly equivalent to my md docs. 

This is an interesting use case, it isn't one that I can remember coming up before. How would you make HTML pages that work together and on their own? In once case you need a navigation and in others you don't. A custom theme could perhaps help you here, but I'm still not sure how it would work exactly. The real advantage of MkDocs is that it combines multiple markdown files, the tooling for rendering one Markdown file to HTML is generally very good in python-markdown itself, which is what we use.

> 2 Similarly, I was surprised to see that every input file ends up in its own directory as index.html,

Yeah, so, this again is because we are focused on the web audience, so it creates nicer URLs. I can see the use case here, we also have to do nasty hacks to make it work with index.html files. If there were a sensible way to support both, I could be interested. However, it would be tricky as much of the code assumes the current way I think - it may be worth investigating this again at some point.


> 3 A lack of > two-level ToC (or #include directive) means that a really section-heavy document generates an enormous ToC

Multi-level nav was added in #482. It's pretty nice :) Specifically see this comment message for examples  https://github.com/mkdocs/mkdocs/commit/8085c65c6acc394be21aad866fdf0f68b6cb650e

What do you want to include? Markdown into multiple pages?

---

Thanks for the feedback, it does sound like you have a use case that we have not really considered before. What do you want to include the individual HTML files in? Would having a way to disable/hide the navigation for builds be enough for that?

**Comment by ProfYaffle** [comment]
Yeah, it's all about the case ('bout the case, 'bout the case...), really - and I'm happy to accept that I'm trying to do something for which the tool wasn't intended.

Re: *"How would you make HTML pages that work together and on their own"* - hey, I hadn't got that far, I was just saying what my naive hope was! :grinning: 

Re: most of the rest... the inclusion was really a way to address the fragments/ToC issue. Here's a real case - these are (some of) the tabs of our application and each has its own pop-up web help:

![general](https://cloud.githubusercontent.com/assets/6093716/7794809/6c8e7602-02c6-11e5-89d6-a67f2a70c2eb.png)

![dvb](https://cloud.githubusercontent.com/assets/6093716/7794811/6f054960-02c6-11e5-980b-a2480f97683b.png)

So, the obvious User Guide structure is something like:

    Preamble/intro
    Before you begin/setting up
    Getting started
    Detailed view
        Electronic Program Guide
        Digital Video Recorder
            subtab
            subtab
            subtab
        Configuration
            General
            Access Entries
            DVB Inputs
                TV Adapters
                Networks
                Muxes
    ...

... with each 'terminal node' as a standalone web-page that can be called up for that particular tab.

Now, to address the ToC level/size issue, I wondered about creating a page (e.g. 'Digital Video Recorder') that appears in the index, but then #includes the subtabs - each of which could then be converted independently for use in the app help. That gives me one heading in the ToC and one seemingly-monolithic page, but leaves the fragments for use elsewhere.

The best I've managed is to have all pages listed in the pages section of mkdocs.yml, but have links in 'Digital Video Recorder' to the subtab pages so it forms a local index. Not using a header style for the title of each of the subtab pages then takes some entries out of the ToC, but it's not elegant. Even then, I may yet drop the 'local index' as unnecessary given it's all in the ToC, especially if we can go down to more than one level once things get updated... (*/me goes to check mkdocs master*)

It's all driven by this need/desire to have content that can get reused outside of the single website model.

**Comment by d0ugal** [comment]
Interesting, thanks. I think you are right that this is a very particular use case. It was good to hear what people are considering but I can't think of an "action point" for this issue so I'm going to close it. If you can think of ways that we can make this easier for you, then opening issues individually for those would be a good idea. We can then discuss those features or changes individually and see if they make sense for MkDocs.
