### ISSUE TITLE
current_page.url broken

### ISSUE THREAD

**Issue by kikar** [mkdocs/mkdocs#571]
Hi,
this is what is built when is use {{ current_page }}
`Uno - /numbers/uno/index.html [*]`
But this is what i get when is use {{ current_page.url }}
`index.html`
even tough the url should be site/numbers/uno/index.html

**Comment by d0ugal** [comment]
Confirmed, that is a strange one. Not sure how it happened. Probably related to the pages config refactor.

**Comment by d0ugal** [comment]
This is actually the expected behaviour, a bit confusing I realise. I'll try to explain. `current_page.url` is the relative URL to the object. Compare it with `previous_page.url` and `next_page.url`, so since you are on the `current_page` the relative URL is `./`. You probably want the absolute URL which is `current_page.abs_url` which also works for `previous_page` and `next_page`.

Hope that makes sense!

**Comment by kikar** [comment]
canonical_url is actually what I was looking for.
Thanks for the answer!
