### ISSUE TITLE
gh-deploy wont work on Python 2.6

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#598]
Maybe we just don't have many, or any 2.6 users? Currently we use subprocess.check_call, this was added in Python 2.7. We might want to fix this, or we might want to just do #165

**Comment by waylan** [comment]
+1 to dropping 2.6 support. It would make the all-Unicode goal much easier and require a few less hoops for good, consistent PY2-PY3 support. Besides, 2.6 users are already left behind in Python-Markdown support and may even run into issues if they try to use the now-included support for markdown extensions.

**Comment by d0ugal** [comment]
I felt like I shouldn't do this until a 1.0, but maybe bringing it forward is reasonable?

**Comment by waylan** [comment]
My expectation is that any PY26 users out there are not going to be making any changes to their system until they decide to upgrade to a new Python version. Therefore, if they already have a fairly recent MkDocs version which is working on their system, then it seems reasonable to expect that they won't be needing to update any time soon. In my experience, such people are generally not updating and editing their config files/themes/etc. They would only ever be adding new content which will continue to work as long as they never upgrade anything.

I suppose the only real issue is if they have automated builds set up which download/install MkDocs and its dependencies on each build. Make sure the classifiers on PyPI are correct for each version and then everything should still work. They will get the latest version that supports their system (and nothing breaks for them) and everyone else can benefit from all the great new stuff.

Of course, that is all my opinion. Other's may disagree.
