### ISSUE TITLE
Ignore the site_dir contents if it is in the docs_dir

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#610]
We have been telling people to not do this, but it comes up again and again. So I wonder if it is a usecase we should support? I don't really like it. Perhaps we just need to error more strongly and tell users rather than causing obscure problems.

**Comment by d0ugal** [comment]
It is worth noting that it originally did error, but that broke ReadTheDocs for a large number of users so it was [reduced to a warning](https://github.com/mkdocs/mkdocs/commit/fd9140e7d587be310d1bcbff213f079d0af22b97).

**Comment by waylan** [comment]
Based on [this comment][1], it is not clear to me what the appropriate fix is for this. We have three options:

1. Do nothing. A warning will continue to be raised and the weird behavior will continue.
2. Raise an error. Builds will no longer complete if the weird config exists and the weird behavior will be avoided.
3. Apply the fix suggested in this issue, which allows the weird config to remain (possibly with a warning) but eliminates the weird behavior.

It seems clear that we don't want option 1. However, the previously mentioned comment seems to suggest we want option 2, but this issue is for option 3 and is tagged with the 0.16 milestone, potentially making it a release blocker. I'm not inclined to work on a fix until I know which way we want to go (my vote is for option 2).

[1]: https://github.com/mkdocs/mkdocs/issues/796#issuecomment-171914179

**Comment by d0ugal** [comment]
I also vote for option 2. It will block readthedocs from upgrading to 0.16, but that should be easy to fix on their end.

**Comment by trel** [comment]
Agreed - go for 2.
Break things now.

Supporting weird for a long time will drive you crazy.
