### ISSUE TITLE
Mailto links not correctly interpreted

### ISSUE THREAD

**Issue by Razique** [mkdocs/mkdocs#646]
Hi, 
I've noticed "mailto" links are not correctly interpreted.

- This code:
````
Contact us at <foo@bar>
````
- Renders the following link:  
http://localhost//mailto:foo@bar  

***
- This code:
````
You can [contact us](foo@bar)
````
- Renders the following link:  
http://localhost/page/permalink/foo@bar

**Comment by waylan** [comment]
The first issue is a bug in MkDocs. The second is user error. See below for details.

This is caused by the relative path extension to Python-Markdown which ships with MkDocs. The extension attempts to "do the right thing" and [return immediately][1] if a scheme is included in the URL. However, the Markdown's [Syntax Rules][2] require email addresses to be entity-encoded and Python's `urlparse` function does not understand the encoded url properly (browsers do so this is only a problem when using `urlparse`):

```python
>>> from mkdocs.utils import urlparse
>>> urlparse("mailto:foo@bar")
ParseResult(scheme='mailto', netloc='', path='foo@bar', params='', query='', fragment='')
>>> urlparse("&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#102;&#111;&#111;&#64;&#98;&#97;&#114;")
ParseResult(scheme='', netloc='', path='&', params='', query='', fragment='109;&#97;&#105;&#108;&#116;&#111;&#58;&#102;&#111;&#111;&#64;&#98;&#97;&#114;')
```

As this only happens with email autolinks, perhaps the extension could check for the encoded "mailto" scheme:

```python
if scheme or netloc or not path or url.startswith('&#109;&#97;&#105;&#108;&#116;&#111;&#58;'):
    return url
```

As stated above, the encoding only applies to autolinks (links surrounded by `<anglebrackets>`). Therefore, regular links to not get encoded and this is not an issue.

The second example is user error as that is not valid Markdown. When defining any absolute address (web or email) for a link, you need to define the scheme (`http:`, `https:`, `ftp:`, `mailto:`, etc.), including for email addresses. Like this:

```
You can [contact us](mailto:foo@bar)
```
In fact, most (all?) Markdown parsers require the scheme (see Babelmark: [with][3], [without][4]). It is not added automatically unless you use an autolink. In fact, many parsers [fail][5] there as `foo@bar` is not considered a valid email address (Python-Markdown is actually pretty loose about what it considers an email address so its not a problem for us). However, `foo@bar.com` [works fine][6] for everyone.

[1]: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/relative_path_ext.py#L66
[2]: https://daringfireball.net/projects/markdown/syntax#autolink
[3]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=You+can+%5Bcontact+us%5D(mailto%3Afoo%40bar.com)
[4]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=You+can+%5Bcontact+us%5D(foo%40bar)
[5]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=Contact+us+at+%3Cfoo%40bar%3E
[6]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=Contact+us+at+%3Cfoo%40bar.com%3E
