### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by BigXplosion** [mkdocs/mkdocs#650]
This might be me being stupid but when I added images to my page they all seem to show up correctly in the correct size but it seems like mkdocs doesn't see how large the images are because the navigation shows it's already at the latest point (Usage in this particular example) eventhough I'm still looking at the second point. example: http://mcmoddocs.com/bca/Blocks/Multiblocks/

**Comment by d0ugal** [comment]
This has happened because your page doesn't contain an H1 (# header) you instead have two H2's (## Header). This means they are treated as top level items and will always be highlighted in the table of contents. As you scroll down others should be highlighted, but both instances of Refinery are always highlighted.

I hope that makes sense, I am not sure I completely understood the question :)

**Comment by d0ugal** [comment]
.... so, if you add `# Blocks` to the top of the file it will probably fix it.

**Comment by BigXplosion** [comment]
that didn't fix it...

I'll try to explain my problem better: If you scroll down (do not use the index at the left) to about the 4th image. the 4th image is still part of the Structure part but the index shows it's already down at Usage or even lower.

**Comment by d0ugal** [comment]
Ah, right. I follow you. So, this is a case of #406 - I've tried to fix this a few times but failed to figure out what is wrong.

**Comment by BigXplosion** [comment]
Ok sorry then, I didn't really find it at first sight.

**Comment by d0ugal** [comment]
No problem :)
