### ISSUE TITLE
ManPage

### ISSUE THREAD

**Issue by williamjmorenor** [mkdocs/mkdocs#686]
Hi

I am working in package mkdocs in Fedora, I am getting a warning because mkdocs do not ship a manpage,:

rpmlint rpmbuild/RPMS/noarch/mkdocs-0.14.0-1.fc22.noarch.rpm 
mkdocs.noarch: W: no-manual-page-for-binary mkdocs

Can please add a mange to mkdocs tarball

**Comment by d0ugal** [comment]
Hi, sure - we can do this. I just need to first learn how  :)

**Comment by waylan** [comment]
There are a few tools out there that will convert optparse/argparse help to man page. I know Click is built on top of optparse (sort of), but not sure if they would work.

**Comment by williamjmorenor** [comment]
https://admin.fedoraproject.org/pkgdb/package/mkdocs/

**Comment by waylan** [comment]
I took another look at this and found [click-man], which is a tool that creates man pages for Click applications. You install the tool and run one command and all your man pages are generated (one per command/subcommand). Interestingly, the [docs] for the package explain why we shouldn't automate that on build (rather than documenting how to automate it). The short of it is that Python builds are system agnostic while man pages are system specific. Also, if installed in a virtualenv, the manpage should not be installed (a reason they miss).

So if you are building deb/rmp/etc packages, then you can use click-man to generate the man page, It's just one more line in your build script. Or, if you installed MkDocs via pip and want a man page, you can `pip install click-man` and then run that one command manually.

Therefore, my proposed resolution of this issue is to document how to use click-man in the installation documentation and be done with it.

[click-man]: https://github.com/click-contrib/click-man
[docs]: https://github.com/click-contrib/click-man#automatic-man-page-installation-with-setuptools-and-pip

**Comment by d0ugal** [comment]
👍🏼 great outcome.
