### ISSUE TITLE
Integrating external Documentation

### ISSUE THREAD

**Issue by Schorny** [mkdocs/mkdocs#691]
I have a documentation written in mkdocs and an API documentation that gets created automatically from the source code.
I currently just use external links inside my mkdocs to link to my API docu, which works fine. But I can't set the API docu as one of the pages target.
And also mkdocs does not copy the API documentation when doing mkdocs build or mkdocs serve, even though it resides in the docs_dir.

Is there any way to "integrate" external documentation in a mkdocs project? basically all I really need is an "asset dir" where I can dump the external documentation and mkdocs just copies it for me 1:1 when doing build or serve and for mkdocs to allow me to link to these assets.

It works fine with images, but somehow with HTML files mkdocs likes to mess with them (changing them or deleting them entirely).

**Comment by samuelcolvin** [comment]
:+1: 

The problem is [here](https://github.com/mkdocs/mkdocs/blob/ff05df30dd2de8840fb185363afa41a5517a69ef/mkdocs/utils/__init__.py#L147): 
```python
and not is_html_file(filename)
```
mkdocs is excluding all html files.

Would be great if this could be changed so html documents could be included when serving, building or deploying, I guess via a switch which defaulted to false so current default functionality isn't changed.

I have the same problem with [bokeh.github.io/Bokeh.jl](http://bokeh.github.io/Bokeh.jl/) the plot `.html` files which definitely **are** media files in this context (the whole premise of bokeh is that html can be used as a format for self contained interactive plots) are excluded.

In this case I use 
```shell
rm -r site/; mkdocs build; cp -r docs/examples/ site/; ghp-import -p site/
```
to ignore mkdocs and deploy the html files to github pages anyway.

**Comment by d0ugal** [comment]
Yeah, good point - that is a regression.
