### ISSUE TITLE
Vendor six?

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#705]
So, we switched to six because it allowed us to remove our compat.py which was basically a bad implementation of six.

Then we had a bunch of problems with users and having six as a dependency - I think this might be due to vendors special casing six and you end up with a forced version on the path before the one in site-requirements? So we backed it out and the comparability is handled in each file.

This bugs me, perhaps irrationally. Clearly @tomchristie was surprised by this as the compat.py appeared again in the refactor pull request.

So, why don't we vendor six? It is just one file and designed for easy vendoring. Seems like a win win other than some extra code under mkdocs.utils.six perhaps.

**Comment by facelessuser** [comment]
> This bugs me, perhaps irrationally. Clearly @tomchristie was surprised by this as the compat.py appeared again in the refactor pull request. 

Meh, it's personal preference really.  Vendoring it will work just as well as having your own custom abstraction layer.  Six works good at abstracting builtin python differences, but if there are 3rd party modules you use that differ depending on Python version, then you have to have a compat abstraction layer anyways; I don't think mkdocs has this problem, but **no one** can **always** avoid using a compat layer.

> which was basically a bad implementation of six

I don't really think it is either good or bad personally as its just an abstraction layer.  I only view it bad if there is a performance decrease or something like that.  Sure abstraction layers are ugly, even six is ugly on the inside as it is a series of hacks to make PY2 and PY3 look and behave similar.  I have never seen a pretty abstraction layer; they are always messy on the inside as they are trying to hide the mess and provide a more sane API to the outside.

I guess you just have to decide if it bothers you enough to change it.  Since vendoring six would eliminate the original issue with six, I can't see it being a big deal either way.  I don't think this is an issue of what is better, but what do you like more.

**Comment by waylan** [comment]
When I put together  the Pull Request which removed six, I started out by recreating compat.py. However, I quickly realized that each part of it is only ever imported by one file (except one object which was imported by two). That being the case, I didn't see the point in even having the file and built the current implementation with no compat.py. To me it is much cleaner and what I would prefer to see going forward. 

However if you disagree, then I would suggest staying with your own compat.py. Six is way more complex than MkDocs needs. In my opinion MkDocs is actually simpler without six.

**Comment by facelessuser** [comment]
> Six is way more complex than MkDocs needs.

I think six is overkill for just about anyone, but that may just be me :smile:.

**Comment by d0ugal** [comment]
Yeah, so if I were to create a compat.py, I would copy the relevant bits from six to keep it "standard" but that seems like more effort than including the six file.

**Comment by tomchristie** [comment]
I doubt we use enough bits from it to pull in the whole module. My preference would be isolate cross-version stuff in compat.py and pull in only what we need.

**Comment by d0ugal** [comment]
Alright, guess it is just me.
