### ISSUE TITLE
Inconsistent labelling of headers in toctree (h1+h2 vs h2+h3)

### ISSUE THREAD

**Issue by hayd** [mkdocs/mkdocs#712]
![No h3 links](https://cloud.githubusercontent.com/assets/1931852/9281264/98b419e8-4278-11e5-92c5-bb0944ee0e8b.png) No h3 links
![Has h3 links](https://cloud.githubusercontent.com/assets/1931852/9281265/9cb60b14-4278-11e5-937f-b650425777fc.png) Has h3 links

The corresponding markdown [1](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/doc/centrality.md) and [2](https://raw.githubusercontent.com/JuliaGraphs/LightGraphs.jl/master/doc/linalg.md). One expects to see links for the methods `degree_centrality`, `indegree_centrality` and `outdegree_centrality` below "Degree Centrality". See https://lightgraphsjl.readthedocs.org/en/latest/centrality/.

~~My guess is that this occurs because h2 and h3 have similar content  and so share an id (which confuses... something?). Perhaps this would be solved by ensuring that the id is unique (e.g. by appending -1 and -2 to ids of headers which currently share the same id. Currently:~~

This occurs because in one of the markdowns there is a h1 (so h3s do not appear in the nav-bar), in the other there is no h1 (so h3s do appear in the nav-bar).

**Comment by waylan** [comment]
>     <h2 id="degree-centrality">Degree Centrality</h2>
>     <h3 id="degree_centrality">degree_centrality</h3>

If you look closely, those IDs are unique. The first uses a dash (`-`), which replaces the space in the header text and the second uses the underscore (`_`) which is carried over verbatim from the header text. In fact, the ID generating code does [check for uniqueness][1] and will append an incrementing number to ensure uniqueness.

[1]: https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/toc.py#L35

It appears that your real concern is that level 3 headers (`<h3>`) are not included in the nav menu for that page, but are in another. I'm not sure if this is related to #278 (which was fixed some time ago) or something different.

The TOC is generated by Markdown as HTML. The MkDocs parses that HTML and builds its own data structure which is passed to the template. I suppose there could be an error in MkDocs which is failing to see those IDs as unique or something. What happens if you change either the h2 or h3 to use different words? If the problem persists, then the IDs are a red herring.

**Comment by hayd** [comment]
Ah yes, how embarrassing! They are unique. They may indeed be a red-herring...

To specify the problem: In one the page the h3 appear in the nav menu, in the other only h2s.

(Personally I've worked aound #278, h3 and h4 looking the same, with custom css.)

**Comment by hayd** [comment]
Ah, I *think* this is the nav menu shows the *highest two* headers. So

- if you have an h1 it'll show h1 and h2.
- if you have no h1 but an h2, it'll should h2 and h3.

Hmmmmmm.

**Comment by d0ugal** [comment]
> Ah, I think this is the nav menu shows the highest two headers.

Yup, this is because we take the table of contents for Markdown. If you are interested in all the details, @waylan previously [wrote about it in lots of detail](https://github.com/mkdocs/mkdocs/issues/624#issuecomment-110775031).

Closing this as I don't think there are any unanswered questions, let me know if I am wrong!
