### ISSUE TITLE
Horizontal bar overlaps with menu items on the left

### ISSUE THREAD

**Issue by BentCoder** [mkdocs/mkdocs#716]
Hi,

How can I solve issue that is shown below? As you can see the grey footer horizontal bar overlaps with menu. Is there a configuration option to get rid of it?

Thanks

![screenshot from 2015-08-17 12 20 39](https://cloud.githubusercontent.com/assets/8837278/9303949/e5455650-44da-11e5-8886-15c6fd94de96.png)

**Comment by d0ugal** [comment]
Which theme is this?

**Comment by BentCoder** [comment]
cerulean

**Comment by tomchristie** [comment]
Was the close intentional?

**Comment by BentCoder** [comment]
Sorry, meant to hit Close button instead of Clone and Comment button!

**Comment by d0ugal** [comment]
I think this only happens when you have a page with many Headers and no content? So the problem should be resolved as you fill in the content on the page.

**Comment by BentCoder** [comment]
It happens when the menu section/block on the left is long no matter how big or small the content of actual page is.

Normal page:

![image](https://cloud.githubusercontent.com/assets/8837278/9334900/1dfd7f74-45c9-11e5-9208-a84a737cdcac.png)

Page with long menu:

![image](https://cloud.githubusercontent.com/assets/8837278/9334968/7e10f5e4-45c9-11e5-8a27-200656367198.png)

**Comment by BentCoder** [comment]
And also, if the menu on the left is long then you won't see all of it cos it is static/fixed.

**Comment by d0ugal** [comment]
I wasn't able to reproduce this for some reason.

**Comment by BentCoder** [comment]
If you can add many pages and then vertically shrink your browser, you'll be able to reproduce it.

**Comment by facelessuser** [comment]
I have seen this as well.

**Comment by robodude666** [comment]
I could have sworn there was a change in the last few months that caused the height of the ToC to be limited and force an overflow scrollbar to appear... unless I've been browsing [Django REST framework's docs](http://www.django-rest-framework.org/) too much recently.

**Comment by BentCoder** [comment]
Hi @d0ugal - Have you been reproduce it or any update on this bug? Thanks

**Comment by d0ugal** [comment]
No updates, I've seen it. This is a fairly small bug but I'd be happy to see a fix for it.

I am currently very short of time for open source outside of work, so I wont be looking at this soon. This will change in a bit over a month.

**Comment by squidfunk** [comment]
I solved this issue in the [mkdocs-material](https://github.com/squidfunk/mkdocs-material) template, maybe you can take this as a guideline when working on the mkdocs default theme. What I do: the drawer locks while scrolling, so it is always in view. However, if the content is far shorter than the drawer, the drawer stretches the content, so it is always fully shown. The longer element always stretches the shorter one.

This can be done by making the drawer static (= not fixed) and floating it, while performing a clear after the content (with the `:after` pseudo selector). However, in order to lock the drawer while scrolling, you need some Javascript. The No-Javascript fallback is just the drawer being static.

Well, CSS.

![css](http://i.imgur.com/Q3cUg29.gif)

**Comment by d0ugal** [comment]
Dropping this from 0.16, there isn't a clear path to resolving this. Help is very welcome.

**Comment by dareno** [comment]
<img width="707" alt="bs-sidebar" src="https://user-images.githubusercontent.com/3236970/39574963-e4667b78-4ea6-11e8-964a-e8a6decbec05.png">

I think this is the same issue. When resizing window so that the navbar is two rows it overlaps with the nav-sidebar. This image is from chrome in developer mode, inspecting the nav-sidebar. Using version 0.17.3.

**Comment by dareno** [comment]
One more detail, it seems these two classes are the ones that overlap in my case:
<img width="407" alt="overlap" src="https://user-images.githubusercontent.com/3236970/39575469-a2493d64-4ea8-11e8-8e13-f8f06719a688.png">
