### ISSUE TITLE
Documentation on the 404 feature

### ISSUE THREAD

**Issue by ThomasArdal** [mkdocs/mkdocs#732]
It seems like there's a feature in MkDocs, making it possible to specify a 404.html file in a custom template and let MkDocs show that on page not found. I cannot make it work and there's no documentation telling how to configure that.

**Comment by d0ugal** [comment]
You are correct, there is something here. I have never used this feature :) Themes can provide a 404.html by just including a 404.html in the theme, I can't remember how you create a custom one otherwise. It might just be that you need to add a 404.html file to the docs directory.

Of course, depending how you serve the built documentation, you may need to tell the server to use the 404.html. Github pages will use it automatically tho for example.

**Comment by ThomasArdal** [comment]
I don't think it works like that. Or maybe I'm doing something wrong. If you check out [this repo](https://github.com/elmahio/blog), there's a [404.html](https://github.com/elmahio/blog/blob/master/mkdocs_bootstrap/404.html) in the theme. This is succesfully [added](https://github.com/elmahio/blog/blob/gh-pages/404.html) to the gh-pages branch when doing a mkdocs gh-deploy, but GitHub doesn't use this 404 page (example: http://elmahio.github.io/blog/notfound).

**Comment by d0ugal** [comment]
Here is a working example that is also hosted on GitHub pages.

- 404: http://www.django-rest-framework.org/asdfsafasdfasd
- template: https://github.com/tomchristie/django-rest-framework/blob/master/docs_theme/404.html
- 404 build: https://github.com/tomchristie/django-rest-framework/blob/gh-pages/404.html

The [GitHub docs](https://help.github.com/articles/custom-404-pages/) suggest it is just as simple as adding a 404.html - so I am really not sure why yours wouldn't work.

**Comment by d0ugal** [comment]
...and, of course, another working example is MkDocs itself although it doesn't use a custom theme so it might be less useful to look at.

**Comment by ThomasArdal** [comment]
I see. You might need a custom domain name (CNAME file) in order for the 404 to work. I will test and let you know the result.

**Comment by d0ugal** [comment]
aha, that makes sense. I guess there isn't much point in a custom 404 if github is still in the url.

**Comment by ThomasArdal** [comment]
Works fine with the 404.html on custom domain. The MkDocs could mention this with a single line somewhere, but I'm not sure anything more is needed, since it's a GitHub Pages feature.

**Comment by waylan** [comment]
I think the ability to create your own 404 template definitely needs to be documented (any comments about gh-pages would presumably go in that documentation). However, my understanding is that no documentation exists about how to override any templates of any kind because the API is not clearly defined yet. For example, should the `404.html` template go in the `docs` dir or in the dir defined in the (optional)  `theme_dir` config setting (I would say it should only be the latter although I believe it currently works in both)?  I suspect when #607 gets resolved, this will all be more clear and a definitive API can be documented. Prior to version 1.0, this stuff may change a few times as it matures, so it hasn't been documented yet.

**Comment by JayHoltslander** [comment]
Just chiming in to say that I ended up here via Google search while trying to find more info on MkDocs and custom 404s.
