### ISSUE TITLE
Search functionality is not relevant 

### ISSUE THREAD

**Issue by Kels** [mkdocs/mkdocs#737]
Hello,

I started using mkdocs since last week, and I love it.

However, the search functionality did not retrieve exptected informations.

For example, I have a page with many How to
![error_1](https://cloud.githubusercontent.com/assets/1903909/10281465/f8f65422-6b74-11e5-8680-2e9d2504dda0.PNG)

When I search on the word how, nothing matched
![error_2](https://cloud.githubusercontent.com/assets/1903909/10281467/fb92ea92-6b74-11e5-944e-dbf7e69111b3.PNG)

Does the search feature requires some particular configuration ?

Cheers

Kelson

**Comment by d0ugal** [comment]
This is because lunr.js contains how in it's standard set of [stop words](https://github.com/olivernn/lunr.js/blob/master/lib/stop_word_filter.js#L67). This means it is basically excluded from the search as it is deemed the word is too generic.

There isn't an easy way for you to customise this, we should probably make it easier for people to hook in here somehow but I can't think how best to do that (but we need some configurability to better support non-English docs anyway).

**Comment by Kels** [comment]
Ok I understand, thanks for your explanation. 

It seems lunr.js allows only to add new stop words. There is no way to configure the default list.
Have you planned something about this topic ?

**Comment by d0ugal** [comment]
From the [lunr.js website](http://lunrjs.com/)

> By default lunr adds a stop word filter and stemmer to the pipeline. You can also add your own processors or remove the default ones depending on your requirements.

I assume this means we would need to create a custom pipeline (or modify the existing one) with a stop word filter that is different.

The bigger question is how we handle something like this. Custom themes could do this easily, so perhaps we need to look at a more generic solution here with #607. Then we don't need anything specific to Lunr.js.

For now I think we should close this and try to tackle it as part of the bigger solution discussed in #607 or #211/#617 (if the solution comes from the translation side as we need to handle non-english stop words somehow).
