### ISSUE TITLE
Create links with in index.html

### ISSUE THREAD

**Issue by ChronoWaste** [mkdocs/mkdocs#747]
Hi! I want to use my docs locally, but when I build and open any link
![captura de pantalla de 2015-11-05 00-04-35](https://cloud.githubusercontent.com/assets/13415603/10960276/0c269c70-8351-11e5-9f49-d295196e6734.png)

Is there any way to include index.html in the links ? **thanks**

**Comment by waylan** [comment]
I'm not sure I understand what your problem is. Are you saying that you want to browse the built site on the local file system (for example: `file:/path/to/some/file.html')? If so, then you need to set [`use_directory_urls`][1] to `false`. If you are trying to accomplish something else, then you will need to provide more information.

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls

**Comment by ChronoWaste** [comment]
It works, **thanks**!

**Comment by waylan** [comment]
Closing this as there is no actionable issue.
