### ISSUE TITLE
Support for Checklists

### ISSUE THREAD

**Issue by chryton** [mkdocs/mkdocs#748]
This would be very helpful when creating things like onboarding checklists; a user could keep the page open and be able to see what they have and have not completed so far.

Going with the GitHub flavored way of doing checklists/boxes, `- [ ]`, would be great.

**Comment by facelessuser** [comment]
I wrote an Python Markdown extension that does exactly that.  Mkdocs doesn't need to directly add such things as you can achieve things like this by just including Python Markdown extensions in your mkdocs.yml file.

You can see here that my mkdocs generated documents support tasklists because I used my extension: http://facelessuser.github.io/pymdown-extensions/extensions/tasklist/.  You can try it or try out other 3rd party extensions that may do the same thing: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions.

**Comment by vlcinsky** [comment]
Proposal: resolve this issue by adding instructions into documentation.

**Comment by facelessuser** [comment]
But it talks about extensions in the docs: http://www.mkdocs.org/user-guide/configuration/#markdown_extensions.

All you have to do is have extensions installed in Python, and reference them in the setting above.  I have an example here if you need one: https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml.

**Comment by d0ugal** [comment]
Happy to review doc suggestions, otherwise I think this is covered.

**Comment by waylan** [comment]
Perhaps a "recipes" page in the [wiki][1] to cover how to add various features through extensions would do the trick. I believe the wiki is editable by anyone with a GitHub account, so anyone can start one up if they like.

And @facelessuser, you have a long list of extensions all wrapped up in a single package, so it is not always easy for people to find the one feature they want. It might help if you listed them all in the list of third party extensions on the [wiki][2].

[1]: https://github.com/mkdocs/mkdocs/wiki
[2]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions

**Comment by facelessuser** [comment]
> Perhaps a "recipes" page in the wiki to cover how to add various features through extensions would do the trick. I believe the wiki is editable by anyone with a GitHub account, so anyone can start one up if they like.

That is a good idea.

> And @facelessuser, you have a long list of extensions all wrapped up in a single package, so it is not always easy for people to find the one feature they want. It might help if you listed them all in the list of third party extensions on the wiki.

I know, I know.  I haven't done an actual release yet, which is why it isn't on the wiki yet;  I haven't been trying to broadcast it widely.  I really only mention it when I see someone with a specific issue the extensions may solve.  I have started unittesting last week and have been making the final tweaks before a release.  I think I should have it all done within the week.  At that point, I will post it on the wiki.  I was just trying to avoid having a bunch of people use it knowing I may break backwards compatibility (which I have totally done this week in some areas) before I released it.

**Comment by waylan** [comment]
>  I haven't done an actual release yet,

Ah, I missed that detail. In any event, glad to hear you are making progress. There are some useful features you have in there.

**Comment by facelessuser** [comment]
> There are some useful features you have in there.

Thanks.

**Comment by waylan** [comment]
FYI, I've added a "recipe" on the wiki for this: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Recipes#add-support-for-checkbox-lists
