### ISSUE TITLE
module not loaded error

### ISSUE THREAD

**Issue by sander76** [mkdocs/mkdocs#753]
I have created a markdown extension which creates animated svgs using the snap.svg library.
I reference this using the `extra_javascript` option in my yaml file.
However, mkdocs places this javascript library at the end of the generated html file.
I now get an error in brower: Reference error: SNAP is not defined.

I know what this means, but I have no idea how to solve this. Placing the script file in the body of the html works, but mkdocs doesn't do that automatically.
Also playing around with `window.onload` etc doesn't seem to help... I am really stuck now. Anyone a good suggestion ?

Sander.

**Comment by waylan** [comment]
Is there a way you could write a script which runs after `extra_javascript` loads the lib which finds all the relevant parts of the document and calls a function for each activating it? Without your code, it is a little difficult to be of much help.

That said, it is a little odd that none of the javascript libs are loaded before the body of the document. I can see the value in having scripts load at the end (although `onload` can handle that as well), but there are legitimate reasons to have libs loaded in the head.

**Comment by sander76** [comment]
I have now changed the base.html template and moved the following inside the <head> tag at the beginning of the document:
`{%- for path in extra_javascript %}`
`      <script src="{{ path }}"></script>`
`{%- endfor %}`

It works, but I have no idea whether I am breaking things I am not aware of....

**Comment by waylan** [comment]
@sander76 I'm sure that works for your purposes, but you are right to wonder if it will break other things. In my experience, when scripts are loaded at the end of the document, it is because they are meant to run after the page has loaded (without using `onload`). Therefore, it is possible you could break other things by your move (but if it is working for you, I say leave it for now). That is why I think there should be an option to include scripts either at the beginning or at the end .

Actually, I would propose a new setting: `javascript_libs` (open to suggestions for better naming). `javascript_libs` would contain all libraries which are needed for a theme/project and would be loaded in the documents `head`. `extra_javascript` can continue to be loaded at the end as it is now. I suppose `javascript_lib` could even be automatically populated from a `lib` dir provided in the theme and/or docs_dir.

**Comment by waylan** [comment]
This was addressed in #1022.
