### ISSUE TITLE
debugging mkdocs

### ISSUE THREAD

**Issue by sander76** [mkdocs/mkdocs#767]
I want to debug a plugin I wrote using Pycharm. The problem I have mkdocs is an executable. I can see build.py which probably gets called by mkdocs. But with what parameters?

**Comment by waylan** [comment]
You can use the traditional `--help` flag to get a printout of the options available to you:

```bash
$ mkdocs --help
Usage: mkdocs-script.py [OPTIONS] COMMAND [ARGS]...

  MkDocs - Project documentation with Markdown.

Options:
  -V, --version  Show the version and exit.
  -q, --quiet    Silence warnings
  -v, --verbose  Enable verbose output
  -h, --help     Show this message and exit.

Commands:
  build      Build the MkDocs documentation
  gh-deploy  Deploy your documentation to GitHub Pages
  json       Build the MkDocs documentation to JSON files...
  new        Create a new MkDocs project
  serve      Run the builtin development server
```

You can run the same flag on any of the subcommands to get a list of options for that subcommand. For example, the build command:

```bash
$ mkdocs build --help
Usage: mkdocs-script.py build [OPTIONS]

  Build the MkDocs documentation

Options:
  -c, --clean                     Remove old files from the site_dir before
                                  building
  -f, --config-file FILENAME      Provide a specific MkDocs config
  -s, --strict                    Enable strict mode. This will cause MkDocs
                                  to abort the build on any warnings.
  -t, --theme [cosmo|united|slate|yeti|journal|readthedocs|readable|cerulean|sim
plex|flatly|spacelab|amelia|mkdocs|cyborg|bootstrap]
                                  The theme to use when building your
                                  documentation.
  -d, --site-dir PATH             The directory to output the result of the
                                  documentation build.
  -q, --quiet                     Silence warnings
  -v, --verbose                   Enable verbose output
  -h, --help                      Show this message and exit.
```

You get the idea. I'm sure you can get the options for the rest of the commands from there.

**Comment by sander76** [comment]
Couldn't ask for a better answer. Thanks !

**Comment by waylan** [comment]
When I provided the above answer, I intended to point to the docs (on mkdocs.org) where the `--help` flag is documented and noticed that it is not. Well, actually, mkdocs.org still [includes][1] the old outdated system (pre Click) were `help` was a sub-command. Of course, this has been [corrected][2] in the source code and will presumably be updated on mkdocs.org with the next release. However, that part of the docs is providing a way for the user to verify that the `mkdocs` command had been installed correctly. As the `--version` flag had existed in both newer and older version, the change switched to using that flag. I think that seems like a reasonable compromise.

Unfortunately,  the docs now make no mention of that fact that users can get help with the `--help` flag. After the "Installation" section, the docs summarize a few of the common sub-commands. Perhaps the docs should also suggest using `--help` to get a complete list of sub-commands with an explanation of how to use `--help` with each of the sub-commands as well.

[1]: http://www.mkdocs.org/#installation
[2]: https://github.com/mkdocs/mkdocs/commit/40dc17e17e5afacb044bcca7d0168ff66c9faabe

**Comment by aescott** [comment]
I'm also debugging a plugin I'm writing. I can install it and run it, that works, but it uses the installed package, under "site-packages" in my virtual env. I'd like to use the version in my repo while building it. I tried to add the path to my plugin package to my PYTHON_PATH before launching the debugger, but it doesn't find it. Is there anyway to get mkdocs to load the plugin from code inside my development repo and not the installed one?

**Comment by waylan** [comment]
@aescott yes, that is possible through a Python feature, not something specific to MkDocs. You will need to install the package in "[development mode][1]." From your repo use the `develop` command (rather than `install`):

```
python setup.py develop
```

Or use the `-e` flag with pip (`.` refers to the current directory, which should contain the `setup.py` file):

```
pip install -e .
```

In either case, a pointer is installed which tells Python to find the module at the current location rather than in `site-packages`. As you make changes to your code, those changes take effect immediately. I would recommend using a separate virtualenv for this than the one you use for production (which should have the package installed normally).

A word of caution: even in Development Mode, once a module is imported, any new changes are ignored until it is imported into a new Python instance. Therefore, if you are running MkDocs' development server, you will still need to stop and restart the server before a change will take effect (the auto-reload server does not apply to changes in Python code). However, that is much simpler than needing to reinstall the module each time.

[1]: https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode

**Comment by xie-dd** [comment]
My markdown source file name contains underlines, but the sidebar of the site page generated by serve and bulid will have the problem of missing underlines. 

So I want to debug the source code, but I don't know how to launch **__main__.py** or **bulid.py**
