### ISSUE TITLE
relative url's can cause bad links

### ISSUE THREAD

**Issue by SvenDowideit** [mkdocs/mkdocs#77]
I am deploying to s3, and then have a hidden 404 error mkdocs page - when the users enters a long (incorrect url), then the error page is rendered using that url - thus all the menu links are broken.

**Comment by ePirat** [comment]
@d0ugal What exactly do you mean with

> I'm not really a fan of relative URLs, it is only really useful for people that view the docs in __static mode__ and I'm not sure how popular a use case that is.

Static mode?

**Comment by d0ugal** [comment]
@ePirat We possibly need a better name for this, basically when you browse the documentation in your browser on the local filesystem. So links like "/" don't work as that isn't the root of the documentation.

**Comment by waylan** [comment]
The report in #1035 brought me to this issue. This is the first time I've taken a close look at it. It appears from my reading that there is some confusion about this issue. As I see it, there are two separate (unresolved) issues with relative URLs. This one and the one in #192. The issue in #192 applies only to URL munging within Markdown and is not related to this issue.

In this issue the OP encountered the same problem as encountered in #1035 (which I closed as a duplicate, but it clearly defines the user's problem and helps clear up the issue). Namely, a template renders a relative URL which is hard coded into the page. Normally, not a problem as each page is always only every at one location. However the problem exists when the same page can exist in multiple different locations. For example, error pages are served for any URL in which an error occurs. The location of any other page relative to the current URL will be different for most cases--especially now that we allow multi-level nesting. 

Of course, in dynamic servers, the error page is often regenerated each time (from a template), in which case the current URL is accounted for when rendering the template, avoiding this problem. But we don't have this option as our error page is rendered without knowledge of the requested URL. Therefore, we need nav items, etc, to point to the proper location regardless of the location of the current page. 

The easy way to do that is via absolute URLs. But, of course, we cannot assume that the server root is the same as the MkDocs root. For example, consider documentation hosted on http://pythonhosted.org as explained in [this comment][1]. The point is, we can't just assume `/` is the documentation root on the server. It may be `/projectname/` or `/username/projectname/` or some other thing.

Previous comments have mentioned adding some sort of new config setting. That should be unnecessary. We already have the [`site_url`][2] setting. If a project's documentation root is at `http://example.com/projectname/`, then that is going to be the value assigned to `site_url`. We can extrapolate from that that any absolute URL should have prepended `/projectname/` to it to be a proper absolute URL.

Of course, there is the issue of the dev server (livereload or not) in which the server root is always the same as MkDocs root. But that should not be a problem as we also have the [`dev_addr`][3] setting. If that is set, just extrapolate the root from that rather than `site_url`. Coincidentally, I find it strange that this config setting exists. Yes, it should exist as an option on the `serve` command, but shouldn't the value just be passed into the config as an override of the `site_url` setting during development?

So my proposal would be that the [`base_url`][4] template variable be the absolute path from the server root to the MkDocs root. To illustrate, here's some examples of what the `base_url` template variable should contain depending on the value of the `site_url` config setting:

| `site_url`                                           | `base_url`        |
| -------------------------------------- | --------------- |
| `http://example.com/`                     | `/`                    |
| `http://example.com`                       | `/`                    |
| `http://example.com/foo/`               | `/foo/`             |
| `http://example.com/foo`                | `/foo/`              |
| `http://example.com/foo/bar/baz/` | `/foo/bar/baz/` |
| `http://127.0.0.1:8000` (from `dev_addr`)  | `/`             | 


[1]: https://github.com/mkdocs/mkdocs/issues/192#issuecomment-75322787
[2]: http://www.mkdocs.org/user-guide/configuration/#site_url
[3]: http://www.mkdocs.org/user-guide/configuration/#dev_addr
[4]: http://www.mkdocs.org/user-guide/custom-themes/#base_url

**Comment by waylan** [comment]
For completeness, I should point out that browsing files via the local file system (`file://`) will break with absolute URLs every time. Of course, currently it is broken anyway (search won't work), but if we want to support that, then absolute URLs are out. In that case, I would propose using absolute URLs on error pages only (as described in my previous comment). Error pages are server specific and don't get returned by the local file system on an error, so it should be okay if they are broken in that instance. The trick is how to address the nav on error pages. If the nav contains relative URLs, those URLs still need to be absolute on the error page. Perhaps the error page should only contain a link to the homepage, not the entire nav.

**Comment by waylan** [comment]
Warning, the following is a complicated explanation of how the code works. Sorry, but explaining it is part of how I work out solutions, which you'll find at the end.

I think the key to fixing this issue is to understand how the URLContext works. The 'short' explanation is that in `mkdocs.commands.build.build_pages` we have the loop: `for page in site_navigation.walk_pages():` The key is in the `walk_pages` method. That method sets a page as "active" and yields it. `build_pages` then takes that page and builds it (renders Markdown and template, then writes to disc). The `url` property of each page is a method which makes a call to the `URLContext` using the "active" page to create URLs which are relative to that "active" page (the entire loop through the nav in the template happens with this one page set as "active"). After the page is built, the loop (in `build_pages`) continues, asking `walk_pages` for the next page. `walk_pages` then deactivates the current page and activates the next page before yielding it. The entire thing is dependent on the global "active" page and URLContext and the fact that we are in a synchronous system (it would never work in an asynchronous environment). That is how each page is generated with a complete nav where all the URLs are relative to that page with absolutely no consideration for the location of the current page in the template. Its a clever piece of code which removes the need for the template care about relative URLs.

However, there are pages which do not get this treatment. Specifically, any page which is not listed in the `pages` config setting. As it happens, all those pages are template based pages, such as error pages, `sitemap.xml`, `search.html` and anything in the `extra_templates` config setting. The key difference is that for these pages there is no "active" page, in which case the URLContext defaults to assuming an "active" URL of `/`. Of course, `search.html` is at the site root (as it `sitemap.xml`) so the relative paths in the nav are correct. However, `extra_templates` could be nested at any location (I assume this is an unreported bug as its a little used feature). Presumably, setting the "active" page in the URLContext to the path of the current template would build a proper nav for that page (untested, but I think it should work). 

But for error pages it's a little more tricky. As discussed previously, error pages could be served at any URL nested at any level by the server. There it no correct "active" page to make nav items relative to. Therefore, I propose that if there is no "active" page, rather than the default being to generate a URL for a page relative to `/`, instead generate an absolute URL with the base extrapolated from `site_url`. This absolute URL should then be returned by the `mkdocs.nav.Page.url` method when the error template builds it's nav.

**Comment by waylan** [comment]
I have a working solution in #77. It took a few iterations, but I have the least invasive patch possible (added 9 lines of code, not counting tests and comments). Only the error page is affected, everything else continues to behave as before.

**Comment by csandanov** [comment]
@waylan there's so much information and changes regarding the URLs I'm confused whether there is a solution to [my problem](https://github.com/mkdocs/mkdocs/issues/192#issuecomment-419387997) described in #192 or not. Is it possible to make mkdocs generate absolute URLs (to avoid 404 by search crawlers) or not? I realize there are variables I can use in theme templates to get absolute URLs in navigation but what about markdown links in `.md` files? Relative URLs `../` generate tons of 404 errors by search crawler.

**Comment by waylan** [comment]
@csandanov please open a new issue and provide examples describing your problem.
