### ISSUE TITLE
use_directory_urls has no effect when .md is omitted from link

### ISSUE THREAD

**Issue by ewan-sinclair** [mkdocs/mkdocs#794]
Links of this style: `[Link Title](directory/some_page.md)` are affected as expected by `use_directory_urls`

Links of this style: `[Link Title](directory/some_page)` will always be produced as if `use_directory_urls` was set to `true`

**Comment by waylan** [comment]
I believe this is expected behavior. Only links which end with `.md` are manipulated. It just so happens to be that a URL like `directory/some_page` matches the URLs for pages when `use_directory_urls` is `True`. However, that is coincidental, not intentional.

It may help to realize that while `use_directory_urls=True` is the programmed default of MkDocs, the actual default behavior of Markdown would be closer to the behavior you get when `use_directory_urls=False`.

In any event, when `use_directory_urls=False` then all that happens is that any link which ends in `.md` has the file extension replaced with `.html`. If there is no `.md`, then what should MkDocs do? It does nothing right now, which seems like the correct action to me. If you want `directory/some_page` style links, then you should set `use_directory_urls=True`.

**Comment by d0ugal** [comment]
Yup, I think this is the expected behaviour, we have no idea that it is a markdown file if you don't include the extension.

**Comment by Tset-Noitamotua** [comment]
Sorry for asking it here but I cant figure out how to  use `use_directory_urls`. I am aware of it beeing mentioned in documentation [here](http://www.mkdocs.org/user-guide/configuration/#use_directory_urls). But it's usage is not clear to me though. Is it a CLI option or do I have to put it somewhere in `mkdocs.yml`?

Cheers
Tset

**Comment by waylan** [comment]
@Tset-Noitamotua the [documentation][1] you point to is a list of configuration setting to be defined in the `mkdocs.yml` file. Everything on that page is controlled via the config file. A few settings can be overridden by the CLI, but those are documented by the CLI (via the `--help` flag for each command).

[1]: http://www.mkdocs.org/user-guide/configuration/#use_directory_urls
