### ISSUE TITLE
Menu with image ?

### ISSUE THREAD

**Issue by zemadmat** [mkdocs/mkdocs#806]
Hi,

I have try MDWIKI which allow to have an image in the menu instead of the text. (https://dynalon.github.io/mdwiki)
Is it possible in mkdocs to have something similar ?

Cheers

**Comment by waylan** [comment]
I just looked at MDWiki but didn't see anything about how to use an image in a menu item. How are expecting this to work? Perhaps if I better understood what you want to do, I can provide some guidance.

**Comment by zemadmat** [comment]
Sure, the navigation menu in MDWiki looks like this
```
[![](./images/ic_home_black_36dp.png)](#!index.md)

[![](./images/ic_school_black_36dp.png)]()

 * [F5](KB/F5/index.md)
 * [Linux](KB/Linux/index.md)
 * [Microsoft](KB/Microsoft/index.md)
 * [SNMP](KB/SNMP/index.md)
 * [SolarWinds](KB/SolarWinds/index.md)

[![](./images/ic_bookmark_black_36dp.png)](Perso-Bookmark.md)

[![](./images/ic_local_restaurant_black_36dp.png)]()

 * [Entree](Perso/Recettes/Entree/index.md)
 * [Plat](Perso/Recettes/Plat/Plat.md)
 * [Dessert](Perso/Recettes/Dessert/index.md)
```
This done the following mmuller.free.fr
As you can see the menu item are images. 

That's something i'd like to have.

Cheers

**Comment by waylan** [comment]
In MkDocs, the text of the menu items are determined by page titles, which you can define in the `pages` configuration setting (see [docs](http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)). As it stands today, the text is simply inserts as the label in the menu links. No processing is done, so you can't use Markdown to create image links. And I expect, due to template escaping, setting the title to an HTML `img` tag won't work either. This is an interesting feature request.

Although, it may be possible with CSS. You can find a whole bunch of methods described here: <https://css-tricks.com/the-image-replacement-museum/>. Just [tell MkDocs](http://www.mkdocs.org/user-guide/configuration/#extra_css) to use your custom CSS.

**Comment by d0ugal** [comment]
At the moment I don't think it is likely that we will be able to support this. It seems like it could be a reasonable feature request but it isn't that common. It might be that we can support this later with better customisation or perhaps this would require a plugin which may be possible one day.

**Comment by jaxxzer** [comment]
Any updated thoughts on this? I would like the same sort of thing in the `nav:` configuration.
