### ISSUE TITLE
utf-8 search support

### ISSUE THREAD

**Issue by coffeetalkh** [mkdocs/mkdocs#826]
Hey, we are working on a Persian version of a mkdocs theme, everything works fine but we have a problem on search contents with Persian contents, when i search the expression nothing found, i also test it with Arabic, Chinese and Hebrew and all of theme have problem with this case. any solution?

**Comment by d0ugal** [comment]
Unfortunately search wont work well in non-latin character sets at the moment. We use [lunr.js](http://lunrjs.com/) to provide the search functionality, I believe it can work with them but I am not sure what is involved in making that happen.

It is possible for themes to overwrite and completely replace the search implementation. To do this, themes would need to at least replace [this file](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/assets/search/mkdocs/js/search.js) (or modify the theme so that file isn't loaded) by including a javascript file in the theme with the path `mkdocs/js/search.js`. However, as I said at the top, I have no experience in making search work for different character sets, so I don't know how difficult it will be.

We could also consider adding a setting to disable search. While this isn't ideal, it would be better to turn search off than have it in a broken state.

I don't think there is a good, easy solution for this at the moment. :disappointed:

**Comment by waylan** [comment]
There is also some related discussion in #859.  Apparently, non-English search indexes are extremely large as lunr.js only "excludes" insignificant English words from the index by default. [MihaiValentin/lunr-languages][1] appears to be an add-on to lunr.js which adds support for various other languages including Japanese and Russian (both use non-latin alphabets). Unfortunately, at this time, Persian,  Arabic, Chinese and Hebrew are not on the list of supported languages. Although there are currently outstanding requests for [Arabic][2] and [Chinese][3] to be added. If you would like to have support added for a certain language, I would suggest starting there. If/when, mkdocs adds language support, then your language will work if its supported by lunr.js.

[1]: /MihaiValentin/lunr-languages
[2]: /MihaiValentin/lunr-languages/issues/9
[3]: /MihaiValentin/lunr-languages/issues/17

**Comment by netroby** [comment]
https://github.com/mkdocs/mkdocs/blob/master/mkdocs/commands/build.py#L223

json dump to utf-8?

**Comment by waylan** [comment]
@netroby, that is some old legacy (now deprecated) code which will be removed in the next major release. It has nothing to do with the current search implementation or any future updates to search.

**Comment by waylan** [comment]
In a brief [discussion][1] about how to pass config settings to lunr.js, @squidfunk pointed out that the Material (third party) theme passes the values in  via meta tags in the template (`<meta name="lang:search.language" content="en">`). However, it occurred to me that the document still has `<html lang="en">` at the top. Obviously, if the documents contain something other than English content (requiring a search lang other than en), then perhaps the `html` tag should indicate that. In fact, [Declaring language in HTML][2] seems to indicate as much.

Therefore, I'm thinking that we approach this in two ways:

1. Create a global `lang` config setting which is used as `<html lang="{{ config.lang }}">` in the template. Search could then use this as a default language to use if one is not otherwise specified.
2. Create a search plugin specific `lang` setting which can contain multiple language codes. Lunr supports indexing multiple languages and multiple languages can exist on one page. However, only one language gets defined in the `html` tag (see [Declaring language in HTML][2]). The plugin specific setting should include all possible languages for that site that will be indexed (see [Multi-Language Content][3] in Lunr docs).

Finally, rather than using the `meta` tags to pass the plugin specific settings, I'm inclined to include them in the JSON index file as so:

    { 'docs': [...], 'config': { 'lang': ['en, 'es'], 'otherkey': 'value'} }

Of course, any third party theme can ignore those. For example, Material would continue to work without changes (except to use `config.plugins.search.lang` rather than `config.extra.search.lang` as the source of its data to populate the meta tag).

[1]: https://github.com/mkdocs/mkdocs/issues/1319#issuecomment-362295804
[2]: https://www.w3.org/International/questions/qa-html-language-declarations
[3]: https://lunrjs.com/guides/language_support.html#multi-language-content

**Comment by waylan** [comment]
I just realized that having a global `lang` config setting (which sets `<html lang="en">`) means we also need to have Internationalization support for hardcoded text in templates (see #211). And I'm unsure how that will work with pages in different languages (see #774). I think at this time it makes sense to implement the search config setting (part 2 above) and leave the global setting to be implemented as part of #211 and/or #774.

In the meantime, the search config setting `plugins.search.lang` should probably default to `['en']`, which is consistent with the current behavior.

Or perhaps all multi-language support matters should be addressed together, in which case this issue would be delayed to be addressed with #211 and #774 rather than as part of the search refactor.

**Comment by waylan** [comment]
I almost have language support working. I was able to get it working within a worker in 6034dc2. I tried to adapt that to also run in the main thread in db1a84a as a fallback for browsers which don't support workers,  Unsurprisingly, it fails as the scripts are not finished loading before the code attempts to run. I understand how to use a callback to avoid that sort of problem, but it is not obvious to me here how to make that work when we have multiple potential scripts which could be loaded and those calls are all nested within various conditionals.  JavaScript's async nature is my biggest weakness.

@yeraydiazdiaz I started with your code. Any suggests from you or anyone?

**Comment by waylan** [comment]
For the record, you can see all of my recent search related work (including the code this builds on) at https://github.com/mkdocs/mkdocs/compare/master...waylan:new-search.

**Comment by yeraydiazdiaz** [comment]
Nice job adding language support.

[I tweaked your version](https://github.com/yeraydiazdiaz/mkdocs/commit/7c81e905c613476609d9e934001f7228d6c88085) slightly to have a separate process where we first load the JSON, then resolve the Lunr files to fetch, grab them asynchronously and finally activate the search. Seems to work well with and without Web Worker support.

Give it a go and let me know what you think.

**Comment by yeraydiazdiaz** [comment]
I managed to solve the issue by [abusing `$.getScript` callbacks](https://github.com/yeraydiazdiaz/mkdocs/commit/f60bfbf20ed04c7dab3deadf5f99c89f33c61db3#diff-f73d2dd58a95b278b4c4f418a7544059R8), pretty awful but I guess it beats using require.js just for old browser support.

Here are the changes the full changes against your branch [`waylan:new-search...yeraydiazdiaz:new-search`](https://github.com/waylan/mkdocs/compare/new-search...yeraydiazdiaz:new-search).

**Comment by waylan** [comment]
I considered recursively loading each script but it wasn't obvious to me how to make it work. Nicely done.
