### ISSUE TITLE
Make string "Docs" in breadcrumbs configurable (readthedocs theme)

### ISSUE THREAD

**Issue by bostjan** [mkdocs/mkdocs#854]
Hello maintainers,

would you consider it a valuable addition if I created a pull request that makes the fixed string "Docs" in breadcrumbs in readthedocs theme?

Thanks for your feedback,
b.

**Comment by bostjan** [comment]
Line 3 in this file:
https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/breadcrumbs.html#L3

**Comment by waylan** [comment]
Not sure how you anticipate allowing the user to set their preference, but we generally try to keep the number of config setting to a minimum. It seems to me that this would fall under theme customization as outlined in #607.  In other words, this is a small part of a much bigger refactor and should be closed in favor of #607.

**Comment by d0ugal** [comment]
is the motivation for this translation?

**Comment by bostjan** [comment]
@d0ugal : No, "branding" actually. Not branding per-se, but to replace "Docs" with something more suitable for my use case, as Docs is totally meaningless to intended audience.

**Comment by waylan** [comment]
@bostjan in case is wasn't obvious from a reading of #607, you can point the [`theme_dir`][1] setting to a custom theme dir and copy the `breadcrumbs.html` template to it, make your change (replace "docs" with your chosen word) and it will be used instead of the template included in the theme. I realize that it may be less than ideal to have to replicate the entire `breadcrumbs.html` template, but it is a solution that works today.

[1]: http://www.mkdocs.org/user-guide/configuration/#theme_dir

**Comment by bostjan** [comment]
@waylan thanks for specifically pointing that out. I did check it out now it works for me.

I think the problem is that neither http://www.mkdocs.org/user-guide/configuration/#theme_dir nor http://www.mkdocs.org/user-guide/styling-your-docs/ say anything about the feature you pointed out.

I wrote the feature request because I did not want to go down the own-theme-way, as you need to keep it in sync with updates almost manually. This override-single-file approach is very nice to the user.
