### ISSUE TITLE
How to create custom theme

### ISSUE THREAD

**Issue by jottr** [mkdocs/mkdocs#862]
I would like to create a custom theme for our documentation (using the readthedocs template as a starting point).
I can't find any info on how to do that in mkdocs documentation.
Could I simply create a theme folder and place it in my mkdocs project root? 
Is there a specific reason why this is not publicly documented?

**Comment by jottr** [comment]
Oh I just noticed that you guys are also using the github wiki for documentation. That's quite confusing. 
Maybe you could add a reference to it on mkdocs.org?

**Comment by d0ugal** [comment]
> I would like to create a custom theme for our documentation (using the readthedocs template as a starting point).
> I can't find any info on how to do that in mkdocs documentation.
> Could I simply create a theme folder and place it in my mkdocs project root? 

Have you read the reasonably detailed [custom themes](http://www.mkdocs.org/user-guide/custom-themes/) page? There is a `theme_dir` config option that you can use to use a local theme, you can see an example of it being used in the [mkdocs-bootswatch](https://github.com/mkdocs/mkdocs-bootswatch/blob/master/mkdocs.yml#L10) project. The `theme_dir` setting isn't well documented, [we should improve that](https://github.com/mkdocs/mkdocs/issues/863).

> Is there a specific reason why this is not publicly documented?

MkDocs is maintained by volunteers in their spare time, any documentation that is missing is likely due to this. If you can list in more detail what you think is missing or how it can be improved, then hopefully somebody will be able to do it at some point. Or, better yet, once you have figured it out you could add to the documentation.

> Oh I just noticed that you guys are also using the github wiki for documentation. That's quite confusing. 
> Maybe you could add a reference to it on mkdocs.org?

We are not using the wiki for documentation. We are using the wiki for community resources - such as a list of community themes. This is a fairly new initiative, if you have a suggestion to make this intention clearer, please let me know. We do link to it in a couple of places from the documentation, however, if you think it should be referenced in other places please let me know.

I don't think there is anything specifically actionable in this issue, so I am going to close it. However, feel free to ask more questions or open new github issues for specific areas we can improve.

**Comment by waylan** [comment]
You may also find some of the comments in #607 helpful. I suspect that part of the reason for the lack of documentation is that we have not yet solidified exactly how we want to allow users to customize themes. The comments in #607 discuss the options and in so doing, explain how some of the system works. Some of things discussed there already work (although not documented) while other things have yet to be added (if they ever will be).

**Comment by jottr** [comment]
Thank you everyone for the pointers!
Can't wait to incorporate mkdocs into my workflow.
