### ISSUE TITLE
Provide more detailed documentation for `theme_dir`

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#863]
As per the title, this came up in #862

**Comment by waylan** [comment]
This is probably very closely tied to #607 and, in part, waiting for decisions and work to be done there so we know what to document.

**Comment by d0ugal** [comment]
True, it would be good to better document what the current state is and what is possible tho' - since we don't have any timeline for #607 documenting the current situation will help some people.

**Comment by waylan** [comment]
We have an existing document: [Custom Themes][1], which is a "guide to creating and distributing custom themes". But we also have the [`theme_dir`][2] config setting, which "[l]ets you set a directory to a custom theme." And then we have the documentation section: [Customising a Theme][3] on the Styling your Docs page, which explains the `extra_css` and `extra_javascript` configuration options.

I'm assuming the documentation discussed in this issue should go under "Styling Your Docs | Customising a Theme" alongside the `extra_css` and `extra_javascript` configuration options. However, it should explain how the `theme_dir` option can be used to override various parts of the theme (the user has two options: use the `theme_dir` or use the `docs_dir` with `extra_css` and `extra_javascript`). 

That is simple enough. The problem is that if you want to build your own third party theme, that is also called **"Custom Themes"** and even uses the word "custom" in the URL. However, what is really being discussed is how to create your own "Third Party" themes, not make slight customizations to existing themes. My point is that the word "**custom**" feels a little overused here.

[1]: http://www.mkdocs.org/user-guide/custom-themes/
[2]: http://www.mkdocs.org/user-guide/configuration/#theme_dir
[3]: http://www.mkdocs.org/user-guide/styling-your-docs/#customising-a-theme
