### ISSUE TITLE
Search not working in local files/file URLs

### ISSUE THREAD

**Issue by phystem** [mkdocs/mkdocs#871]
Search is working as long as the document is running on server.
After taking the build, if the file is opened in **Chrome**/**IE **the search is being blocked
But it's working perfectly fine in **Firefox**

The error in chrome

```
GET file://fonts.googleapis.com/css?family=Ubuntu net::ERR_FILE_NOT_FOUND
text.js:307 XMLHttpRequest cannot load file:///xxx/Help/mkdocs/js/search-results-template.mustache. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.text.get @ text.js:307text.load @ text.js:187(anonymous function) @ require.js:22(anonymous function) @ require.js:8q @ require.js:12Z.callPlugin @ require.js:20Z.fetch @ require.js:17Z.check @ require.js:19Z.enable @ require.js:23(anonymous function) @ require.js:21(anonymous function) @ require.js:8(anonymous function) @ require.js:23v @ require.js:7Z.emit @ require.js:23Z.check @ require.js:19Z.enable @ require.js:23Z.init @ require.js:17E @ require.js:14i.completeLoad @ require.js:28i.onScriptLoad @ require.js:29
text.js:307 XMLHttpRequest cannot load file:///xxx/Help/mkdocs/search_index.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

**Comment by waylan** [comment]
Yes, cross origin requests are not permitted with `file://` requests. This is normal behavior by browsers with stricter security settings. If you want search to always work, it needs to be served from the same server as the pages. File based access is severely limited in that way. You need to place your files behind a server (partly why MkDocs ships with dev server) or disable your browser's security features (not recommended). There is nothing we can do to change that. As this is not an actionable item, I'm closing this.

**Comment by psifertex** [comment]
I realize the current search system doesn't work offline because it's generating the index dynamically, but I did want to point out it /is/ possible to do offline search with a different approach. Sphinx generated documentation does it by pre-generating the javascript index for the search.

**Comment by waylan** [comment]
@psifertex, that is a work in progress. See #859 for details.

**Comment by waylan** [comment]
I took another look at this. Even if we pre-generate the index, that index is still a JSON file which is not accessible with the `file://` scheme. 

Search is now in a plugin. If you really need this, then you can create your own plugin which uses some other search implementation.

**Comment by psifertex** [comment]
Given the merged PR in #1418 does that mean offline search is now possible? If so, am I just missing where the documentation is on that feature?

**Comment by waylan** [comment]
@psifertex no, online search is not possible due to browser security features, which we have no control over. The search refactor remained backward compatible with existing third party themes. To avoid the browser security limitations would have required breaking that backward compatibility in ways we were not willing to do.

To be clear, I don't expect the included search plugin to ever support offline searching. That would need to be implemented as a third-party plugin which replaces the builtin plugin.

**Comment by psifertex** [comment]
Again, offline search is absolutely possible, just not with a run-time computed index which is itself not the most efficient way to do it anyway.

I'm interested in potentially working on this as a plugin. Can you clarify what backward compatibility would be broken by precomputing an index?

**Comment by waylan** [comment]
First, we do offer a a precomputed index as an option. However, due to the dependencies it requires, and the fact that it isn't as reliable, it is not the default.

And yes, offline search it possible, but that would require providing the index (precomputed or not) as JavaScript (in a script tag) rather than an JSON which is retrieved by the code. However, at the time of the refactor, the existing third-party themes were already expecting the JSON file. Therefore, to avoid breaking them, we did not change aka that change. An additional complication is that we moved to a web worker, which makes it even more difficult.

As an aside, themes popular third party theme (Material) recently added support for the precomputed index. However, it has never ben a requirement that themes must support that, so we cannot switch to that as the default.

Speaking of Material, while that theme uses the provided "index" file (precomputed or not), it uses that file to implement its own search which worked differently than what is provided by the plugin. In fact, that is why the existing plugin has the option to disable everything except generating the index.

My point is that there are a lot of moving parts and many factors that came into play when creating the plugin. All of these matters were discussed in detail in various issues and PRs here on GitHub.
