### ISSUE TITLE
tests assume package will be unpacked into "mkdocs" directory

### ISSUE THREAD

**Issue by brianmay** [mkdocs/mkdocs#923]
The following tests assume that mkdocs will be unpacked into a directory called "mkdocs". This is often not the case, e.g. the source downloaded from github and PyPI calls it ``mkdocs-0.15.3``.

https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/config/config_options_tests.py#L182
https://github.com/mkdocs/mkdocs/blob/master/mkdocs/tests/config/config_options_tests.py#L182

**Comment by d0ugal** [comment]
Interesting. Why is this a problem? Are you attempting to run the tests against a version installed from PyPI?

**Comment by brianmay** [comment]
My point was that there are a lot of different ways of building the package and you really *cannot* make assumptions what the directory name used is.

In my particular case the tests are run as part of the process of building the Debian package, and the Debian source is called "python-mkdocs" so this is what I called the source directory. If you checked out the Debian source package using dpkg-source you would get python-mkdocs-0.15.3 instead.

Similarly, for another work flow I might want to have a mkdocs.old and a mkdocs directory, and compare the differences between the two. Why should the mkdocs.old tests break just because I renamed the directory?

The test is broken.

**Comment by d0ugal** [comment]
Sure, happy to accept a fix for this. Thanks for the extra information.

**Comment by brianmay** [comment]
I stuffed up the reference to the second file that has this problem. In 
mkdocs/tests/config/config_tests.py

Unfortunately the patch does not fix the problem, I think it illustrates confusion as to what I am talking about. I am not talking about the module directory - that is always going to be ``mkdocs``. Rather I am talking about the top level source directory tree.

Just to be clear this is *not* a Debian specific issue. If you think it is Debian specific, you haven't understood the problem.

e.g. If I checkout mkdocs as follows:

```
git clone https://github.com/mkdocs/mkdocs.git mymkdocs
cd mymkdocs
python3.5 ./setup.py test
```

I now have the source tree under the "mymkdocs" directory instead of "mkdocs".

The tests should pass. Before this change however, it would look for the directory ``../mkdocs/docs`` which is incorrect. After this change it still looks for the directory ``../mkdocs/docs`` which is still incorrect. The correct directory in this case is ``../mymkdocs/docs``.

```
In [2]: import os

In [3]: import mkdocs

In [4]: mkdocs_pkgdir = os.path.basename(os.path.dirname(mkdocs.__file__))

In [5]: import os.path

In [6]: os.path.join('..', mkdocs_pkgdir, 'docs')
Out[6]: '../mkdocs/docs'
```

Actually right now in git there seems to be a number of failures in the tests, this is only one of them.

**Comment by d0ugal** [comment]
I miss-read the change and thought that is what it was doing what you describe I am fairly sure I do understand the issue and realise it isn't Debian specific - just a use-case nobody has brought to us before.

I'll be able to do an update later today.

**Comment by brianmay** [comment]
To be fair, I misread the change at first too. It wasn't until I tested it that I realized it was incorrect :-(

**Comment by waylan** [comment]
Sorry, I misunderstood your report. My understanding was that you were saying that the directory in which the package was installed may be different, not that the parent directory of a working copy of a git checkout may be different. In retrospect, the later makes much more sense. In any event, this should do the trick then:

```python
dir = mkdocs.__file__.split(os.sep)[-3]
```
Note we just move one directory up the chain. The `split` should give you `['some', 'path', 'to', 'mymkdocs', 'mkdocs', '__init__.py`] and we want the third back from the end (`[-3]`). The previous fix gave us the second back from the end (essentially `mkdocs.__file__.split(os.sep)[-2]`). And as anyone can place their repo anywhere within their file system, we always want to count back from the end, rather than from the front.

My only concern is that `split(os.sep)` may be to simplistic and could fail on some oddly configured system. Unfortunately, no functions in the `os.path` lib give us multiple levels of split in one call.

**Comment by waylan** [comment]
> My only concern is that `split(os.sep)` may be to simplistic and could fail on some oddly configured system. Unfortunately, no functions in the `os.path` lib give us multiple levels of split in one call.

As I understand it, the only benefit of using the functions provided in `os.path` is that they use the separator in the appropriate type (bytes or Unicode) depending on the type of the path they are operating on. In other words, they use a byte string for the separator if the path is a byte string or a Unicode string for the separator if the path is a Unicode string (see [here][1] for example). Shouldn't be difficult to replicate that behavior here.

[1]: https://hg.python.org/cpython/file/tip/Lib/posixpath.py#l39

**Comment by waylan** [comment]
Something has been bothering me about this and I feel compelled to mention it. Why do the tests step outside the code base at all? We have no control over anything outside the code base/repo, so ideally we would not have any tests which relied on such externals (with perhaps library dependencies being an exception). I assume this has largely been a non-issue as we use tox internally ( I haven't checked if tox actually eliminates the problem reported here). The tox tool will create virtual environments in a consistent manner and should always give us consistent environments. But it would be wrong to "require" everyone to use tox for running the tests (even if it would be preferable).

Perhaps the correct solution is not to patch the tests with a `__file__` call, but to actually change the tests to stay within the confines of the project. For example, the [integration][1] tests already include a number of sample documentation instances. Why not use one of those (or create a new one) for these types of tests rather than using the actual MkDocs documentation as the sample. The integration samples are buried (3 levels) deep within the repo/package and we have complete control over the surrounding environment, parent directory, etc.

[1]: /mkdocs/mkdocs/tree/master/mkdocs/tests/integration

**Comment by d0ugal** [comment]
> Something has been bothering me about this and I feel compelled to mention it. Why do the tests step outside the code base at all?

No special reason 😄  Just the normal reasons that cause me to (often? occasionally?) make poor coding choices.
