### ISSUE TITLE
Remove prev next from navigation

### ISSUE THREAD

**Issue by huegelc** [mkdocs/mkdocs#946]
Hi,

how can I remove prev/next items from navigation? Is there a option in `mkdocs.yml` ?

**Comment by waylan** [comment]
Have a l look at #633 in which the `include_next_prev` config option is being deprecated (which explains why it is not documented). As noted in the last comment on that issue, users should remove the next/prev links via theme customization as discussed in  #607.

**Comment by gringolalia** [comment]
Could you provide a quick step-by-step? I do not understand! Where are the theme files and templates located and how can I edit them? Newbie sorry.

**Comment by waylan** [comment]
@gringolalia you don't "edit" the templates, but you override them either through replacement files or through template inheritance. However, the mechanisms for doing that are not fully implemented in the current release (0.15), but will be in the next release (0.16). That release will also include extensive documentation about how to override various parts of the templates. For a preview, you can view the pending updates to the documentation here: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/styling-your-docs.md#customizing-a-theme. Note that "Template Blocks" are completely missing from the version 0.15 (they hadn't been implemented yet) and some of the other stuff has been tweaked a little since that release. In other words, those are the docs for the new upcoming features. Things currently don't work exactly that way (mostly but not quite), but its the best we have. Hopefully the next release will happen soon and everything will work as documented there.

**Comment by bretonio** [comment]
Looking forward to it thx!

**Comment by oprypin** [comment]
The current link is https://www.mkdocs.org/user-guide/customizing-your-theme/#overriding-template-blocks and indeed it works as described: you can add an *empty* `{% block next_prev %}{% endblock %}` to override the existing one, both for `readthedocs` theme and `mkdocs` theme:
https://github.com/mkdocs/mkdocs/blob/e1b77ab66e8305b5f0373b4842b50d2618390a96/mkdocs/themes/readthedocs/footer.html#L2
https://github.com/mkdocs/mkdocs/blob/e1b77ab66e8305b5f0373b4842b50d2618390a96/mkdocs/themes/mkdocs/base.html#L113

**Comment by oprypin** [comment]
OK so... you're doing *something* (we don't know what) and you're getting errors.

If you can't figure those out, perhaps go to https://github.com/mkdocs/mkdocs/discussions and open a new thread **with full context**: MkDocs version, what you did, what you're seeing (you provided only the latter)

**Comment by oprypin** [comment]
> If you can't figure those out, perhaps go to https://github.com/mkdocs/mkdocs/discussions and open a new thread

**Comment by oprypin** [comment]
1. You are copying a file from MkDocs 1.2.3 and slotting it into MkDocs 1.1.2. That version indeed had no support for translations, so it trips over that.

2. I'm pretty sure that copying the whole file shouldn't be necessary. As per the guide (but I haven't checked this myself), I'd expect that you'd need just the file `main.html` with **just** this content:
    ```jinja
    {% extends "base.html" %}

    {% block next_prev %}{% endblock %}
    ```
