### ISSUE TITLE
Markdown image directive and html <img> have different paths.

### ISSUE THREAD

**Issue by ostrokach** [mkdocs/mkdocs#991]
I am trying to use MkDocs to publish some of the notes that I have been writing in markdown.

Sometimes I there are large images that I wish to include in my docs. Since markdown does not allow you to specify the width of the image, I resort to using the html `<img>` tags.

For example, in my `todo.md` file, instead of:

```
![My large image](todo/my_large_image.png)
```

I have:

```
<p align="center">
<img src="todo/my_large_image.png" width="600px" >
</p>
```

However, while the markdown tag renders correctly, the html one does not. MkDocs looks for the image  `todo/todo/my_large_image.png`. This is inconsistent with every markdown editor that I have tried, and GitLab markdown edit.

Any suggestions?

(and thanks for MkDocs, it looks great! :))

---

```
$ python --version
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

$ mkdocs --version
mkdocs, version 0.15.3
```

**Comment by waylan** [comment]
As [documented][1], MkDocs will alter internal links. Depending on how the [`use_directory_urls`][2] setting is configured, the path to a page can change, so MkDocs adjusts the links to compensate. This behavior is on top of standard Markdown. However, it only applies to links made with Markdown syntax. Raw HTML is ignored, which explains the inconsistent behavior you are seeing. 

I understand why you are using Raw HTML, but I'm not clear on which links are "broken" (fail to point to the actual image). Is it the altered Markdown links which are incorrect (which means we have a bug), or are the raw HTML links incorrect (which means you will need to use something different to link to your images)?

[1]: http://www.mkdocs.org/user-guide/writing-your-docs/#linking-documents
[2]: http://www.mkdocs.org/user-guide/configuration/#preview-controls

**Comment by ostrokach** [comment]
Thanks for the reply!

It is the raw html links that are rendered incorrect. The name of the markdown file containing the link gets prepended to the link. For example, if I have a link `todo/my_large_image.png` inside a mardown file `todo.md`, the link becomes: `todo/todo/my_large_image.png`. This is assuming the following directory structure:

```
+-- todo.md
+-- todo
    + my_large_image.png
```
I can get the links to work correctly by adding `..` (e.g. `src="todo/my_large_image.png"` becomes `src="../todo/my_large_image.png"`). But then the images are not rendered correctly in every other MarkDown editor.

**Comment by waylan** [comment]
> This is assuming the following directory structure:

>     +-- todo.md
>     +-- todo
>         + my_large_image.png

Ah, I see your problem. If you have `use_directory_urls=True` (the default), then you get:

    +-- todo/
        +-- index.html
        +-- my_large_image.png

But, MkDocs does not account for your img being in a directory with the same name as your Markdown file, so it steps you out (with `../`) and then steps back in (with `todo/`). If you were starting with this structure (where the img dir is not named the same as the Markdown file):

    +-- todo.md
    +-- img/
        +-- my_large_image.png

Then, MkDocs would generate the following structure:

    +-- todo/
        +-- index.html
    +-- img/
        +-- my_large_image.png

In which case a link from the document to the image would correctly be `../img/my_large_image.png`. Whats confusing you is the fact that your img dir is the same name as the Markdown file (without the file extension). So everything is working fine.

As I mentioned before, the code that handles this URL manipulation ignores raw HTML, so yes, your raw HTML links would be broken and you would need to edit them manually. And yes, if you do so, they will be broken in every other environment. For the recod, we have no intention of changing this in the foreseeable future. You should not use raw HTML to link internally when you have  `use_directory_urls=True`.

However, if you have  `use_directory_urls=False`, then all that extra directory rearranging and URL munging does not happen. Your original structure would generate the following output structure:

    +-- todo.html
    +-- todo/
        +-- my_large_image.png

And the link to the img would be `todo/my_large_image.png`, which should work in any environment. If that is not working, then I'll need more info about that.

**Comment by waylan** [comment]
We need to do a better job of warning people about these potential pitfalls in the documentation. I've given this the "Documentation" label to remind us to do that.

**Comment by ostrokach** [comment]
Thanks for your help!

Regarding the following:

> However, if you have use_directory_urls=False, then all that extra directory rearranging and URL munging does not happen. Your original structure would generate the following output structure:
> ```
> +-- todo.html
> +-- todo/
>     +-- my_large_image.png
> ```
> And the link to the img would be todo/my_large_image.png, which should work in any environment. If that is not working, then I'll need more info about that.

I renamed the `todo` folder and links to `img`, and added `use_directory_urls: false` to my `mkdocs.yml` file. However, for me, running `mkdocs build` still produces the following directory structure:

```
+-- todo/
    +-- index.html
+-- img/
    +-- my_large_image.png
```

The difference between `use_directory_urls: true` and `use_directory_urls: false` appears to be that, in the former, the URL for the todo page is at `http://127.0.0.1:8000/todo/` and, in the latter, it is at `http://127.0.0.1:8000/todo/index.html`.

I created a demo github repository so that you can see what is going on: https://github.com/ostrokach/mkdocs-test.

The todo page is here: https://ostrokach.github.io/mkdocs-test/todo/index.html

Having MkDocs produce the directory structure that you show for `use_directory_urls: false`, would be ideal. However, I understand if that would take too much work to implement at this point.

**Comment by waylan** [comment]
Are you running your build with the `--clean` flag? If not, then the problem may be that remnants of a previous build still exist.

In any event, it would seem we have a bug here. I'll need to investigate later when I have some time.

**Comment by waylan** [comment]
Okay, I'm confused. I've always assumed that `use_directory_urls: false` has the behavior I described above. Apparently, however, regardless of the setting, all pages are nested in dirs and given `index.html` as a file name. __WHY?__ Shouldn't we only be replacing the `.md` file extension with `.html` and leaving it as-is otherwise (not creating nested `index.html` files)? I can fix this, but based on comments in the code, this behavior appears to be intentional. Any insight @d0ugal @tomchristie?

**Comment by d0ugal** [comment]
This behaviour has always existed to create "pretty" urls. For example `http://www.mkdocs.org/user-guide/configuration/` rather than `http://www.mkdocs.org/user-guide/configuration.html`. I've never been a huge fan of it, and it has caused many bugs, that I've tried to fix a few times but always seem to miss something.

I thought I had fixed this particular bug in the past, but I guess not.

**Comment by waylan** [comment]
I understand why the feature exists, however with the feature turned off, we get `http://www.mkdocs.org/user-guide/configuration/index.html` rather than `http://www.mkdocs.org/user-guide/configuration.html`. I assumed this was a bug, however, the comments in the code seem to indicate it is intentional... which makes no sense to me.

As both you and I assumed things work differently with the feature turned off than it actually does, perhaps one of us introduced bugs.

**Comment by d0ugal** [comment]
Right, so I can't fully speak for that decision as it predates me. However, I assume it is done for simplicity and to allow all the other relative path handling to remain the same.

**Comment by waylan** [comment]
> I assume it is done for simplicity and to allow all the other relative path handling to remain the same.

That was my assumption as well. However, I consider the decision to be a bad one. In fact, personally, I think the feature should be turned off by default with no URL munging. Then, if users really want "pretty URLs" they can turn the feature on. And I would think the feature (when on) should behave more like Jekyll's [Extensionless Permalinks][1] (which also avoids most of the URL munging we do). It would certainly simplify/eliminate all these annoying bugs and its easy to [add][2] to the dev server.

Of course, that would be a backward incompatible change. Even if we don't go that route, it is not clear to me what the correct way forward is here.

[1]: https://jekyllrb.com/docs/permalinks/#extensionless-permalinks
[2]: https://github.com/lepture/python-livereload/pull/131

**Comment by rmzelle** [comment]
I'm testing mkdocs to see if I can switch from pandoc, and differences in file/url organization also trip up my migration. My existing source file layout is:

```
index.md
+-- topicA/
    +-- index.md
    +-- topicA.png
+-- topicB/
    +-- index.md
    +-- topicB.png
```

Both pandoc and mkdocs produce this:

```
index.html
+-- topicA/
    +-- index.html
    +-- topicA.png
+-- topicB/
    +-- index.html
    +-- topicB.png
```

However, while pandoc correctly recognizes image links like `![picture](topicA.png)` in e.g. topicA/index.md (generating `<img src="topicA.png" alt="picture">`), mkdocs creates a broken link (`<img alt="picture" src="../topicA.png">`), expecting the image file to be present in the root directory. 

(I also have an issue where pandoc converts `[topicA](topicA/)` in the root's index.md to `<a href="topicA/">topicA</a>`, whereas mkdocs produces `<a href="./topicA/">topicA</a>` (Chrome interprets the latter as a "file:///" path to the topicA subdirectory instead of a link to show topicA/index.html)
